(()=>{
const fmt076=s=>{s=Math.max(0,Math.floor(Number(s)||0));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
const nowSec076=()=>Math.max(0,Math.floor(rawActiveMs()/1000));
const nowMin076=()=>Math.floor(nowSec076()/60);
const css=document.createElement('style');css.textContent=`
/* v0.7.6: één live tijdweergave; oude afgeronde dubbele metrics verbergen */
#fieldBoard .liveplayer>.metrics,#benchBoard .liveplayer>.metrics{display:none!important}
.live074Grid{margin-top:6px!important}.live074Metric b{font-variant-numeric:tabular-nums}
.pitch074{font-variant-numeric:tabular-nums}
#rotation074 .rot074Row{grid-template-columns:1.25fr .55fr .55fr .75fr .75fr!important}
.cloudControl076{display:flex;gap:6px;flex-wrap:wrap;margin-top:7px}.cloudControl076 button{width:auto!important;min-height:34px!important;padding:6px 9px!important;font-size:11px!important;margin:0!important}.cloudDelete076{background:#983263!important}.cloudFinish076{background:#b98928!important;color:#fff!important}
#clockLegend076{margin:7px 0;padding:8px 10px;border:1px solid #eadcf5;border-radius:10px;background:#faf7fd;color:#4b2672;font-size:10px}
@media(max-width:720px){#rotation074 .rot074Row{grid-template-columns:1.2fr .55fr .7fr!important}#rotation074 .rot074Row span:nth-child(4),#rotation074 .rot074Row span:nth-child(5){display:none}}
`;document.head.appendChild(css);

let manual076={swap:false,pos:false,goal:false};
function bindLiveMinute076(id,key){const el=document.getElementById(id);if(!el||el.dataset.live076)return;el.dataset.live076='1';el.addEventListener('input',()=>manual076[key]=true);el.addEventListener('dblclick',()=>{manual076[key]=false;el.value=nowMin076()});let n=document.createElement('div');n.className='liveMinute075';n.id=id+'Live076';el.after(n)}
function syncInput076(id,key){const el=document.getElementById(id);if(!el)return;const m=nowMin076();if(!manual076[key]&&document.activeElement!==el)el.value=m;const n=document.getElementById(id+'Live076');if(n)n.textContent=`Live wedstrijdminuut: ${m}' · klok ${fmt076(nowSec076())}`}
function syncAllInputs076(){bindLiveMinute076('swapMinute','swap');bindLiveMinute076('positionMinute','pos');bindLiveMinute076('goalMinute','goal');syncInput076('swapMinute','swap');syncInput076('positionMinute','pos');syncInput076('goalMinute','goal')}

/* Nieuwe acties bewaren naast minuut ook de exacte effectieve wedstrijdseconde. */
try{const oldConfirm076=confirmPending;confirmPending=function(){if(pending){const sec=nowSec076();if(pending.type==='WISSEL'&&!manual076.swap){pending.minute=Math.floor(sec/60);pending.second=sec}if(pending.type==='GOAL'&&!manual076.goal){pending.minute=Math.floor(sec/60);pending.second=sec}}const before=(state.events||[]).length,r=oldConfirm076();const sec=nowSec076();(state.events||[]).slice(before).forEach(e=>{if(e.second==null)e.second=sec});return r}}catch(e){}
try{const oldPos076=changePosition;changePosition=function(){if(!manual076.pos){const el=document.getElementById('positionMinute');if(el)el.value=nowMin076()}const before=(state.events||[]).length,sec=nowSec076(),r=oldPos076();(state.events||[]).slice(before).filter(e=>e.type==='POSITIE').forEach(e=>{e.minute=Math.floor(sec/60);e.second=sec});try{saveLive();renderLive()}catch(e){}return r}}catch(e){}

/* Bij Cloud-refresh exacte match_second terugzetten wanneer de server die heeft. */
try{const oldApply076=cloudApplyLiveSnapshot;cloudApplyLiveSnapshot=function(snap){oldApply076(snap);try{const raw=snap?.events||[],by=Object.fromEntries(raw.map(e=>[e.id,e]));(state.events||[]).forEach(e=>{const r=e.cloudEventId?by[e.cloudEventId]:null;if(r&&r.match_second!=null)e.second=Number(r.match_second);else if(e.second==null)e.second=(Number(e.minute)||0)*60})}catch(err){}}}catch(e){}

function exact076(){
 const snap=snapshot(),now=nowSec076(),endMin=Math.floor(now/60),remainder=now-endMin*60,map={};
 (state.selectedIds||[]).forEach(id=>{const field=snap.open[id]!==undefined,playMin=Number(snap.play?.[id])||0,benchMin=Number(snap.bench?.[id])||0;map[id]={id,status:field?'field':'bench',position:snap.positions?.[id]||'',playSec:playMin*60+(field?remainder:0),benchSec:benchMin*60+(!field?remainder:0),in:0,out:0,total:0,last:null,currentSec:now,started:(state.starterIds||[]).includes(id)}});
 const subs=(state.events||[]).filter(e=>e.type==='WISSEL').slice().sort((a,b)=>(Number(a.second??a.minute*60)||0)-(Number(b.second??b.minute*60)||0)||((a.seq||0)-(b.seq||0)));
 for(const e of subs){const sec=Math.max(0,Math.min(now,Number(e.second??e.minute*60)||0));if(map[e.outId]){map[e.outId].out++;map[e.outId].total++;map[e.outId].last={dir:'UIT',minute:e.minute??Math.floor(sec/60),second:sec}}if(map[e.inId]){map[e.inId].in++;map[e.inId].total++;map[e.inId].last={dir:'IN',minute:e.minute??Math.floor(sec/60),second:sec}}}
 Object.values(map).forEach(x=>{const rel=subs.filter(e=>x.status==='field'?e.inId===x.id:e.outId===x.id).sort((a,b)=>(Number(a.second??a.minute*60)||0)-(Number(b.second??b.minute*60)||0)).at(-1);x.currentSec=Math.max(0,now-(rel?Number(rel.second??rel.minute*60)||0:0));x.share=now?Math.round(100*x.playSec/now):0});
 return{snap,now,map};
}
function cardId076(card){if(card.dataset.playerId)return card.dataset.playerId;const n=(card.querySelector('.num')?.textContent||'').replace(/\D/g,'');return (state.selectedIds||[]).find(id=>String(p(id).number)===n)||''}
function updateCards076(u){['fieldBoard','benchBoard'].forEach(rootId=>{const root=document.getElementById(rootId);if(!root)return;[...root.children].forEach(card=>{const id=cardId076(card),x=u.map[id];if(!x)return;const g=card.querySelector('.live074Grid');if(g){const b=g.querySelectorAll('b');if(b[0])b[0].textContent=fmt076(x.playSec);if(b[1])b[1].textContent=fmt076(x.benchSec);if(b[2])b[2].textContent=x.status==='field'?fmt076(Math.min(x.currentSec,x.playSec)):'—';if(b[3])b[3].textContent=x.status==='bench'?fmt076(Math.min(x.currentSec,x.benchSec)):'—'}const m=card.querySelector('.live074Meta');if(m)m.innerHTML=`<span class="${x.status==='field'?'stateField':'stateBench'}">${x.status==='field'?'VELD':'BANK'}</span><span>${x.started?'BASIS':'RESERVE'}</span><span>${x.position||'—'}</span><span>IN ${x.in}×</span><span>UIT ${x.out}×</span><span>↕ ${x.total}×</span><span>${x.last?'laatste '+x.last.dir+' '+x.last.minute+"'":'geen wissel'}</span><span>veld ${x.share}%</span>`})})}
function updatePitch076(u){const pitch=document.getElementById('livePitch');if(!pitch)return;pitch.querySelectorAll('.slot').forEach(slot=>{const dot=slot.querySelector('.dot');if(!dot)return;const txt=[...dot.childNodes].find(n=>n.nodeType===3&&n.textContent.trim()),num=(txt?.textContent||'').replace(/\D/g,''),id=(state.selectedIds||[]).find(x=>String(p(x).number)===num),x=u.map[id];if(!x||x.status!=='field')return;let inf=slot.querySelector('.pitch074');if(!inf){inf=document.createElement('div');inf.className='pitch074';slot.appendChild(inf)}inf.textContent=`Σ ${fmt076(x.playSec)} · ▶ ${fmt076(Math.min(x.currentSec,x.playSec))} · ↕${x.total}`})}
function updateMonitor076(u){const r=document.getElementById('rotation074');if(!r)return;const rows=Object.values(u.map).sort((a,b)=>b.currentSec-a.currentSec);r.innerHTML='<div class="rot074Title">Wisselmonitor · dezelfde doorlopende klok als veld en bank</div><div class="rot074Row rot074Head"><span>Speler</span><span>Status</span><span>Pos.</span><span>Huidige beurt</span><span>Totaal</span></div>'+rows.map(x=>`<div class="rot074Row"><span>${p(x.id)?.name||x.id}</span><span>${x.status==='field'?'VELD':'BANK'}</span><span>${x.position||'—'}</span><span class="${x.status==='bench'&&x.currentSec>=900?'rot074Warn':''}">${fmt076(x.currentSec)}</span><span>${fmt076(x.status==='field'?x.playSec:x.benchSec)}</span></div>`).join('')}
function ensureLegend076(){let a=document.getElementById('liveIntegrity074');if(!a)return;let l=document.getElementById('clockLegend076');if(!l){l=document.createElement('div');l.id='clockLegend076';a.after(l)}l.innerHTML='<b>Doorlopende tijden:</b> wedstrijdklok, goal-/wissel-/positieminuut, speeltijd, banktijd, huidige veldbeurt en huidige bankbeurt gebruiken dezelfde effectieve wedstrijdklok. Tijdens rust/pauze staan deze speeltijden stil.'}

async function rpcClock076(action){const params={p_match_id:cloudActiveMatchId,p_action:action,p_client_event_id:(crypto.randomUUID?crypto.randomUUID():cloudUuid()),p_minutes:null};let res=await cloudClient.rpc('advance_match_clock',params);if(res.error&&/permission|jwt|token|auth/i.test(res.error.message||'')){try{await cloudClient.auth.refreshSession()}catch(e){}params.p_client_event_id=(crypto.randomUUID?crypto.randomUUID():cloudUuid());res=await cloudClient.rpc('advance_match_clock',params)}if(res.error)throw res.error;await cloudReloadActiveMatch();await cloudLoadTeamsAndOpenMatches();return res.data}
async function finishCloud076(){if(!cloudActiveMatchId)return;if(!confirm('Wedstrijd definitief stoppen? De live klok stopt en de wedstrijd wordt afgesloten.'))return;try{await rpcClock076('finish');setStatus('Cloud-wedstrijd definitief gestopt.',true);cloudSetStatus('Wedstrijd afgesloten.',true)}catch(e){setStatus('Stoppen mislukt: '+e.message);cloudSetStatus('Stoppen mislukt: '+e.message)}}
async function deleteCloud076(id,label){if(!id)return;if(id===cloudActiveMatchId){alert('Stop de actieve wedstrijd eerst voordat je hem verwijdert.');return}if(!confirm(`Cloud-wedstrijd verwijderen?\n\n${label||''}\n\nDit kan niet ongedaan worden gemaakt.`))return;if(!confirm('Laatste waarschuwing: ook gekoppelde wedstrijddata kan worden verwijderd. Doorgaan?'))return;try{const q=await cloudClient.from('matches').delete().eq('id',id);if(q.error)throw q.error;await cloudLoadTeamsAndOpenMatches();setStatus('Cloud-wedstrijd verwijderd.',true);cloudSetStatus('Cloud-wedstrijd verwijderd.',true)}catch(e){setStatus('Verwijderen mislukt: '+e.message);cloudSetStatus('Verwijderen mislukt: '+e.message)}}
function decorateCloudMatches076(){const root=document.getElementById('cloudOpenMatches');if(!root)return;root.querySelectorAll('.matchcard').forEach(card=>{if(card.querySelector('.cloudControl076'))return;const open=card.querySelector('.cloudResumeBtn'),id=open?.dataset.id;if(!id)return;const ctl=document.createElement('div');ctl.className='cloudControl076';const label=card.querySelector('b')?.textContent||'';if(id===cloudActiveMatchId){const f=document.createElement('button');f.className='cloudFinish076';f.textContent='■ Wedstrijd stoppen';f.onclick=()=>finishCloud076();ctl.appendChild(f)}const d=document.createElement('button');d.className='cloudDelete076';d.textContent='🗑 Verwijderen';d.onclick=()=>deleteCloud076(id,label);ctl.appendChild(d);card.appendChild(ctl)})}
function tick076(){try{if(!state?.startMs)return;syncAllInputs076();if(state.cloud){const u=exact076();updateCards076(u);updatePitch076(u);updateMonitor076(u);ensureLegend076();decorateCloudMatches076()}}catch(e){console.warn('v0.7.6',e)}}
setInterval(tick076,1000);setTimeout(tick076,250);
})();