'use strict';
const assert=require('assert'),path=require('path');
require(path.resolve(__dirname,'../pitch-layout.js'));
require(path.resolve(__dirname,'../action-context-model-v08.js'));
const api=global.ClubMatchV08ActionContext;
let seq=0;const ids=()=>`id-${++seq}`;
const rw=global.ClubMatchV08PitchLayout.geometry('4-3-3').slots.find(s=>s.position==='RW');
const snapshot={match:{id:'m1',formation_code:'4-3-3',score_for:1,score_against:0},state:{period:'first_half',effective_elapsed_seconds:1902},players:[{player_id:'p1',selected:true,is_on_field:true,current_position:'RW',starting_position:'RW'}],events:[]};
function tacticalVsAction(){const s=api.createSession({idFactory:ids}),d=s.propose({snapshot,playerId:'p1',action:'cross',start:{x:91,y:14},end:{x:55,y:8}});assert.equal(d.tactical.position,'RW');assert.deepEqual(d.tactical.point,{x:rw.x,y:rw.y});assert.deepEqual(d.start,{x:91,y:14});assert.notDeepEqual(d.start,d.tactical.point);assert.equal(snapshot.players[0].current_position,'RW');console.log('PASS tactical-vs-action')}
function automaticPriority(){const s=api.createSession({idFactory:ids}),first=s.propose({snapshot,playerId:'p1',action:'shot'});assert.equal(first.coordinateSource,'tactical');assert.deepEqual(first.start,{x:rw.x,y:rw.y});s.commit({...first,end:{x:70,y:12}});const second=s.propose({snapshot:{...snapshot,state:{...snapshot.state,effective_elapsed_seconds:1905}},playerId:'p1',action:'cross'});assert.equal(second.coordinateSource,'chain');assert.deepEqual(second.start,{x:70,y:12});console.log('PASS coordinate-priority')}
function correctionIsolation(){const s=api.createSession({idFactory:ids}),d=s.commit(s.propose({snapshot,playerId:'p1',action:'shot'})),c=s.correct(d,{x:91,y:14},{x:50,y:2});assert.deepEqual(c.start,{x:91,y:14});assert.deepEqual(c.end,{x:50,y:2});assert.equal(c.tactical.position,'RW');assert.deepEqual(c.tactical.point,{x:rw.x,y:rw.y});assert.equal(snapshot.players[0].current_position,'RW');console.log('PASS correction-isolation')}
function payload(){const s=api.createSession({idFactory:ids}),d=s.commit(s.propose({snapshot,playerId:'p1',action:'cross',end:{x:52,y:10},relatedPlayerIds:['p2'],context:{pressure:'heavy_pressure',passing_options:'none',phase:'attack',target:'occupied'}})),p=s.contextPayload(d);assert.equal(p.context_version,1);assert.equal(p.tactical_position,'RW');assert.equal(p.score_for_at_event,1);assert.equal(p.score_against_at_event,0);assert.equal(p.match_phase,'first_half');assert.equal(p.pressure,'heavy_pressure');assert.equal(p.passing_options,'none');assert.ok(p.action_chain_id);assert.deepEqual(p.involved_player_ids,['p2']);assert.equal(p.action_context.phase,'attack');console.log('PASS payload')}
function hydrateRefresh(){const contextual={id:'e1',client_event_id:'ce1',event_type:'player_action',subject_player_id:'p1',match_minute:31,match_second:45,payload:{action:'cross',side:'for',action_start_x:91,action_start_y:14,action_end_x:54,action_end_y:9,tactical_x:rw.x,tactical_y:rw.y,tactical_position:'RW',action_chain_id:'chain-x',action_coordinate_source:'manual',context_version:1,action_context:{pressure:'pressure'}}};const s=api.createSession({idFactory:ids});s.hydrate({...snapshot,events:[contextual]});const d=s.state.lastAction;assert.deepEqual(d.start,{x:91,y:14});assert.deepEqual(d.end,{x:54,y:9});assert.equal(d.chainId,'chain-x');assert.equal(d.tactical.position,'RW');console.log('PASS refresh-persistence')}
function scale(){const events=Array.from({length:1000},(_,i)=>({id:'e'+i,client_event_id:'c'+i,event_type:'player_action',subject_player_id:'p1',match_minute:Math.floor(i/60),match_second:i%60,payload:{action:'pass_completed',side:'for',action_start_x:i%100,action_start_y:50,action_end_x:(i+1)%100,action_end_y:49,tactical_position:'RW',action_chain_id:'ch'+Math.floor(i/10),context_version:1}}));const s=api.createSession({idFactory:ids}),start=process.hrtime.bigint();s.hydrate({...snapshot,events});const ms=Number(process.hrtime.bigint()-start)/1e6;assert.equal(s.state.recent.length,api.MAX_RECENT);assert.equal(s.state.lastAction.id,'e999');assert.ok(ms<150,`1000 events hydrate te traag: ${ms.toFixed(1)}ms`);console.log('PASS scale '+ms.toFixed(1)+'ms')}
function actionSpecific(){const pass=api.contextOptions('pass'),shot=api.contextOptions('shot');assert.ok(pass.direction.includes('forward'));assert.ok(shot.chance.includes('open'));assert.ok(!shot.direction);console.log('PASS action-specific-context')}
[tacticalVsAction,automaticPriority,correctionIsolation,payload,hydrateRefresh,scale,actionSpecific].forEach(fn=>fn());console.log('PASS context coordinate suite');