'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function load(name,extra={}){const c={console,setTimeout,clearTimeout,setInterval,clearInterval,Date,Math,Object,Array,Map,Set,Promise,Error,JSON,String,Number,Boolean,RegExp,TextEncoder,Uint8Array,...extra};c.globalThis=c;c.window=c;vm.createContext(c);vm.runInContext(src(name),c,{filename:name});return c}
async function formations(){const c=load('pitch-layout.js');vm.runInContext(src('formation-layout.js'),c);const formations=c.ClubMatchV08Formation.FORMATIONS,pitch=c.ClubMatchV08PitchLayout;assert.strictEqual(Object.keys(formations).length,14);for(const [code,slots] of Object.entries(formations)){assert.strictEqual(slots.length,11,code);assert.strictEqual(new Set(slots).size,11,code);assert.strictEqual(pitch.geometry(code).slots.length,11,code)}assert.deepStrictEqual(Array.from(pitch.validate()),[])}
function timelineWindow(){const c=load('runtime.js'),events=Array.from({length:1000},(_,i)=>({id:`e${i}`,match_minute:Math.floor(i/60),match_second:i%60})),out=c.ClubMatchV08Runtime.timelineEvents({events});assert.strictEqual(out.length,240);assert.strictEqual(out[0].id,'e760');assert.strictEqual(out.at(-1).id,'e999')}
async function singleFlight(){let version=1,goals=0,pens=0;const c=load('mutation-controller.js'),snapshot=()=>({match:{id:'m1',status:'live'},state:{state_version:version},players:[{player_id:'p1',selected:true,is_on_field:true},{player_id:'p2',selected:true,is_on_field:true}]}),live=()=>({players:{p1:{currentRole:'FIELD',currentPosition:'ST'},p2:{currentRole:'FIELD',currentPosition:'RW'}},fieldIds:['p1','p2']}),rpc=async(name)=>{if(name==='get_match_snapshot')return {data:snapshot()};if(name==='record_goal'){goals++;await new Promise(r=>setTimeout(r,15));version++;return {data:{ok:true}}}if(name==='record_match_penalty_v08'){pens++;await new Promise(r=>setTimeout(r,15));version++;return {data:{ok:true}}}throw new Error(name)};const ctl=c.ClubMatchV08MutationController.createMutationController({rpc,deriveSnapshot:live,renderConfirmed:()=>{},idFactory:()=>Math.random().toString()});await Promise.all([ctl.recordGoal({matchId:'m1',side:'for',scorerId:'p1'}),ctl.recordGoal({matchId:'m1',side:'for',scorerId:'p1'})]);await Promise.all([ctl.recordPenalty({matchId:'m1',side:'for',outcome:'missed',takerId:'p1',fouledPlayerId:'p2'}),ctl.recordPenalty({matchId:'m1',side:'for',outcome:'missed',takerId:'p1',fouledPlayerId:'p2'})]);assert.strictEqual(goals,1);assert.strictEqual(pens,1)}
function csv1000(){const c=load('match-library-ui.js'),events=Array.from({length:1000},(_,i)=>({id:`e${i}`,event_type:'player_action',match_minute:Math.floor(i/60),match_second:i%60,subject_player_id:'p1',payload:{action:'pass_completed',note:`actie ${i}`}})),csv=c.ClubMatchV08MatchLibraryUi.buildCsv({match:{id:'m1',team_name:'Club',opponent_name:'Tegenstander'},players:[{player_id:'p1',selected:true,display_name:'Speler'}],events},{});assert(csv.length>50000);assert(csv.includes('actie 999'));assert(csv.includes('Gebeurtenis'))}
function boundedLiveArchitecture(){const runtime=src('runtime.js'),controller=src('player-action-controller-v10.js');assert(runtime.includes('LIVE_EVENT_WINDOW=240'));assert(runtime.includes('get_match_live_snapshot_v08'));assert(runtime.includes('waitForClientEvent'));assert(controller.includes('waitForClientEvent'));assert(!controller.includes("await runtime.refresh(name,true);snapshot=runtime.snapshot||snapshot;return result?.data}\n async function rawRecord")||runtime.includes('realtimeConnected'))}
(async()=>{const tests={formations,timelineWindow,singleFlight,csv1000,boundedLiveArchitecture};for(const [n,t] of Object.entries(tests)){await t();console.log('PASS '+n)}console.log(`PASS all ${Object.keys(tests).length} core 1700 regressions`)})().catch(e=>{console.error(e);process.exit(1)});
