'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..');
function src(name){return fs.readFileSync(path.join(root,name),'utf8')}
function load(name,extra={}){const c={console,setTimeout,clearTimeout,Date,Math,Object,Array,Map,Set,Promise,Error,JSON,String,Number,Boolean,RegExp,TextEncoder,Uint8Array,...extra};c.globalThis=c;c.window=c;vm.createContext(c);vm.runInContext(src(name),c,{filename:name});return c}
async function formations(){const c=load('pitch-layout.js');vm.runInContext(src('formation-layout.js'),c);const f=c.ClubMatchV08Formation.FORMATIONS,p=c.ClubMatchV08PitchLayout;assert.strictEqual(Object.keys(f).length,14);for(const [code,slots] of Object.entries(f)){assert.strictEqual(slots.length,11);assert.strictEqual(new Set(slots).size,11);assert.strictEqual(p.geometry(code).slots.length,11)}assert.deepStrictEqual(Array.from(p.validate()),[])}
function timeline(){const c=load('runtime.js'),events=Array.from({length:1000},(_,i)=>({id:`e${i}`,match_minute:Math.floor(i/60),match_second:i%60})),out=c.ClubMatchV08Runtime.timelineEvents({events});assert.strictEqual(out.length,240);assert.strictEqual(out[0].id,'e760');assert.strictEqual(out.at(-1).id,'e999')}
async function singleFlight(){let version=1,goals=0,pens=0;const c=load('mutation-controller.js'),snapshot=()=>({match:{id:'m1',status:'live'},state:{state_version:version},players:[{player_id:'p1',selected:true,is_on_field:true},{player_id:'p2',selected:true,is_on_field:true}]}),live=()=>({players:{p1:{currentRole:'FIELD',currentPosition:'ST'},p2:{currentRole:'FIELD',currentPosition:'RW'}},fieldIds:['p1','p2']}),rpc=async(name)=>{if(name==='get_match_snapshot')return {data:snapshot()};if(name==='record_goal'){goals++;await new Promise(r=>setTimeout(r,20));version++;return {data:{ok:true}}}if(name==='record_match_penalty_v08'){pens++;await new Promise(r=>setTimeout(r,20));version++;return {data:{ok:true}}}throw new Error(name)};const ctl=c.ClubMatchV08MutationController.createMutationController({rpc,deriveSnapshot:live,renderConfirmed:()=>{},idFactory:()=>Math.random().toString()});await Promise.all([ctl.recordGoal({matchId:'m1',side:'for',scorerId:'p1'}),ctl.recordGoal({matchId:'m1',side:'for',scorerId:'p1'})]);await Promise.all([ctl.recordPenalty({matchId:'m1',side:'for',outcome:'missed',takerId:'p1',fouledPlayerId:'p2'}),ctl.recordPenalty({matchId:'m1',side:'for',outcome:'missed',takerId:'p1',fouledPlayerId:'p2'})]);assert.strictEqual(goals,1);assert.strictEqual(pens,1)}
function state(){return {teamSeasons:[{team_season_id:'ts1',club_name:'Hercules',team_name:'O16-1',season_name:'2026/2027'}],teamPossession:{total:{for_pct:58,against_pct:42,for_seconds:2161,against_seconds:1577}},teamPerformance:{version:'cm-team-performance-v1',matches:1,wins:0,draws:0,losses:1,team_performance_pct:61.5,teamplay_pct:68.2,data_coverage_pct:95,passes:{completed:80,failed:20,attempted:100,accuracy_pct:80},possession:{pct:58,for_seconds:2161,against_seconds:1577},duels:{won:6,lost:4,win_pct:60},shooting:{shots:8,on_target:4,on_target_pct:50,chances_created:5},defending:{recoveries:12,losses:8,recovery_control_pct:60,interceptions:7,blocks:3,saves:4},discipline:{fouls_won:4,fouls_committed:3},formula:{}},dashboard:{teamSeasonId:'ts1',kpis:{matches:1,available_matches:1,play_minutes:900,bench_minutes:300,goals:0,assists:0,actions:1000,possession_seconds:2100,absent:0},ratingModel:{min:1,max:100,base:50,normalizationMinutes:80,minimumNormalizerMinutes:20,weights:{goal:12,assist:8,ball_recovery:2,ball_loss:-1.5,shot_on_target:2}},players:[{player_id:'p1',number:13,name:'Wai Sam',display_name:'Wai Sam',play:80,playPct:100,goals:0,assists:0,rating:55,ratingReliability:'laag',actionTotal:10,possessionSeconds:100,possessionShare:10,actions:{ball_recovery:4,ball_loss:2,interception:2},relationships:{passCompleted:8,badPass:2,passReceived:10,passCompletionPct:80,ballLossPerReceivedPct:20,duelWon:3,duelLost:2,duelWinPct:60,shots:2,shotsOnTarget:1,shotOnTargetPct:50}}],matches:[{id:'m1',match_date:'2026-08-29',team:'O16-1',opponent:'Geel Wit',score_for:0,score_against:2,duration:84,formation:'4-4-2',action_count:1000,possession_seconds:2100,possession_pct:58,include_in_dashboard:true}]}}}
function rating(){const c=load('dashboard-ui.js'),b=c.ClubMatchV08DashboardUi.ratingBreakdown(state().dashboard.players[0],state().dashboard.ratingModel);assert.strictEqual(b.raw,5);assert.strictEqual(b.calculated,55)}
function performance(){const c=load('dashboard-controller.js'),p=c.ClubMatchV08Dashboard.normalizePerformance({team_performance_pct:72.4,teamplay_pct:75.1,data_coverage_pct:85,passes:{completed:80,failed:20,attempted:100,accuracy_pct:80},duels:{won:6,lost:4,win_pct:60}});assert.strictEqual(p.team_performance_pct,72.4);assert.strictEqual(p.teamplay_pct,75.1);assert.strictEqual(p.passes.completed,80);assert.strictEqual(p.duels.win_pct,60)}
function csv1000(){const c=load('match-library-ui.js'),events=Array.from({length:1000},(_,i)=>({id:`e${i}`,event_type:'player_action',match_minute:Math.floor(i/60),match_second:i%60,subject_player_id:'p1',payload:{action:'pass_completed',note:`actie ${i}`}})),csv=c.ClubMatchV08MatchLibraryUi.buildCsv({match:{id:'m1',team_name:'Hercules',opponent_name:'Geel Wit',score_for:0,score_against:2},players:[{player_id:'p1',selected:true,is_starter:true,display_name:'Speler',shirt_number:1}],events},{});assert(csv.length>50000);assert(csv.includes('actie 999'));assert(csv.includes('Payload JSON'));assert(csv.split('\r\n').length>=1003)}
function exports(){const dash=load('dashboard-ui.js'),c=load('report-export.js',{ClubMatchV08DashboardUi:dash.ClubMatchV08DashboardUi}),xls=c.ClubMatchV08Reports.buildExcel(state());assert(xls.includes('Team Performance %'));assert(xls.includes('Samenspel %'));assert(xls.includes('Passes goed'));assert(xls.includes('Wai Sam'));const pdf=c.ClubMatchV08Reports.pdfFromJpegs([new Uint8Array([255,216,255,217])]),txt=Buffer.from(pdf).toString('latin1');assert(txt.startsWith('%PDF-1.4'));assert(txt.includes('/Subtype /Image'));assert(txt.includes('xref'));assert(txt.endsWith('%%EOF'))}
function wiring(){const lib=src('match-library-ui.js'),dash=src('dashboard-ui.js'),ctl=src('dashboard-controller.js'),report=src('report-export.js');for(const rpc of ['add_match_event_v08','edit_match_event_v08','void_match_event_v08','delete_match_v08'])assert(lib.includes(rpc));assert(ctl.includes('get_team_performance_dashboard_v08'));assert(dash.includes('Team Performance %')&&dash.includes('Samenspel %'));assert(dash.includes('Passes aangekomen')&&dash.includes('Foute passes'));assert(!dash.includes('Typ DELETE'));assert(report.includes('downloadTeamInfographicPdf')&&report.includes('downloadTeamInfographicPng'))}
function bootstrap(){const index=src('index.html'),runtime=src('runtime.js'),analyst=src('analyst-live-input-v08.js');for(const legacy of ['roadmap-ux-v08.js','smart-registration-v08.js','v08-stabilization.js','live-analyst-polish-v08.js','tablet-matchday-hotfix-v08.js','pause-action-guard-v08.js','ux-theme.js','dashboard-player-tiles-v08.js'])assert(!index.includes(legacy));assert(index.includes('browser-bootstrap-v08.js'));assert(index.includes('report-export.js'));assert(index.includes('build 20260829.0700'));assert(runtime.includes('get_match_live_snapshot_v08'));assert(analyst.includes("['live','halftime'].includes"));assert(analyst.includes('niet opgeslagen tijdens pauze/rust'))}
(async()=>{const tests={formations,timeline,singleFlight,rating,performance,csv1000,exports,wiring,bootstrap};for(const [name,test] of Object.entries(tests)){await test();console.log(`PASS ${name}`)}console.log(`PASS all ${Object.keys(tests).length} modular gates`)})().catch(e=>{console.error(e);process.exit(1)});