'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');const root=path.resolve(__dirname,'..'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function release(){const i=src('index.html');for(const t of ['build 20260903.1800','product-navigation-v10.js?v=20260903.1800','youth-development-v10.js?v=20260903.1800','live-action-field-v13.js?v=20260903.1800','stored-match-delete-ui.js?v=20260903.1800'])assert(i.includes(t),t);for(const old of ['build 20260831.1700','roadmap-ux-v08.js','tablet-matchday-hotfix-v08.js'])assert(!i.includes(old),old)}
function lateGuest(){const a=src('app.js');for(const t of ['Speler later / gastspeler','get_late_arrival_candidates_v10','add_late_player_to_match_v10','guest_player','source_team_name'])assert(a.includes(t),t)}
function liveRosterAndActionPoint(){const s=src('live-action-field-v13.js');for(const t of ['Rolpositie ≠ actiepositie','speler → lege plek op veld → actie','manualActionPoint','renderPlayers(force=false)'])assert(s.includes(t),t);assert(!s.includes('global.innerWidth<=600||e.target.closest'), 'mobiel mag lege veldactiepositie niet blokkeren');assert(s.includes('wanted.has')||s.includes('wanted=new Set')||s.includes('wanted = new Set'),'live roster moet bestaande tegels reconciliëren')}
function deletion(){const s=src('stored-match-delete-ui.js');for(const t of ['authoritative match deletion owner','deleteAndVerify','verifyGone','get_my_match_library_v08','stopImmediatePropagation','refreshMatchesBtn'])assert(s.includes(t),t)}
function productNavigation(){const s=src('product-navigation-v10.js');for(const t of ['Sportlink competitie-sync','GEPLAND · NIET VERBONDEN','Stannet VPS','Matchday Simple','Development Coach','Training Planner','Club Academy'])assert(s.includes(t),t)}
function youth(){const s=src('youth-development-v10.js');for(const t of ["'25-50-65'",'Gelijke speeltijd','Ontwikkelminuten','Belastingsgestuurd','Prestatie / tactisch','Custom','Voorstel','Van wedstrijd naar training','Trainingsvorm','fysio'])assert(s.includes(t),t)}
function roadmap(){const s=src('ROADMAP_1800_ADDENDUM.md');for(const t of ['Sportlink','25-50-65','Wisselbeleid','Training Planner','Club Academy','Stannet VPS','Rolpositie ≠ actiepositie'])assert(s.includes(t),t)}
function architecture(){const r=src('runtime.js');assert(r.includes('LIVE_EVENT_WINDOW=240'));assert(r.includes('get_match_live_snapshot_v08'));}
for(const [n,f] of Object.entries({release,lateGuest,liveRosterAndActionPoint,deletion,productNavigation,youth,roadmap,architecture})){f();console.log('PASS '+n)}console.log('PASS all build 1800 release gates');
