'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),root=path.resolve(__dirname,'..'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function loadMany(names,extra={}){const c={console,Date,Math,Object,Array,Map,Set,Promise,Error,JSON,String,Number,Boolean,RegExp,...extra};c.globalThis=c;c.window=c;vm.createContext(c);for(const n of names)vm.runInContext(src(n),c,{filename:n});return c}
function index(){const s=src('index.html');assert(s.includes('build 20260831.1245'));assert(s.includes('live-action-field-v12.js?v=20260831.1245'));assert(s.includes('action-context-ui-v08.js?v=20260831.1245'));assert(!s.includes('live-action-field-v11.js?v='));}
function layoutPersistence(){const s=src('live-action-field-v12.js');for(const x of ["const LAYOUT_PREFIX='clubmatch.v08.laf.layout'",'legacyLayoutKeys','clubmatch.v11.laf.layout','clubmatch.v10.laf.layout','saveLayout','Indeling opgeslagen voor deze wedstrijd'])assert(s.includes(x),x);}
function liveStatus(){const s=src('live-action-field-v12.js');for(const x of ['data-live-status','refreshLiveStatus','live-action-field-manual','Live-status bijgewerkt'])assert(s.includes(x),x);}
function guidedPlacement(){const s=src('live-action-field-v12.js');for(const x of ['data-guide-slot="${key}"',"placeGuide('duel')","placeGuide('defense')",'Pass onderschept','Duel verloren','Slechte controle','Interceptie','Duel gewonnen','Bal veroverd'])assert(s.includes(x),x);}
function contextNonBlocking(){const s=src('action-context-ui-v08.js');for(const x of ['data-context-done','Context klaar · verder registreren','function closeContext','pending=br?.pendingChoice??null','contextBox.classList.add(\'hidden\')'])assert(s.includes(x),x);}
function contextVisible(){const c=loadMany(['event-describer.js','live-input-event-describer-v08.js']),api=c.ClubMatchV08EventDescriber,players={p1:{display_name:'Speler',shirt_number:9},p2:{display_name:'Fouled',shirt_number:4}},event={event_type:'player_action',subject_player_id:'p1',payload:{action:'bad_pass',context_version:1,action_context:{pressure:'pressure',passing_options:'none',phase:'transition'}}},d=api.describeEvent(event,players);assert(d.description.includes('Context:'));assert(d.description.includes('onder druk'));assert(d.description.includes('geen afspeelmogelijkheid'));assert(d.description.includes('omschakeling'));}
function penaltyClean(){const c=loadMany(['event-describer.js','live-input-event-describer-v08.js']),api=c.ClubMatchV08EventDescriber,players={p1:{display_name:'Speler',shirt_number:9},p2:{display_name:'Fouled',shirt_number:4}},e={event_type:'player_action',subject_player_id:'p1',payload:{action:'penalty',outcome:'missed',note:'Live Actieveld v09',fouled_player_id:'p2'}},d=api.describeEvent(e,players);assert(d.description.includes('Penalty · gemist'));assert(d.description.includes('overtreding op'));assert(!d.description.includes('v09'));}
function noInternalNotes(){const s=src('live-action-field-v12.js');assert(!s.includes("note:'Live Actieveld"));assert(s.includes('p_note:null'));}
for(const [n,t] of Object.entries({index,layoutPersistence,liveStatus,guidedPlacement,contextNonBlocking,contextVisible,penaltyClean,noInternalNotes})){t();console.log('PASS '+n)}console.log('PASS 1245 release suite');