'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),root=path.resolve(__dirname,'..'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function loadMany(names,extra={}){const c={console,Date,Math,Object,Array,Map,Set,Promise,Error,JSON,String,Number,Boolean,RegExp,...extra};c.globalThis=c;c.window=c;vm.createContext(c);for(const n of names)vm.runInContext(src(n),c,{filename:n});return c}
function index(){const s=src('index.html');assert(s.includes('build 20260831.1500'));assert(s.includes('live-action-field-v13.js?v=20260831.1500'));assert(s.includes('match-intelligence-v11.js?v=20260831.1500'));assert(s.includes('dashboard-pdf-v09.js?v=20260831.1500'));assert(!s.includes('live-action-field-v12.js?v='));}
function liveField(){const s=src('live-action-field-v13.js');for(const x of ["LAYOUT_PREFIX='clubmatch.v08.laf.layout'",'legacyLayoutKeys','data-live-status','refreshLiveStatus',"placeGuide('duel')","placeGuide('defense')",'classList.add(\'guided\')','lafPenaltyDecision','width:70px!important','p_note:null'])assert(s.includes(x),x);assert(!s.includes("note:'Live Actieveld"));}
function contextNonBlocking(){const s=src('action-context-ui-v08.js');for(const x of ['data-context-done','Context klaar · verder registreren','function closeContext','pending=br?.pendingChoice??null'])assert(s.includes(x),x);}
function contextVisible(){const c=loadMany(['event-describer.js','live-input-event-describer-v08.js']),api=c.ClubMatchV08EventDescriber,players={p1:{display_name:'Speler',shirt_number:9}},event={event_type:'player_action',subject_player_id:'p1',payload:{action:'bad_pass',context_version:1,action_context:{pressure:'pressure',passing_options:'none',phase:'transition'}}},d=api.describeEvent(event,players);assert(d.description.includes('Context:'));assert(d.description.includes('onder druk'));assert(d.description.includes('geen afspeelmogelijkheid'));assert(d.description.includes('omschakeling'));}
function penaltyClean(){const c=loadMany(['event-describer.js','live-input-event-describer-v08.js']),api=c.ClubMatchV08EventDescriber,players={p1:{display_name:'Speler',shirt_number:9},p2:{display_name:'Fouled',shirt_number:4}},e={event_type:'player_action',subject_player_id:'p1',payload:{action:'penalty',outcome:'missed',note:'Live Actieveld v09',fouled_player_id:'p2'}},d=api.describeEvent(e,players);assert(d.description.includes('Penalty · gemist'));assert(d.description.includes('overtreding op'));assert(!d.description.includes('Live Actieveld'));}
function intelligence(){const s=src('match-intelligence-v11.js');for(const x of ['Eerste helft','Tweede helft','Balbezit over de minuten','Impact van wissels en formatie','Player of the Match (POTM)','Box score / speelstatistieken','Voorstel volgende opstelling','Samenspel','Team Performance','Actie-afstand is geen echte loopafstand','5-minuten'])assert(s.includes(x),x);}
function pdfParity(){const s=src('dashboard-pdf-v09.js');for(const x of ['cloneDashboard','v08PerformanceAnalysis','Dashboard PDF · zoals website','dezelfde dashboarddata','window.print'])assert(s.includes(x),x);}
for(const [n,t] of Object.entries({index,liveField,contextNonBlocking,contextVisible,penaltyClean,intelligence,pdfParity})){t();console.log('PASS '+n)}console.log('PASS 1500 release suite');