'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),root=path.resolve(__dirname,'..'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function index(){const s=src('index.html');assert(s.includes('build 20260831.1045'));for(const x of ['action-context-model-v08.js?v=20260831.1045','action-context-persistence-v08.js?v=20260831.1045','player-action-controller-v10.js?v=20260831.1045','live-action-field-v10.js?v=20260831.1045','action-context-ui-v08.js?v=20260831.1045'])assert(s.includes(x),x);assert(!s.includes('player-action-controller.js?v='));assert(!s.includes('live-action-field-v09.js?v='))}
function separation(){const m=src('action-context-model-v08.js'),l=src('live-action-field-v10.js');for(const x of ['tacticalPoint','action_start_x','action_end_x','action_chain_id','action_coordinate_source','lastEnd','chain'])assert(m.includes(x),x);assert(l.includes('function visualOwnPoint'));assert(l.includes('function tacticalOwnPoint'));assert(l.includes('Live Veldpositie ≠ Actiepositie'));assert(!l.includes("runtime.changePosition"));}
function zeroExtraTap(){const l=src('live-action-field-v10.js');assert(l.includes('speler → actie → klaar'));assert(l.includes("if(a==='shot')"));assert(l.includes("if(a==='ball_loss')"));assert(!l.includes('Waardoor ging de bal verloren?'));assert(l.includes('lokaal verwerkt · Cloud synchroniseert'))}
function optionalContext(){const u=src('action-context-ui-v08.js');for(const x of ['Locatie aanpassen','Richting/target','+ Context','cmCtxFullscreen','max-width: 600px','contextOptions'])assert(u.includes(x),x);assert(u.includes("if(mobile())mobileLocation"))}
function persistence(){const p=src('action-context-persistence-v08.js');assert(p.includes('enrich_match_event_context_v08'));assert(p.includes('pending-event-context'));assert(p.includes("addEventListener?.('online'"));assert(!p.includes('runtime.refresh'));}
function manual(){const h=src('HANDLEIDING_LIVE_REGISTRATIE.md');for(const x of ['Live Veldpositie versus Actiepositie','Gebruik op desktop','Gebruik op tablet','Gebruik op mobiel','Pass','Dribbel','Voorzet','Schot','Balverlies','heatmaps','skillrating','videoanalyse'])assert(h.includes(x),x)}
function noLegacy(){const s=src('index.html');for(const x of ['roadmap-ux-v08.js','smart-registration-v08.js','v08-stabilization.js','live-analyst-polish-v08.js','tablet-matchday-hotfix-v08.js','pause-action-guard-v08.js','ux-theme.js','live-action-field-v09.js?v=','player-action-controller.js?v='])assert(!s.includes(x),x)}
function existingCore(){const r=src('runtime.js'),m=src('mutation-controller.js'),p=src('preparation-ui.js'),mgt=src('management-ui.js');assert(r.includes('LIVE_EVENT_WINDOW=240'));assert(r.includes('waitForClientEvent'));assert(m.includes('singleFlight'));assert(p.includes('draggable="true"'));assert(mgt.includes('data-member-remove'))}
for(const [n,t] of Object.entries({index,separation,zeroExtraTap,optionalContext,persistence,manual,noLegacy,existingCore})){t();console.log('PASS '+n)}console.log('PASS 1045 release suite');