'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),root=path.resolve(__dirname,'..'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function load(name,extra={}){const c={console,Date,Math,Object,Array,Map,Set,Promise,Error,JSON,String,Number,Boolean,RegExp,...extra};c.globalThis=c;c.window=c;vm.createContext(c);vm.runInContext(src(name),c,{filename:name});return c}
function index(){const s=src('index.html');assert(s.includes('build 20260831.1130'));assert(s.includes('live-action-field-v11.js?v=20260831.1130'));assert(s.includes('action-context-ui-v08.js?v=20260831.1130'));assert(!s.includes('live-action-field-v10.js?v='));}
function guidedPlacement(){const s=src('live-action-field-v11.js');for(const x of ['data-guide-slot="${key}"','placeGuide(\'duel\')','placeGuide(\'defense\')','Pass onderschept','Duel verloren','Slechte controle','Interceptie','Duel gewonnen','Bal veroverd'])assert(s.includes(x),x);}
function penaltyTiles(){const s=src('live-action-field-v11.js');for(const x of ['lafPenaltyDecision','class="scored"','class="missed"','class="saved"','class="cancel"','note:null'])assert(s.includes(x),x);}
function compactGroups(){const s=src('live-action-field-v11.js');assert(s.includes('white-space:nowrap'));assert(s.includes('.lafGroupButtons{display:flex'));assert(s.includes('flex-wrap:nowrap'));}
function contextRail(){const s=src('action-context-ui-v08.js');for(const x of ['cmCtxFieldRow','grid-template-columns:minmax(0,1fr) 280px','cmCtxRail','order:-1','Meerdere contextcategorieën tegelijk mogelijk','updatePendingContext'])assert(s.includes(x),x);}
function eventPenalty(){const c=load('event-describer.js'),api=c.ClubMatchV08EventDescriber,players={p1:{display_name:'Speler',shirt_number:9},p2:{display_name:'Fouled',shirt_number:4}},e={event_type:'player_action',subject_player_id:'p1',payload:{action:'penalty',outcome:'missed',note:'Live Actieveld v09',fouled_player_id:'p2'}},d=api.describeEvent(e,players);assert(d.description.includes('Penalty · gemist'));assert(d.description.includes('overtreding op'));assert(!d.description.includes('v09'));}
function noInternalNotes(){const s=src('live-action-field-v11.js');assert(!s.includes("note:'Live Actieveld"));assert(s.includes('p_note:null'));}
for(const [n,t] of Object.entries({index,guidedPlacement,penaltyTiles,compactGroups,contextRail,eventPenalty,noInternalNotes})){t();console.log('PASS '+n)}console.log('PASS 1130 release suite');