'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),root=path.resolve(__dirname,'..'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function load(n,extra={}){const c={console,setTimeout,clearTimeout,setInterval,clearInterval,Date,Math,Object,Array,Map,Set,Promise,Error,JSON,String,Number,Boolean,RegExp,TextEncoder,Uint8Array,...extra};c.globalThis=c;c.window=c;vm.createContext(c);vm.runInContext(src(n),c,{filename:n});return c}
function index(){const s=src('index.html');assert(s.includes('build 20260830.0850'));assert(s.includes('live-action-field-v09.js?v=20260830.0850'));assert(!s.includes('live-action-field-v08.js'));assert(s.includes('dashboard-layout-v09.js?v=20260830.0850'))}
function live(){const s=src('live-action-field-v09.js');for(const x of ['Pass onderschept','Duel verloren','Slechte controle','Bal veroverd','Duel gewonnen','Interceptie','Foute pass','Indeling aanpassen','Instructie manual','Historie 0 t/m −30','recommended'])assert(s.includes(x),x);assert(s.includes('record_inferred_pass_failure_v08'));assert(s.includes('analystLoseBall'));assert(s.includes('duel_won'));assert(s.includes('cmLiveHelp'));assert(!s.includes('if(S.forcedBadPass&&S.lastOwn)S.pendingLoss'),'Foute-pass knop mag pendingLoss niet vóór touchOpp zetten')}
function prep(){const s=src('preparation-ui.js');for(const x of ['Visuele basisopstelling','draggable="true"','data-prep-pitch','placeStarter','moveToBench','render(s,{show:true})','openExisting(match)','renderCurrent()'])assert(s.includes(x),x)}
function users(){const c=src('management-controller.js'),u=src('management-ui.js');for(const x of ['remove_club_membership_v09','clubmatch-user-delete','removeMembership','deleteUser'])assert(c.includes(x),x);for(const x of ['data-member-remove','data-user-delete','Uit club','Account verwijderen'])assert(u.includes(x),x)}
function info(){const s=src('dashboard-layout-v09.js');assert(s.includes('padding-right:48px'));assert(s.includes('.cmInfoAnchor>.cmInfoBtn'));assert(s.includes('.cmiScoreCard strong'))}
function noLegacy(){const s=src('index.html');for(const x of ['roadmap-ux-v08.js','smart-registration-v08.js','v08-stabilization.js','live-analyst-polish-v08.js','tablet-matchday-hotfix-v08.js','pause-action-guard-v08.js','ux-theme.js'])assert(!s.includes(x),x)}
function timeline1000(){const c=load('runtime.js'),events=Array.from({length:1000},(_,i)=>({id:`e${i}`})),out=c.ClubMatchV08Runtime.timelineEvents({events});assert.strictEqual(out.length,240);assert.strictEqual(out[0].id,'e760');assert.strictEqual(out.at(-1).id,'e999')}
async function singleFlight(){let version=1,goals=0;const c=load('mutation-controller.js'),snapshot=()=>({match:{id:'m',status:'live'},state:{state_version:version},players:[{player_id:'p',selected:true,is_on_field:true}]}),rpc=async n=>{if(n==='get_match_snapshot')return{data:snapshot()};if(n==='record_goal'){goals++;await new Promise(r=>setTimeout(r,10));version++;return{data:{ok:true}}}throw new Error(n)};const ctl=c.ClubMatchV08MutationController.createMutationController({rpc,deriveSnapshot:()=>({players:{p:{currentRole:'FIELD',currentPosition:'ST'}},fieldIds:['p']}),renderConfirmed:()=>{},idFactory:()=>Math.random().toString()});await Promise.all([ctl.recordGoal({matchId:'m',side:'for',scorerId:'p'}),ctl.recordGoal({matchId:'m',side:'for',scorerId:'p'})]);assert.strictEqual(goals,1)}
(async()=>{for(const [n,t] of Object.entries({index,live,prep,users,info,noLegacy,timeline1000,singleFlight})){await t();console.log('PASS '+n)}console.log('PASS 0850 release suite')})().catch(e=>{console.error(e);process.exit(1)});
