'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..');
function load(name,extra={}){const context={console,setTimeout,clearTimeout,Date,Math,Object,Array,Map,Set,Promise,Error,JSON,String,Number,Boolean,RegExp,...extra};context.globalThis=context;context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,name),'utf8'),context,{filename:name});return context}
async function testFormations(){const c=load('pitch-layout.js');vm.runInContext(fs.readFileSync(path.join(root,'formation-layout.js'),'utf8'),c,{filename:'formation-layout.js'});const pitch=c.ClubMatchV08PitchLayout,formations=c.ClubMatchV08Formation.FORMATIONS;assert.strictEqual(Object.keys(formations).length,14,'expected 14 formations');for(const [code,slots] of Object.entries(formations)){assert.strictEqual(slots.length,11,`${code}: 11 formation slots`);assert.strictEqual(new Set(slots).size,11,`${code}: unique formation slots`);const geometry=pitch.geometry(code);assert.strictEqual(geometry.code,code,`${code}: pitch geometry must not fall back`);assert.strictEqual(geometry.slots.length,11,`${code}: 11 pitch slots`);assert.strictEqual(new Set(geometry.slots.map(s=>s.position)).size,11,`${code}: unique pitch geometry`)}assert.deepStrictEqual(Array.from(pitch.validate()),[],'pitch validate should be clean')}
function testTimelineWindow(){const c=load('runtime.js');const events=Array.from({length:1000},(_,i)=>({id:`e${i}`,match_minute:Math.floor(i/60),match_second:i%60})),out=c.ClubMatchV08Runtime.timelineEvents({events});assert.strictEqual(out.length,240,'live timeline must be bounded to 240');assert.strictEqual(out[0].id,'e760');assert.strictEqual(out[239].id,'e999')}
function snapshot(version=1){return {match:{id:'m1',status:'live',score_for:0,score_against:0},state:{state_version:version},players:[{player_id:'p1',selected:true,is_on_field:true},{player_id:'p2',selected:true,is_on_field:true}]}}
function liveState(){return {players:{p1:{currentRole:'FIELD',currentPosition:'ST'},p2:{currentRole:'FIELD',currentPosition:'RW'}},fieldIds:['p1','p2']}}
async function testSingleFlight(){let version=1,goalWrites=0,penaltyWrites=0;const c=load('mutation-controller.js');const rpc=async(name,params)=>{if(name==='get_match_snapshot')return {data:snapshot(version)};if(name==='record_goal'){goalWrites++;await new Promise(r=>setTimeout(r,25));version++;return {data:{ok:true,params}}}if(name==='record_match_penalty_v08'){penaltyWrites++;await new Promise(r=>setTimeout(r,25));version++;return {data:{ok:true,params}}}throw new Error(`unexpected RPC ${name}`)};const ctl=c.ClubMatchV08MutationController.createMutationController({rpc,deriveSnapshot:()=>liveState(),renderConfirmed:()=>{},idFactory:()=>`id-${Math.random()}`});const a=ctl.recordGoal({matchId:'m1',side:'for',scorerId:'p1'}),b=ctl.recordGoal({matchId:'m1',side:'for',scorerId:'p1'});await Promise.all([a,b]);assert.strictEqual(goalWrites,1,'double goal click must create one goal RPC');const p1=ctl.recordPenalty({matchId:'m1',side:'for',outcome:'missed',takerId:'p1',fouledPlayerId:'p2'}),p2=ctl.recordPenalty({matchId:'m1',side:'for',outcome:'missed',takerId:'p1',fouledPlayerId:'p2'});await Promise.all([p1,p2]);assert.strictEqual(penaltyWrites,1,'double penalty click must create one penalty RPC')}
function dashboardState(){return {teamSeasons:[{team_season_id:'ts1',club_name:'Hercules',team_name:'O16-1',season_name:'2026/2027'}],teamPossession:{total:{for_pct:58,against_pct:42,for_seconds:2161,against_seconds:1577}},dashboard:{teamSeasonId:'ts1',kpis:{matches:1,available_matches:1,play_minutes:900,bench_minutes:300,goals:0,assists:0,actions:1000,possession_seconds:2100,absent:0},ratingModel:{min:1,max:100,base:50,normalizationMinutes:80,minimumNormalizerMinutes:20,weights:{goal:12,assist:8,ball_recovery:2,ball_loss:-1.5,shot_on_target:2}},players:[{player_id:'p1',number:13,name:'Wai Sam',display_name:'Wai Sam',team:'O16-1',play:80,playPct:100,goals:0,assists:0,rating:55,ratingReliability:'laag',actionTotal:10,possessionSeconds:100,possessionShare:10,actions:{ball_recovery:4,ball_loss:2,shot_on_target:0},relationships:{passCompletionPct:80,ballLossPerReceivedPct:20,duelWinPct:50,shotOnTargetPct:0}}],matches:[{id:'m1',match_date:'2026-08-29',team:'O16-1',opponent:'Geel Wit',score_for:0,score_against:2,duration:84,formation:'4-4-2',action_count:1000,possession_seconds:2100,possession_pct:58,include_in_dashboard:true}]}}}
function testRating(){const c=load('dashboard-ui.js');const b=c.ClubMatchV08DashboardUi.ratingBreakdown(dashboardState().dashboard.players[0],dashboardState().dashboard.ratingModel);assert.strictEqual(b.raw,5,'4 recoveries (+8) and 2 losses (-3) = 5');assert.strictEqual(b.factor,1);assert.strictEqual(b.calculated,55)}
function testCsv1000(){const c=load('match-library-ui.js');const events=Array.from({length:1000},(_,i)=>({id:`e${i}`,event_type:'player_action',match_minute:Math.floor(i/60),match_second:i%60,subject_player_id:'p1',payload:{action:'pass_completed',note:`actie ${i}`}}));const csv=c.ClubMatchV08MatchLibraryUi.buildCsv({match:{id:'m1',team_name:'Hercules',opponent_name:'Geel Wit',match_date:'2026-08-29',score_for:0,score_against:2},players:[{player_id:'p1',selected:true,is_starter:true,display_name:'Speler',shirt_number:1,starting_position:'GK'}],events},{team_name:'Hercules',opponent_name:'Geel Wit'});assert(csv.length>50000,'1000-event CSV should contain substantial data');assert(csv.includes('actie 999'),'CSV must contain latest event');assert(csv.split('\r\n').length>=1003,'CSV must contain all event rows')}
function testExcel(){const dash=load('dashboard-ui.js');const c=load('report-export.js',{ClubMatchV08DashboardUi:dash.ClubMatchV08DashboardUi});const xls=c.ClubMatchV08Reports.buildExcel(dashboardState());assert(xls.length>1000,'Excel export should not be empty');assert(xls.includes('Wai Sam'));assert(xls.includes('Geel Wit'))}
function testCleanBootstrap(){const index=fs.readFileSync(path.join(root,'index.html'),'utf8'),runtime=fs.readFileSync(path.join(root,'runtime.js'),'utf8'),analyst=fs.readFileSync(path.join(root,'analyst-live-input-v08.js'),'utf8');for(const legacy of ['roadmap-ux-v08.js','smart-registration-v08.js','v08-stabilization.js','live-analyst-polish-v08.js','tablet-matchday-hotfix-v08.js','pause-action-guard-v08.js','ux-theme.js','dashboard-player-tiles-v08.js'])assert(!index.includes(legacy),`clean index must not load ${legacy}`);assert(index.includes('browser-bootstrap-v08.js'),'clean browser bootstrap must load');assert(index.includes('report-export.js'),'report service must load');assert(index.includes('build 20260829.0700'),'release candidate build must be visible');assert(runtime.includes("get_match_live_snapshot_v08"),'runtime must use bounded live snapshot RPC');assert(analyst.includes("['live','halftime'].includes"),'Live Actieveld must remain visible at halftime');assert(analyst.includes('niet opgeslagen tijdens pauze/rust'),'paused clicks must be blocked from persistence')}
(async()=>{const tests=[['formations',testFormations],['timeline-1000-window',testTimelineWindow],['single-flight',testSingleFlight],['rating-breakdown',testRating],['csv-1000',testCsv1000],['excel',testExcel],['clean-bootstrap',testCleanBootstrap]];for(const [name,test] of tests){await test();console.log(`PASS ${name}`)}console.log(`PASS all ${tests.length} modular gates`)})().catch(error=>{console.error(error);process.exit(1)});
