'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert'),root=path.resolve(__dirname,'..'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function index(){const s=src('index.html');assert(s.includes('build 20260830.0850'));assert(s.includes('live-action-field-v09.js?v=20260830.0850'));assert(!s.includes('live-action-field-v08.js'));assert(s.includes('dashboard-layout-v09.js?v=20260830.0850'))}
function live(){const s=src('live-action-field-v09.js');for(const x of ['Pass onderschept','Duel verloren','Slechte controle','Bal veroverd','Duel gewonnen','Interceptie','Foute pass','Indeling aanpassen','Instructie manual','Historie 0 t/m −30','recommended'])assert(s.includes(x),x);assert(s.includes('record_inferred_pass_failure_v08'));assert(s.includes('analystLoseBall'));assert(s.includes('duel_won'));assert(s.includes('cmLiveHelp'))}
function prep(){const s=src('preparation-ui.js');for(const x of ['Visuele basisopstelling','draggable="true"','data-prep-pitch','placeStarter','moveToBench','render(s,{show:true})','openExisting(match)','renderCurrent()'])assert(s.includes(x),x)}
function users(){const c=src('management-controller.js'),u=src('management-ui.js');for(const x of ['remove_club_membership_v09','clubmatch-user-delete','removeMembership','deleteUser'])assert(c.includes(x),x);for(const x of ['data-member-remove','data-user-delete','Uit club','Account verwijderen'])assert(u.includes(x),x)}
function info(){const s=src('dashboard-layout-v09.js');assert(s.includes('padding-right:48px'));assert(s.includes('.cmInfoAnchor>.cmInfoBtn'));assert(s.includes('.cmiScoreCard strong'))}
function noLegacy(){const s=src('index.html');for(const x of ['roadmap-ux-v08.js','smart-registration-v08.js','v08-stabilization.js','live-analyst-polish-v08.js','tablet-matchday-hotfix-v08.js','pause-action-guard-v08.js','ux-theme.js'])assert(!s.includes(x),x)}
for(const [n,t] of Object.entries({index,live,prep,users,info,noLegacy})){t();console.log('PASS '+n)}console.log('PASS 0850 release suite');
