'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');const root=path.resolve(__dirname,'..');
function src(n){return fs.readFileSync(path.join(root,n),'utf8')}function load(n,extra={}){const c={console,setTimeout,clearTimeout,setInterval,clearInterval,Date,Math,Object,Array,Map,Set,Promise,Error,JSON,String,Number,Boolean,RegExp,TextEncoder,Uint8Array,...extra};c.globalThis=c;c.window=c;vm.createContext(c);vm.runInContext(src(n),c,{filename:n});return c}
async function formations(){const c=load('pitch-layout.js');vm.runInContext(src('formation-layout.js'),c);for(const [code,slots] of Object.entries(c.ClubMatchV08Formation.FORMATIONS)){assert.strictEqual(slots.length,11,code);assert.strictEqual(new Set(slots).size,11,code);assert.strictEqual(c.ClubMatchV08PitchLayout.geometry(code).slots.length,11,code)}}
function timeline(){const c=load('runtime.js'),events=Array.from({length:1000},(_,i)=>({id:`e${i}`})),out=c.ClubMatchV08Runtime.timelineEvents({events});assert.strictEqual(out.length,240);assert.strictEqual(out[0].id,'e760')}
async function singleFlight(){let version=1,goals=0;const c=load('mutation-controller.js'),snapshot=()=>({match:{id:'m',status:'live'},state:{state_version:version},players:[{player_id:'p',selected:true,is_on_field:true}]}),rpc=async n=>{if(n==='get_match_snapshot')return{data:snapshot()};if(n==='record_goal'){goals++;await new Promise(r=>setTimeout(r,10));version++;return{data:{ok:true}}}throw new Error(n)};const ctl=c.ClubMatchV08MutationController.createMutationController({rpc,deriveSnapshot:()=>({players:{p:{currentRole:'FIELD',currentPosition:'ST'}},fieldIds:['p']}),renderConfirmed:()=>{},idFactory:()=>Math.random().toString()});await Promise.all([ctl.recordGoal({matchId:'m',side:'for',scorerId:'p'}),ctl.recordGoal({matchId:'m',side:'for',scorerId:'p'})]);assert.strictEqual(goals,1)}
function performance(){const p={version:'cm-performance-report-v09',players:[{player_id:'p',play:90,selected_matches:2,rating:60,relationships:{possessionStarts:20,turnoverRatePct:15,retentionPct:85,possessionMetricReliability:'medium',lossCauses:{other:2}}}]},c=load('dashboard-controller.js'),n=c.ClubMatchV08Dashboard.normalizePerformance(p),r=n.players[0].relationships;assert.strictEqual(n.version,'cm-performance-report-v09');assert.strictEqual(r.possessionStarts,20);assert.strictEqual(r.turnoverRatePct,15);assert.strictEqual(r.retentionPct,85);assert.strictEqual(r.lossCauses.other,2)}
function analysis(){const c=load('performance-intelligence-v09.js',{document:{},addEventListener:()=>{},dispatchEvent:()=>{},CustomEvent:function(){}}),api=c.ClubMatchV09Performance,base={player_id:'p',play:90,selected_matches:2,rating:60,goals:0,assists:0,actions:{ball_loss:3,ball_recovery:1,interception:0},relationships:{possessionStarts:20,turnoverRatePct:15,retentionPct:85,possessionMetricReliability:'medium',lossCauses:{bad_pass:1,other:0},passCompleted:8,badPass:2,passCompletionPct:80,passReliability:'high'}};const good=api.playerAnalysis(base,60);assert(good.strengths.some(x=>x.includes('Balbehoud')));const unknown={...base,relationships:{...base.relationships,retentionPct:65,turnoverRatePct:35,lossCauses:{bad_pass:0,other:5}}},bad=api.playerAnalysis(unknown,60);assert(bad.focus.some(x=>x.includes('oorzaak')));assert(!bad.focus.some(x=>x.includes('eerste actie na ontvangst')))}
function sources(){const idx=src('index.html'),controller=src('dashboard-controller.js'),synergy=src('team-synergy-ui-v09.js'),player=src('player-infographic-v09.js'),pdf=src('dashboard-pdf-v09.js'),xls=src('report-export-v09.js'),live=src('live-action-field-v08.js');assert(idx.includes('build 20260830.0840'));for(const f of ['performance-intelligence-v09.js','team-synergy-ui-v09.js','player-infographic-v09.js','dashboard-pdf-v09.js','report-export-v09.js','kpi-info-v08.js'])assert(idx.includes(f),f);for(const old of ['performance-intelligence-v08.js','team-synergy-ui-v08.js','player-infographic-v08.js'])assert(!idx.includes(old),old);assert(controller.includes('get_performance_report_v09'));for(const t of ['get_team_synergy_dashboard_v09','from_node_id','from_position','to_position'])assert(synergy.includes(t),t);for(const t of ['retentionPct','turnoverRatePct','lossCauses','downloadAllPdf'])assert(player.includes(t),t);for(const t of ['Dashboard PDF','pageExecutive','pageNetwork','pdfFromJpegs'])assert(pdf.includes(t),t);for(const t of ['Bezitmomenten','Turnover %','Balbehoud %','Verlies overig'])assert(xls.includes(t),t);assert(!xls.includes('ballLossPerReceivedPct'));for(const t of ['historie blijft zichtbaar: 0 t/m −30','record_inferred_pass_failure_v08','likelyProgression','likelySwitch'])assert(live.includes(t),t)}
function csv1000(){const c=load('match-library-ui.js'),events=Array.from({length:1000},(_,i)=>({id:`e${i}`,event_type:'player_action',match_minute:Math.floor(i/60),match_second:i%60,subject_player_id:'p',payload:{action:'pass_completed',note:`actie ${i}`}})),csv=c.ClubMatchV08MatchLibraryUi.buildCsv({match:{id:'m',team_name:'Club',opponent_name:'Opp'},players:[{player_id:'p',selected:true,display_name:'Speler'}],events},{});assert(csv.length>50000);assert(csv.includes('actie 999'))}
function pdfCore(){const dash=load('dashboard-ui.js'),c=load('report-export.js',{ClubMatchV08DashboardUi:dash.ClubMatchV08DashboardUi}),bytes=c.ClubMatchV08Reports.pdfFromJpegs([new Uint8Array([255,216,255,217])]),txt=Buffer.from(bytes).toString('latin1');assert(txt.startsWith('%PDF-1.4'));assert(txt.endsWith('%%EOF'))}
(async()=>{for(const [n,t] of Object.entries({formations,timeline,singleFlight,performance,analysis,sources,csv1000,pdfCore})){await t();console.log('PASS '+n)}console.log('PASS 0840 release suite')})().catch(e=>{console.error(e);process.exit(1)});
