'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const src=n=>fs.readFileSync(path.join(root,n),'utf8');
function load(name,extra={}){const c={console,setTimeout,clearTimeout,setInterval,clearInterval,Date,Math,Object,Array,Map,Set,Promise,Error,JSON,String,Number,Boolean,RegExp,TextEncoder,Uint8Array,Buffer,...extra};c.globalThis=c;c.window=c;vm.createContext(c);vm.runInContext(src(name),c,{filename:name});return c}
function releaseWiring(){const s=src('index.html');for(const token of ['build 20260831.1700','performance-intelligence-v10.js?v=20260831.1700','dashboard-pdf-v10.js?v=20260831.1700','kpi-info-v10.js?v=20260831.1700','match-intelligence-v11.js?v=20260831.1700','action-context-persistence-v08.js?v=20260831.1700'])assert(s.includes(token),token);for(const old of ['performance-intelligence-v09.js?v=','dashboard-pdf-v09.js?v=','kpi-info-v08.js?v='])assert(!s.includes(old),old)}
async function contextPersistence(){const calls=[],store=new Map(),storage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},client={rpc:async(name,params)=>{calls.push({name,params});if(calls.length===1)return {error:new Error('tijdelijk offline')};return {data:{ok:true,stored:true}}}};const c=load('action-context-persistence-v08.js'),api=c.ClubMatchV08ActionContextPersistence.createPersistence({client,storage}),item={matchId:'m1',clientEventId:'ce1',context:{pressure:'heavy_pressure',passing_options:'none',action_context:{phase:'transition',result:'poor_control'}}};const first=await api.persist(item);assert.strictEqual(first,null);assert.strictEqual(api.pendingCount,1);await api.flush();assert.strictEqual(api.pendingCount,0);assert.strictEqual(calls[0].name,'upsert_match_event_context_v09');assert.strictEqual(calls[1].name,'upsert_match_event_context_v09');assert.strictEqual(calls[1].params.p_context.action_context.result,'poor_control')}
function contextIntegration(){const p=src('action-context-persistence-v08.js'),laf=src('live-action-field-v13.js'),ui=src('action-context-ui-v08.js'),desc=src('live-input-event-describer-v08.js');assert(p.includes('upsert_match_event_context_v09'));assert(!p.includes('enrich_match_event_context_v08'));for(const token of ['persistence().after(primaryPromise','updatePendingContext','poor_control','contextPayload'])assert(laf.includes(token),token);for(const token of ['context kan alvast','Meerdere contextcategorieën tegelijk mogelijk','height:480px!important','body.insertBefore(fieldRow,actions)'])assert(ui.includes(token),token);for(const token of ['Context:','poor_control:\'slechte controle\''])assert(desc.includes(token),token)}
function playerTilesAndSwapColors(){const s=src('dom-renderer.js');for(const token of ['v08PlayerHead','v08Metrics','v08Metric','swapNever080','swapPast080','swapIn080','swapOut080','#1976d2','#d39118','#6f42c1','changeLabel(player.changeState)'])assert(s.includes(token),token);assert(s.includes('.v08PitchPlayer.swapIn080'));assert(s.includes('.v08PitchBenchPlayer.swapOut080'));assert(s.includes('.v08MonitorRow.swapPast080'))}
function intelligenceVisible(){const s=src('match-intelligence-v11.js'),p=src('performance-intelligence-v10.js');for(const token of ['Eerste helft','Tweede helft','Balbezit over de minuten','Impact van wissels en formatie','Player of the Match (POTM)','Box score / speelstatistieken','Voorstel volgende opstelling','Actie-afstand is geen echte loopafstand'])assert(s.includes(token),token);assert(p.includes('ClubMatchV11MatchIntelligence?.render?.(state)'))}
function performanceMath(){const fakeDoc={},c=load('performance-intelligence-v10.js',{document:fakeDoc}),api=c.ClubMatchV10Performance,p={pass_quality:{confidence_weight:1},components:{passing:80,possession:58,duels:60,ball_control:60,attack:72,defense:76,discipline:57,result:100}};const teamplay=api.actualWeighted(api.componentParts(p).teamplay),performance=api.actualWeighted(api.componentParts(p).performance);assert(Math.abs(teamplay.result-67.6)<0.001);assert(Math.abs(performance.result-71.77)<0.01);assert.notStrictEqual(Math.round(teamplay.result*10),Math.round(performance.result*10));const k=src('kpi-info-v10.js');for(const token of ['met huidige cijfers','Team-balbezit','Persoonlijke bezitmomenten','Balbehoud','weightedRows','actual(key)'])assert(k.includes(token),token)}
function fixture(){const player={player_id:'p1',number:13,display_name:'Testspeler',name:'Testspeler',play:80,bench:10,rating:76,ratingReliability:'middel',goals:1,assists:1,actions:{ball_loss:2,ball_recovery:4,interception:2,duel_won:3,duel_lost:1,shot:4,shot_on_target:2,corner:1,free_kick:1,throw_in:2},relationships:{passCompleted:16,badPass:4,passCompletionPct:80,passReliability:'high',retentionPct:85,possessionStarts:14,duelWinPct:75}};return {teamPossession:{first_half:{for_pct:54,against_pct:46},second_half:{for_pct:62,against_pct:38}},teamPerformance:{team_name:'Hercules O16-1',matches:1,wins:1,draws:0,losses:0,goals_for:2,goals_against:1,result_pct:100,team_performance_pct:71.8,teamplay_pct:67.6,data_coverage_pct:100,scope:{type:'match',opponent:'Test FC',match_date:'2026-08-31',score_for:2,score_against:1},pass_quality:{confidence_weight:1,reliability:'high'},components:{passing:80,possession:58,duels:60,ball_control:60,attack:72,defense:76,discipline:57,result:100},passes:{completed:80,failed:20,accuracy_pct:80,reliability:'high'},possession:{for_seconds:2160,against_seconds:1560,pct:58.1},duels:{won:6,lost:4,win_pct:60},shooting:{shots:8,on_target:4,on_target_pct:50,goals:2,goal_conversion_pct:25,chances_created:5,chances_per_match:5},defending:{recoveries:12,losses:8,recovery_control_pct:60,interceptions:7,blocks:3,saves:2,goals_against_per_match:1},discipline:{fouls_won:4,fouls_committed:3},players:[player]}}}
function pdfIsRealDesigned(){const fakeDoc={querySelector:()=>null,getElementById:()=>null},c=load('dashboard-pdf-v10.js',{document:fakeDoc}),api=c.ClubMatchV10DashboardPdf,bytes=api.buildPdfBytes(fixture()),txt=Buffer.from(bytes).toString('latin1');assert(txt.startsWith('%PDF-1.4'));assert(txt.endsWith('%%EOF'));assert(bytes.length>5000);for(const token of ['Team Performance - echte berekening','Samenspel - echte berekening','Hoe de KPI','Onderliggende berekeningen','Passing','Team-balbezit','Spelersanalyse & box score','Box score / speelstatistieken'])assert(txt.includes(token),token);const s=src('dashboard-pdf-v10.js');assert(!s.includes('window.print'));assert(s.includes("b.textContent='Dashboard PDF · zoals website'"));assert(s.includes('rawCalculationPage'));assert(s.includes("['Cor',23]"));assert(s.includes("['VT',20]"));assert(s.includes("['Ing',23]"))}
function classList(initial=[]){const set=new Set(initial);return {add:(...x)=>x.forEach(v=>set.add(v)),remove:(...x)=>x.forEach(v=>set.delete(v)),contains:x=>set.has(x),toggle:(x,force)=>{if(force===undefined){if(set.has(x))set.delete(x);else set.add(x)}else if(force)set.add(x);else set.delete(x)},values:()=>[...set]}}
function panel(name,hidden=false,persistent=false){return {name,classList:classList(hidden?['hidden']:[]),hasAttribute:k=>persistent&&k==='data-workspace-persistent'}}
function workspaceBack(){const hub=panel('hub',false,true),matches=panel('matches'),dashboard=panel('dashboard',true),history=panel('history',true),app={children:[hub,matches,dashboard,history],dataset:{}},doc={getElementById:()=>app},c=load('workspace-manager.js',{document:doc}),w=c.ClubMatchV08Workspace.createWorkspaceManager({document:doc,app});dashboard.classList.remove('hidden');w.enter('dashboard',dashboard);assert(matches.classList.contains('hidden'));history.classList.remove('hidden');w.enter('history',history);assert(matches.classList.contains('hidden'));w.backToMatches();assert(!matches.classList.contains('hidden'));assert(dashboard.classList.contains('hidden'));assert(history.classList.contains('hidden'));assert.strictEqual(w.active,'matches');const s=src('workspace-manager.js');assert(s.includes('saved.set(panel,true)'));assert(!s.includes('if(saved)exit(true)'))}
function scalableArchitecture(){const runtime=src('runtime.js'),index=src('index.html');assert(runtime.includes('LIVE_EVENT_WINDOW=240'));assert(runtime.includes('get_match_live_snapshot_v08'));for(const legacy of ['roadmap-ux-v08.js','smart-registration-v08.js','v08-stabilization.js','live-analyst-polish-v08.js','tablet-matchday-hotfix-v08.js','pause-action-guard-v08.js','ux-theme.js','dashboard-player-tiles-v08.js'])assert(!index.includes(legacy),legacy)}
(async()=>{const tests={releaseWiring,contextPersistence,contextIntegration,playerTilesAndSwapColors,intelligenceVisible,performanceMath,pdfIsRealDesigned,workspaceBack,scalableArchitecture};for(const [name,test] of Object.entries(tests)){await test();console.log('PASS '+name)}console.log(`PASS all ${Object.keys(tests).length} build 1700 gates`)})().catch(e=>{console.error(e);process.exit(1)});
