/* ClubMatch Cloud v0.8 - branch-only browser application wiring */
(function(global){
'use strict';
const SUPABASE_URL='https://fnbqyogbamufytcabfzm.supabase.co';
const SUPABASE_KEY='sb_publishable_skGPpngOQ_1OpEbreV2kXA__2OL_Mbp';
const RESET_REDIRECT='https://maartenchung.github.io/ClubMatch-Cloud/cloud-v0.8-rebuild/';
const byId=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let client=null,runtime=null,renderer=null,lifecycleSync=null,matchSelection=null,preparation=null,preparationUi=null,correctionUi=null,voiceController=null,voiceUi=null,playerActions=null,playerActionUi=null,liveControlsUi=null,basisLineupUi=null,livePitchController=null,matchPhase=null,matchPhaseUi=null,dashboard=null,dashboardUi=null,security=null,securityUi=null,lastFrame=null,busy=false;
function status(message,ok=false){const el=byId('v08Status');if(!el)return;el.textContent=message;el.classList.toggle('ok',ok);el.classList.toggle('bad',!ok&&!!message)}
function setBusy(value){busy=!!value;document.querySelectorAll('[data-v08-action]').forEach(btn=>{btn.disabled=busy||btn.dataset.v08Allowed==='0'})}
function setAllowed(selector,allowed){const el=document.querySelector(selector);if(!el)return;el.dataset.v08Allowed=allowed?'1':'0';el.disabled=busy||!allowed}
async function run(label,fn){if(busy)return;setBusy(true);status(`${label}…`);try{const result=await fn();status(`${label} ✓`,true);return result}catch(error){console.error(error);status(`${label} mislukt: ${error.message||error}`);return undefined}finally{setBusy(false)}}
function optionHtml(player){const position=player.position?(global.ClubMatchV08PitchLayout?.slotLabel?.(player.position)||player.position):'';return `<option value="${esc(player.id)}">#${esc(player.shirtNumber??'—')} ${esc(player.name)}${position?' · '+esc(position):''}</option>`}
function fillSelect(id,players,allowEmpty=false){const el=byId(id);if(!el)return;const old=el.value;el.innerHTML=(allowEmpty?'<option value="">—</option>':'')+players.map(optionHtml).join('');if([...el.options].some(o=>o.value===old))el.value=old}
function textMatch(match){byId('activeMatchTitle').textContent=match.id?`${match.team_name||'Team'} — ${match.opponent_name||'Tegenstander'}`:'Geen wedstrijd geselecteerd';byId('activeMatchMeta').textContent=match.id?`${match.club_name||''}${match.season_name?' · '+match.season_name:''}${match.status?' · '+match.status:''}${match.formation_code?' · '+match.formation_code:''}`:''}
function applyActionPolicy(frame={field:[],bench:[]}){const snapshot=runtime?.snapshot||{},policy=global.ClubMatchV08ActionPolicy.createActionPolicy({match:snapshot.match,state:snapshot.state,frame});setAllowed('#subBtn',policy.substitute);setAllowed('#posBtn',policy.changePosition);setAllowed('#swapBtn',policy.swapPositions);setAllowed('#goalForBtn',policy.goalFor);setAllowed('#goalAgainstBtn',policy.goalAgainst);setAllowed('[data-clock="pause"]',policy.pause);setAllowed('[data-clock="resume"]',policy.resume);setAllowed('[data-clock="halftime"]',policy.halftime);setAllowed('[data-clock="second_half"]',policy.secondHalf);setAllowed('[data-clock="injury_time"]',policy.injuryTime);setAllowed('[data-clock="finish"]',policy.finish);setAllowed('#deleteMatchBtn',policy.deleteMatch);byId('deleteMatchBtn')?.classList.toggle('hidden',!policy.deleteMatch);return policy}
function resetLiveUi(){lastFrame=null;playerActionUi?.close?.();voiceUi?.clear?.();renderer?.clear?.();correctionUi?.clear?.();basisLineupUi?.clear?.();matchPhaseUi?.clear?.();textMatch({});if(global.ClubMatchV08ActionPolicy?.createActionPolicy)applyActionPolicy({field:[],bench:[]})}
function stopUserWork(){runtime?.stop?.();preparationUi?.hide?.();dashboardUi?.hide?.();resetLiveUi()}
function updateActionControls(frame){lastFrame=frame;fillSelect('subOut',frame.field);fillSelect('subIn',frame.bench);fillSelect('posPlayer',frame.field);fillSelect('swapA',frame.field);fillSelect('swapB',frame.field);fillSelect('goalScorer',frame.field,true);fillSelect('goalAssist',frame.field,true);textMatch(runtime?.snapshot?.match||{});applyActionPolicy(frame);livePitchController?.syncControls?.()}
function renderModel(model,meta={}){const frame=global.ClubMatchV08UiFrame.createUiFrame(model);renderer.render(frame);updateActionControls(frame);const snapshot=meta.snapshot||runtime?.snapshot;correctionUi?.render?.(snapshot);if(meta.confirmed!==false){playerActions?.setSnapshot?.(snapshot);voiceUi?.setSnapshot?.(snapshot);basisLineupUi?.render?.(snapshot);matchPhaseUi?.render?.(snapshot)}return frame}
function markActiveMatch(matchId){document.querySelectorAll('.matchChoice').forEach(x=>x.classList.toggle('active',x.dataset.matchId===matchId))}
function setSessionIdentity(session){byId('sessionEmail').textContent=session?.user?.email||session?.user?.id||''}
async function openLiveMatch(match,{remember=true}={}){preparationUi?.hide();dashboardUi?.hide();await matchPhase?.enforceDeadline?.(match.match_id);await runtime.start(match.match_id);if(remember)matchSelection?.remember(match.match_id);markActiveMatch(match.match_id);return runtime.viewModel}
async function openPreparation(match,{remember=true}={}){dashboardUi?.hide();runtime.stop();resetLiveUi();if(remember)matchSelection?.remember(match.match_id);await preparationUi.openExisting(match);markActiveMatch(match.match_id);return preparation.state}
async function openMatchSummary(match,options={}){if(['draft','scheduled'].includes(match.status))return openPreparation(match,options);return openLiveMatch(match,options)}
async function refreshOpenMatches({restore=false}={}){const box=byId('openMatches');box.innerHTML='<div class="muted">Cloud-wedstrijden laden…</div>';const {data,error}=await client.rpc('get_my_open_matches');if(error)throw error;const matches=Array.isArray(data)?data:[];if(!matches.length){box.innerHTML='<div class="muted">Geen open wedstrijden.</div>';if(runtime?.activeMatchId){runtime.stop();resetLiveUi()}return matches}box.innerHTML='';matches.forEach(match=>{const card=document.createElement('button');card.type='button';card.className='matchChoice';card.dataset.matchId=match.match_id;const statusNl=({live:'live',halftime:'rust',draft:'concept',scheduled:'gepland',finished:'afgelopen'}[match.status]||match.status);card.innerHTML=`<b>${esc(match.team_name)} — ${esc(match.opponent_name)}</b><span>${esc(match.club_name||'')} · ${esc(match.match_date||'')} · ${esc(match.scheduled_time||'')} · ${esc(statusNl)} · status v${esc(match.state_version??'—')}</span>`;card.onclick=()=>run(match.status==='draft'||match.status==='scheduled'?'Voorbereiding openen':'Wedstrijd openen',()=>openMatchSummary(match));box.appendChild(card)});if(runtime?.activeMatchId&&matches.some(match=>match.match_id===runtime.activeMatchId))markActiveMatch(runtime.activeMatchId);else if(preparation?.state?.meta?.matchId&&preparationUi?.visible&&matches.some(match=>match.match_id===preparation.state.meta.matchId))markActiveMatch(preparation.state.meta.matchId);else if(restore){const chosen=matchSelection?.choose(matches),match=matches.find(item=>item.match_id===chosen);if(match)await openMatchSummary(match,{remember:false})}return matches}
function ensureHeaderButtons(){const refresh=byId('refreshMatchesBtn'),parent=refresh?.parentElement;if(!parent)return;if(!byId('newPreparationBtn')){const button=document.createElement('button');button.id='newPreparationBtn';button.className='secondary';button.dataset.v08Action='';button.textContent='+ Nieuwe wedstrijd';button.onclick=()=>run('Nieuwe voorbereiding',async()=>{dashboardUi?.hide();runtime.stop();resetLiveUi();matchSelection?.clear();preparation.clear();await preparation.loadTeamSeasons();preparationUi.renderCurrent();return preparation.state});parent.insertBefore(button,refresh)}if(!byId('dashboardBtn')){const button=document.createElement('button');button.id='dashboardBtn';button.className='secondary';button.dataset.v08Action='';button.textContent='Dashboard';button.onclick=()=>run('Dashboard laden',async()=>{preparationUi?.hide();await dashboard.loadTeams();await dashboard.load(null);dashboardUi.show();return dashboard.state});parent.insertBefore(button,refresh)}}
async function loadSignedInContext({restore=true}={}){await preparation.loadTeamSeasons();return refreshOpenMatches({restore})}
async function enterAuthenticatedApp({restore=true}={}){const result=await security.refreshMfa();securityUi.render(result);const session=(await client.auth.getSession()).data.session;setSessionIdentity(session);if(result.mfa.needsChallenge){stopUserWork();securityUi.showChallenge(true);securityUi.setChallengeStatus('Tweestapsverificatie is vereist voor deze sessie.');return false}securityUi.showApp();await loadSignedInContext({restore});return true}
function enterSignedOut(){stopUserWork();setSessionIdentity(null);securityUi?.showLoggedOut?.();if(byId('openMatches'))byId('openMatches').innerHTML=''}
async function bootstrapSession(){const recovery=security.importRecovery(global.location);if(recovery?.data?.recovery){stopUserWork();securityUi.showRecovery(true);securityUi.setRecoveryStatus('Resetlink gecontroleerd. Kies nu een nieuw wachtwoord.');return}const {data,error}=await client.auth.getSession();if(error)throw error;if(!data.session){enterSignedOut();return}await enterAuthenticatedApp({restore:true})}
function bindActions(){
  ensureHeaderButtons();byId('loginBtn').onclick=()=>run('Inloggen',async()=>{const email=byId('email').value.trim(),password=byId('password').value;const {data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;setSessionIdentity(data.session);await enterAuthenticatedApp({restore:true})});byId('logoutBtn').onclick=()=>run('Uitloggen',async()=>{stopUserWork();const {error}=await client.auth.signOut();if(error)throw error;enterSignedOut()});byId('refreshMatchesBtn').onclick=()=>run('Wedstrijden verversen',()=>refreshOpenMatches({restore:!runtime.activeMatchId&&!preparationUi.visible}));byId('refreshLiveBtn').onclick=()=>run('Live-status verversen',async()=>{await matchPhase?.enforceDeadline?.();return runtime.refresh('handmatig')});
  byId('subBtn').onclick=()=>run('Wissel vastleggen',()=>runtime.substitute({outId:byId('subOut').value,inId:byId('subIn').value}));byId('posBtn').onclick=()=>run('Positie wijzigen',()=>runtime.changePosition({playerId:byId('posPlayer').value,position:byId('posNew').value.trim()}));byId('swapBtn').onclick=()=>run('Posities ruilen',()=>runtime.swapPositions({playerId:byId('swapA').value,otherPlayerId:byId('swapB').value}));byId('goalForBtn').onclick=()=>run('Doelpunt eigen team',()=>runtime.recordGoal({side:'for',scorerId:byId('goalScorer').value,assistId:byId('goalAssist').value||null,goalType:byId('goalType')?.value||null,note:byId('goalNote')?.value.trim()||null}));byId('goalAgainstBtn').onclick=()=>run('Doelpunt tegenstander',()=>runtime.recordGoal({side:'against',goalType:byId('goalType')?.value||null,note:byId('goalNote')?.value.trim()||null}));
  document.querySelectorAll('[data-clock]').forEach(btn=>btn.onclick=()=>run('Wedstrijdklok bijwerken',async()=>{if(btn.dataset.clock==='finish'){const result=await matchPhase.finish();await refreshOpenMatches();return result}const input={clockAction:btn.dataset.clock};if(input.clockAction==='injury_time')input.minutes=Number(byId('injuryMinutes').value);const result=await runtime.advanceClock(input);await refreshOpenMatches();return result}));
  byId('deleteMatchBtn').onclick=()=>run('Wedstrijd verwijderen',async()=>{if(!runtime.activeMatchId)throw new Error('Geen wedstrijd geselecteerd');if(!confirm('Deze wedstrijd en alle gekoppelde gebeurtenissen/spelerdata definitief verwijderen?'))throw new Error('Verwijderen geannuleerd');const confirmation=prompt('Typ DELETE om definitief te verwijderen:','');if(confirmation!=='DELETE')throw new Error('Bevestiging is niet DELETE');const result=await runtime.deleteMatch({confirmation});matchSelection?.clear();await refreshOpenMatches({restore:true});return result});
}
function ensureModule(path,isReady,label){if(isReady())return Promise.resolve();return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=path;script.onload=()=>isReady()?resolve():reject(new Error(`${label} geladen zonder API`));script.onerror=()=>reject(new Error(`${label} kon niet worden geladen`));document.head.appendChild(script)})}
async function init(){
  try{
    if(!global.ClubMatchV08CloudClient?.createClient)throw new Error('ClubMatch Cloud-client kon niet worden geladen');
    await ensureModule('pitch-layout.js',()=>!!global.ClubMatchV08PitchLayout?.geometry,'veldmodel');await ensureModule('event-describer.js',()=>!!global.ClubMatchV08EventDescriber?.describeEvent,'gebeurtenisvertaling');await ensureModule('action-policy.js',()=>!!global.ClubMatchV08ActionPolicy?.createActionPolicy,'actiebeleid');await ensureModule('lifecycle-sync.js',()=>!!global.ClubMatchV08LifecycleSync?.createLifecycleSync,'herstelsynchronisatie');await ensureModule('match-selection.js',()=>!!global.ClubMatchV08MatchSelection?.createMatchSelection,'wedstrijdselectie');
    await ensureModule('preparation-controller.js',()=>!!global.ClubMatchV08Preparation?.createPreparationController,'wedstrijdvoorbereiding');await ensureModule('preparation-ui.js',()=>!!global.ClubMatchV08PreparationUi?.createPreparationUi,'voorbereidingsscherm');await ensureModule('correction-ui.js',()=>!!global.ClubMatchV08Corrections?.createCorrectionUi,'correctiescherm');await ensureModule('basis-lineup-ui.js',()=>!!global.ClubMatchV08BasisLineup?.createBasisLineupUi,'basisopstelling');await ensureModule('live-pitch-controller.js',()=>!!global.ClubMatchV08LivePitch?.createLivePitchController,'live veldbediening');await ensureModule('match-phase-controller.js',()=>!!global.ClubMatchV08MatchPhase?.createMatchPhaseController,'wedstrijdphase');await ensureModule('match-phase-ui.js',()=>!!global.ClubMatchV08MatchPhaseUi?.createMatchPhaseUi,'wedstrijdfasescherm');await ensureModule('live-controls-ui.js',()=>!!global.ClubMatchV08LiveControls?.createLiveControlsUi,'live wedstrijdbediening');
    await ensureModule('player-action-controller.js',()=>!!global.ClubMatchV08PlayerActions?.createPlayerActionController,'speleracties');await ensureModule('player-action-ui.js',()=>!!global.ClubMatchV08PlayerActionUi?.createPlayerActionUi,'speleractiescherm');await ensureModule('voice-command.js',()=>!!global.ClubMatchV08VoiceCommand?.parseCommand,'spraakparser');await ensureModule('voice-controller.js',()=>!!global.ClubMatchV08VoiceController?.createVoiceController,'spraakcontroller');await ensureModule('voice-ui.js',()=>!!global.ClubMatchV08VoiceUi?.createVoiceUi,'spraakscherm');
    await ensureModule('dashboard-controller.js',()=>!!global.ClubMatchV08Dashboard?.createDashboardController,'dashboard');await ensureModule('dashboard-ui.js',()=>!!global.ClubMatchV08DashboardUi?.createDashboardUi,'dashboardscherm');await ensureModule('security-controller.js',()=>!!global.ClubMatchV08Security?.createSecurityController,'beveiliging');await ensureModule('security-ui.js',()=>!!global.ClubMatchV08SecurityUi?.createSecurityUi,'beveiligingsscherm');
    client=global.ClubMatchV08CloudClient.createClient(SUPABASE_URL,SUPABASE_KEY);renderer=global.ClubMatchV08DomRenderer.createRenderer(document);runtime=global.ClubMatchV08Runtime.createRuntime({supabase:client,render:renderModel,onDeleted:resetLiveUi,onError:error=>status(`Cloud-synchronisatie: ${error.message||error}`)});
    correctionUi=global.ClubMatchV08Corrections.createCorrectionUi({document,runtime,run});matchPhase=global.ClubMatchV08MatchPhase.createMatchPhaseController({client,runtime});matchPhaseUi=global.ClubMatchV08MatchPhaseUi.createMatchPhaseUi({document,controller:matchPhase,run});livePitchController=global.ClubMatchV08LivePitch.createLivePitchController({document,runtime,run});livePitchController.install();basisLineupUi=global.ClubMatchV08BasisLineup.createBasisLineupUi({document,onMove:(playerId,position)=>run('Basispositie wijzigen',()=>livePitchController.movePlayer(playerId,position))});
    playerActions=global.ClubMatchV08PlayerActions.createPlayerActionController({client,runtime});playerActionUi=global.ClubMatchV08PlayerActionUi.createPlayerActionUi({document,controller:playerActions,run});playerActionUi.install();voiceController=global.ClubMatchV08VoiceController.createVoiceController({runtime,playerActions,parseCommand:global.ClubMatchV08VoiceCommand.parseCommand});voiceUi=global.ClubMatchV08VoiceUi.createVoiceUi({document,controller:voiceController,run});voiceUi.render();liveControlsUi=global.ClubMatchV08LiveControls.createLiveControlsUi({document});liveControlsUi.install();matchSelection=global.ClubMatchV08MatchSelection.createMatchSelection();
    preparation=global.ClubMatchV08Preparation.createPreparationController({client,onChange:state=>{if(preparationUi?.visible)preparationUi.render(state)}});preparationUi=global.ClubMatchV08PreparationUi.createPreparationUi({document,controller:preparation,run,onSaved:async snapshot=>{matchSelection.remember(snapshot.match.id);await refreshOpenMatches({restore:false});markActiveMatch(snapshot.match.id)},onStarted:async matchId=>{matchSelection.remember(matchId);preparationUi.hide();await refreshOpenMatches({restore:false});const response=await client.rpc('get_my_open_matches');if(response.error)throw response.error;const match=(response.data||[]).find(item=>item.match_id===matchId);if(!match)throw new Error('Gestarte wedstrijd niet teruggevonden');await openLiveMatch(match,{remember:false})}});
    dashboard=global.ClubMatchV08Dashboard.createDashboardController({client,onChange:state=>{if(dashboardUi?.visible)dashboardUi.render(state)}});dashboardUi=global.ClubMatchV08DashboardUi.createDashboardUi({document,controller:dashboard,run});security=global.ClubMatchV08Security.createSecurityController({client,onChange:state=>securityUi?.render?.(state)});
    securityUi=global.ClubMatchV08SecurityUi.createSecurityUi({document,onRequestReset:email=>run('Resetmail aanvragen',async()=>{const result=await security.requestPasswordReset(email,RESET_REDIRECT);securityUi.setResetNote(result.message);return result}),onUpdatePassword:(password,confirmation)=>run('Nieuw wachtwoord opslaan',async()=>{await security.updateRecoveredPassword(password,confirmation);byId('newPassword').value='';byId('newPasswordConfirm').value='';securityUi.showLoggedOut();securityUi.setResetNote('Wachtwoord gewijzigd. Log opnieuw in met je nieuwe wachtwoord.');return true}),onVerifyLoginMfa:code=>run('2FA verifiëren',async()=>{const state=await security.verifyLoginMfa(code);securityUi.render(state);byId('loginMfaCode').value='';securityUi.showApp();await loadSignedInContext({restore:true});return state}),onLogout:()=>run('Uitloggen',async()=>{const {error}=await client.auth.signOut();if(error)throw error;enterSignedOut()}),onBeginEnrollment:()=>run('Authenticator toevoegen',async()=>{const state=await security.beginTotpEnrollment();securityUi.render(state);return state}),onRefreshSecurity:()=>run('Beveiliging verversen',async()=>{const state=await security.refreshMfa();securityUi.render(state);return state}),onVerifyEnrollment:code=>run('2FA activeren',async()=>{const state=await security.verifyTotpEnrollment(code);securityUi.render(state);byId('mfaEnrollCode').value='';return state}),onCancelEnrollment:()=>{security.cancelEnrollment();securityUi.render(security.state)},onUnenroll:factorId=>{if(confirm('Deze 2FA-factor verwijderen? Zorg dat je een andere factor beschikbaar hebt.'))run('2FA-factor verwijderen',async()=>{const state=await security.unenroll(factorId);securityUi.render(state);return state})}});
    lifecycleSync=global.ClubMatchV08LifecycleSync.createLifecycleSync({runtime,window:global,document});lifecycleSync.install();bindActions();applyActionPolicy({field:[],bench:[]});client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT')enterSignedOut();else if(event==='PASSWORD_RECOVERY'){stopUserWork();securityUi.showRecovery(true)}else if(session)setSessionIdentity(session)});await bootstrapSession();status('ClubMatch Cloud v0.8 gereed.',true);
  }catch(error){console.error(error);status(`Start mislukt: ${error.message||error}`)}
}
document.addEventListener('DOMContentLoaded',init);
})(window);
