import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const scripts=[...html.matchAll(/<script\s+src="([^"]+)"/g)].map(m=>m[1]);
const marker=html.match(/build\s+(\d{8}\.\d{4})/i);assert.ok(marker,'visible build marker missing');const build=marker[1];
assert.ok(scripts.length>=32,'expected complete v0.8 browser module set including live UX, phases, actions, corrections and voice');
assert.ok(scripts.every(src=>src.endsWith(`?v=${build}`)),`browserbestand zonder actuele versie ${build}: ${scripts.filter(src=>!src.endsWith(`?v=${build}`)).join(', ')}`);
for(const expected of ['cloud-client.js','pitch-layout.js','event-describer.js','live-state.js','snapshot-adapter.js','view-model.js','mutation-controller.js','clock-projector.js','runtime.js','ui-frame.js','dom-renderer.js','action-policy.js','lifecycle-sync.js','match-selection.js','formation-layout.js','preparation-controller.js','preparation-ui.js','correction-ui.js','basis-lineup-ui.js','live-pitch-controller.js','match-phase-controller.js','match-phase-ui.js','live-controls-ui.js','player-action-controller.js','player-action-ui.js','voice-command.js','voice-controller.js','voice-ui.js','dashboard-controller.js','dashboard-ui.js','security-controller.js','security-ui.js','ux-theme.js','app.js'])assert.ok(scripts.some(src=>src===`${expected}?v=${build}`),`ontbrekend versie-gepind browserbestand: ${expected}`);
assert.ok(!scripts.some(src=>src.startsWith('correction-bootstrap.js')),'verouderde correctie-bootstrap mag niet meer geladen worden');
assert.equal(new Set(scripts.map(src=>src.split('?v=')[1])).size,1,'niet alle browserbestanden gebruiken hetzelfde buildnummer');
assert.ok(html.includes('<h2>Live monitoring</h2>'),'Wisselmonitor moet vervangen zijn door Live monitoring');
console.log(`PASS asset-versioning: ${scripts.length} browserbestanden zijn versie-gepind op build ${build}`);
