import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const context={console,globalThis:null,window:null,Date};context.globalThis=context;context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(new URL('./clock-projector.js',import.meta.url),'utf8'),context);
const C=context.ClubMatchV08ClockProjector;
const running={match:{status:'live'},state:{state_version:7,clock_status:'running',effective_elapsed_seconds:600}};
const anchor=C.createAnchor(running,100000);
assert.equal(C.projectedSecond(anchor,100000),600);
assert.equal(C.projectedSecond(anchor,101999),601);
assert.equal(C.projectedSecond(anchor,105000),605);
const projected=C.projectSnapshot(running,anchor,105000);
assert.equal(projected.state.effective_elapsed_seconds,605);
assert.equal(running.state.effective_elapsed_seconds,600,'confirmed snapshot must remain immutable');
const paused={match:{status:'live'},state:{state_version:8,clock_status:'paused',effective_elapsed_seconds:605}};
const pausedAnchor=C.createAnchor(paused,200000);
assert.equal(C.projectedSecond(pausedAnchor,260000),605,'paused clock must not advance');
const halftime={match:{status:'halftime'},state:{state_version:9,clock_status:'stopped',effective_elapsed_seconds:2400}};
assert.equal(C.projectedSecond(C.createAnchor(halftime,0),600000),2400,'halftime must stay fixed');
console.log('PASS clock-projector: running + paused + halftime');
