import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const context={console,globalThis:null,window:null,Date};context.globalThis=context;context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(new URL('./clock-projector.js',import.meta.url),'utf8'),context);
const C=context.ClubMatchV08ClockProjector;
const running={match:{status:'live'},state:{state_version:7,period:'first_half',clock_status:'running',effective_elapsed_seconds:600}};
const anchor=C.createAnchor(running,100000);assert.equal(C.projectedSecond(anchor,105000),605);assert.equal(C.projectedPauseSecond(anchor,105000),0);
const projected=C.projectSnapshot(running,anchor,105000);assert.equal(projected.state.effective_elapsed_seconds,605);assert.equal(running.state.effective_elapsed_seconds,600,'confirmed snapshot must remain immutable');
const paused={server_now:'2026-08-26T11:01:30.000Z',match:{status:'live'},state:{state_version:8,period:'first_half',clock_status:'paused',effective_elapsed_seconds:605},events:[{id:'p1',event_type:'match_paused',occurred_at:'2026-08-26T11:01:00.000Z'}]};
const pausedAnchor=C.createAnchor(paused,200000);assert.equal(C.projectedSecond(pausedAnchor,260000),605,'paused match clock must not advance');assert.equal(C.confirmedPauseSecond(paused),30);assert.equal(C.projectedPauseSecond(pausedAnchor,200000),30);assert.equal(C.projectedPauseSecond(pausedAnchor,205000),35,'pause clock must advance while match time is frozen');assert.equal(pausedAnchor.pauseActive,true);
const halftime={server_now:'2026-08-26T12:03:15.000Z',match:{status:'halftime'},state:{state_version:9,period:'halftime',clock_status:'stopped',effective_elapsed_seconds:2400},events:[{id:'h1',event_type:'halftime_started',occurred_at:'2026-08-26T12:00:00.000Z'}]};
const halfAnchor=C.createAnchor(halftime,300000);assert.equal(C.projectedSecond(halfAnchor,305000),2400,'halftime must not change match time');assert.equal(C.confirmedBreakSecond(halftime),195);assert.equal(C.projectedBreakSecond(halfAnchor,305000),200);assert.equal(C.projectedPauseSecond(halfAnchor,305000),0,'rustklok en pauzeklok zijn afzonderlijk');
const secondHalf={...halftime,match:{status:'live'},state:{...halftime.state,state_version:10,period:'second_half',clock_status:'running'}};const secondAnchor=C.createAnchor(secondHalf,400000);assert.equal(secondAnchor.breakActive,false);assert.equal(secondAnchor.pauseActive,false);assert.equal(C.projectedBreakSecond(secondAnchor,405000),0);
console.log('PASS clock-projector: match + pause + halftime clocks share server anchors');
