/* ClubMatch Cloud v0.8 - correcties achteraf op append-only events */
(function(global){
'use strict';
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function eventSecond(event){return Math.max(0,(Number(event?.match_minute)||0)*60+(Number(event?.match_second)||0))}
function fmtSecond(total){const s=Math.max(0,Math.floor(Number(total)||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function deriveCorrectionRows(snapshot){
  const events=Array.isArray(snapshot?.events)?snapshot.events:[],voided=new Set(),corrections=new Map();
  events.forEach(e=>{if(/_voided$/.test(e.event_type)&&e.target_event_id)voided.add(e.target_event_id);if(/_corrected$/.test(e.event_type)&&e.target_event_id)corrections.set(e.target_event_id,e)});
  return events.filter(e=>['substitution','position_changed','goal_for','goal_against'].includes(e.event_type)).map(base=>{
    const effective=corrections.get(base.id)||base,isVoided=voided.has(base.id),isSwap=base.event_type==='position_changed'&&(base.payload?.swap===true||!!base.related_player_id);
    return Object.freeze({id:base.id,type:base.event_type,base,effective,isVoided,isCorrected:effective!==base,isSwap,canCorrect:!isVoided&&!isSwap,canVoid:!isVoided,matchSecond:eventSecond(effective)});
  }).sort((a,b)=>b.matchSecond-a.matchSecond);
}
function playerMap(snapshot){return new Map((snapshot?.players||[]).map(p=>[p.player_id,p]))}
function playerName(map,id){const p=map.get(id);return p?`#${p.shirt_number??'—'} ${p.display_name||p.full_name||id}`:'—'}
function rowDescription(row,map){const e=row.effective,b=row.base;if(row.type==='substitution'){const d=e.substitution||b.substitution||{};return `${playerName(map,e.subject_player_id||d.player_out_id)} uit · ${playerName(map,e.related_player_id||d.player_in_id)} in · ${e.payload?.new_position||d.new_position||b.payload?.new_position||'—'}`}if(row.type==='position_changed'){if(row.isSwap)return `Positieruil: ${playerName(map,b.subject_player_id)} ↔ ${playerName(map,b.related_player_id)}`;const d=e.position_change||b.position_change||{};return `${playerName(map,e.subject_player_id||d.player_id)} → ${e.payload?.new_position||d.new_position||'—'}`}const g=e.goal||b.goal||{},side=g.side||(b.event_type==='goal_for'?'for':'against');if(side==='against')return `Doelpunt tegenstander${g.goal_type?` · ${g.goal_type}`:''}`;return `${playerName(map,g.scorer_player_id||e.subject_player_id)}${g.assist_player_id?` · assist ${playerName(map,g.assist_player_id)}`:''}${g.goal_type?` · ${g.goal_type}`:''}`}
function createCorrectionUi(options={}){
  const doc=options.document||global.document,runtime=options.runtime;if(!doc||!runtime)throw new Error('Document en live-runtime zijn verplicht');let panel=null,editingId=null,lastSnapshot=null;
  function ensureStyles(){if(doc.getElementById('v08CorrectionStyles'))return;const s=doc.createElement('style');s.id='v08CorrectionStyles';s.textContent=`.corrList{display:grid;gap:7px}.corrRow{border:1px solid #e5d8f0;border-radius:11px;padding:9px;background:#fcfaff}.corrRowTop{display:grid;grid-template-columns:70px 100px 1fr auto;gap:8px;align-items:center}.corrBadge{font-size:10px;font-weight:900;color:#4b2672}.corrState{font-size:10px}.corrState.changed{color:#6f42c1;font-weight:900}.corrState.voided{color:#983263;font-weight:900}.corrActions{display:flex;gap:5px;flex-wrap:wrap}.corrActions button{font-size:10px;padding:6px 8px}.corrEdit{margin-top:8px;padding-top:8px;border-top:1px solid #eee}.corrEditGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.corrReason{font-size:10px;color:#6b5877}@media(max-width:760px){.corrRowTop{grid-template-columns:55px 85px 1fr}.corrActions{grid-column:1/-1}.corrEditGrid{grid-template-columns:1fr 1fr}}@media(max-width:480px){.corrEditGrid{grid-template-columns:1fr}}`;doc.head.appendChild(s)}
  function ensureMounted(){if(panel)return panel;ensureStyles();const app=doc.getElementById('appPanel');if(!app)throw new Error('ClubMatch-appscherm ontbreekt');panel=doc.createElement('section');panel.id='v08Corrections';panel.className='card hidden';const live=app.querySelector('.liveLayout');if(live)app.insertBefore(panel,live);else app.appendChild(panel);return panel}
  function selectedOptions(snapshot,value='',allowEmpty=false){const players=(snapshot?.players||[]).filter(p=>p.selected);return (allowEmpty?'<option value="">— geen —</option>':'')+players.map(p=>`<option value="${esc(p.player_id)}"${p.player_id===value?' selected':''}>#${esc(p.shirt_number??'—')} ${esc(p.display_name||p.full_name||p.player_id)}</option>`).join('')}
  function timeFields(row){return `<label>Minuut<input id="corrMinute" type="number" min="0" max="300" value="${Math.floor(row.matchSecond/60)}"></label><label>Seconde<input id="corrSecond" type="number" min="0" max="59" value="${row.matchSecond%60}"></label>`}
  function goalTypeOptions(value=''){const values=[['','— type —'],['open_play','Open spel'],['counter','Omschakeling'],['set_piece','Standaardsituatie'],['corner','Hoekschop'],['free_kick','Vrije trap'],['penalty','Strafschop'],['own_goal','Eigen doelpunt'],['other','Overig']];return values.map(([v,label])=>`<option value="${v}"${v===value?' selected':''}>${label}</option>`).join('')}
  function editHtml(row,snapshot){
    const e=row.effective,b=row.base;
    if(row.type==='substitution'){const d=e.substitution||b.substitution||{},out=e.subject_player_id||d.player_out_id,inn=e.related_player_id||d.player_in_id,pos=e.payload?.new_position||d.new_position||b.payload?.new_position||'';return `<div class="corrEdit"><div class="corrEditGrid"><label>Speler uit<select id="corrOut">${selectedOptions(snapshot,out)}</select></label><label>Speler in<select id="corrIn">${selectedOptions(snapshot,inn)}</select></label><label>Nieuwe positie<input id="corrPosition" value="${esc(pos)}"></label>${timeFields(row)}</div><div class="controls" style="margin-top:7px"><button id="corrSave" data-v08-action>Correctie opslaan</button><button id="corrCancel" class="secondary" data-v08-action>Annuleren</button></div></div>`}
    if(row.type==='position_changed'){const d=e.position_change||b.position_change||{},pid=e.subject_player_id||d.player_id,pos=e.payload?.new_position||d.new_position||'';return `<div class="corrEdit"><div class="corrEditGrid"><label>Speler<select id="corrPlayer">${selectedOptions(snapshot,pid)}</select></label><label>Nieuwe positie<input id="corrPosition" value="${esc(pos)}"></label>${timeFields(row)}</div><div class="controls" style="margin-top:7px"><button id="corrSave" data-v08-action>Correctie opslaan</button><button id="corrCancel" class="secondary" data-v08-action>Annuleren</button></div></div>`}
    const g=e.goal||b.goal||{},side=g.side||(b.event_type==='goal_for'?'for':'against'),scorer=g.scorer_player_id||e.subject_player_id||'',assist=g.assist_player_id||e.related_player_id||'',goalType=g.goal_type||e.payload?.goal_type||'',note=g.note||e.payload?.note||'';
    return `<div class="corrEdit"><div class="corrEditGrid">${side==='for'?`<label>Maker<select id="corrScorer">${selectedOptions(snapshot,scorer)}</select></label><label>Assist<select id="corrAssist">${selectedOptions(snapshot,assist,true)}</select></label>`:''}<label>Type<select id="corrGoalType">${goalTypeOptions(goalType)}</select></label><label>Notitie<input id="corrNote" value="${esc(note)}"></label>${timeFields(row)}</div><div class="controls" style="margin-top:7px"><button id="corrSave" data-v08-action>Correctie opslaan</button><button id="corrCancel" class="secondary" data-v08-action>Annuleren</button></div></div>`
  }
  function kindLabel(row){if(row.type==='substitution')return 'Wissel';if(row.type==='position_changed')return row.isSwap?'Positieruil':'Positie';return 'Doelpunt'}
  function render(snapshot){
    lastSnapshot=snapshot;const root=ensureMounted();if(!snapshot?.match?.id){root.classList.add('hidden');root.replaceChildren();return root}const rows=deriveCorrectionRows(snapshot),map=playerMap(snapshot);
    root.innerHTML=`<div class="sectionTitle"><div><h2 style="margin-bottom:3px">Correcties achteraf</h2><div class="muted">Originele gebeurtenissen blijven bewaard. Correcties en ongeldig maken worden als nieuwe Cloud-gebeurtenissen vastgelegd.</div></div><span class="badge">${rows.length} gebeurtenissen</span></div><div class="corrList" style="margin-top:9px">${rows.map(row=>`<div class="corrRow" data-corr-id="${esc(row.id)}"><div class="corrRowTop"><b>${fmtSecond(row.matchSecond)}</b><span class="corrBadge">${kindLabel(row)}</span><div><div>${esc(rowDescription(row,map))}</div><div class="corrState ${row.isVoided?'voided':row.isCorrected?'changed':''}">${row.isVoided?'ONGELDIG':row.isCorrected?'GECORRIGEERD':'ORIGINEEL'}${row.isSwap?' · atomaire ruil':''}</div></div><div class="corrActions">${row.canCorrect?'<button class="secondary" data-corr-edit data-v08-action>Corrigeren</button>':''}${row.canVoid?'<button class="danger" data-corr-void data-v08-action>Ongeldig maken</button>':''}</div></div>${editingId===row.id&&row.canCorrect?editHtml(row,snapshot):''}</div>`).join('')||'<div class="muted">Nog geen wissels, positiewijzigingen of doelpunten om te corrigeren.</div>'}</div>`;
    bind(root,rows);root.classList.remove('hidden');return root
  }
  function bind(root,rows){root.querySelectorAll('[data-corr-id]').forEach(node=>{const row=rows.find(r=>r.id===node.dataset.corrId);node.querySelector('[data-corr-edit]')?.addEventListener('click',()=>{editingId=row.id;render(lastSnapshot)});node.querySelector('#corrCancel')?.addEventListener('click',()=>{editingId=null;render(lastSnapshot)});node.querySelector('[data-corr-void]')?.addEventListener('click',()=>{if(!global.confirm?.(`${kindLabel(row)} op ${fmtSecond(row.matchSecond)} ongeldig maken?\n\nDe originele invoer blijft in de auditgeschiedenis staan.`))return;const reason=global.prompt?.('Reden (optioneel):','')||'';options.run?.(`${kindLabel(row)} ongeldig maken`,async()=>{if(row.type==='substitution')await runtime.voidSubstitution({eventId:row.id,reason});else if(row.type==='position_changed')await runtime.voidPositionChange({eventId:row.id,reason});else await runtime.voidGoal({eventId:row.id,reason});editingId=null;render(runtime.snapshot)})});node.querySelector('#corrSave')?.addEventListener('click',()=>options.run?.('Correctie opslaan',async()=>{const minute=Number(node.querySelector('#corrMinute')?.value),second=Number(node.querySelector('#corrSecond')?.value);if(row.type==='substitution')await runtime.correctSubstitution({eventId:row.id,outId:node.querySelector('#corrOut').value,inId:node.querySelector('#corrIn').value,position:node.querySelector('#corrPosition').value,matchMinute:minute,matchSecond:second});else if(row.type==='position_changed')await runtime.correctPositionChange({eventId:row.id,playerId:node.querySelector('#corrPlayer').value,position:node.querySelector('#corrPosition').value,matchMinute:minute,matchSecond:second});else{const side=(row.base.goal?.side||(row.type==='goal_for'?'for':'against'));await runtime.correctGoal({eventId:row.id,scorerId:side==='for'?node.querySelector('#corrScorer').value:null,assistId:side==='for'?(node.querySelector('#corrAssist').value||null):null,goalType:node.querySelector('#corrGoalType').value||null,note:node.querySelector('#corrNote').value||null,matchMinute:minute,matchSecond:second})}editingId=null;render(runtime.snapshot)}))})}
  function clear(){editingId=null;lastSnapshot=null;const root=ensureMounted();root.replaceChildren();root.classList.add('hidden')}
  return Object.freeze({render,clear,get visible(){return panel&&!panel.classList.contains('hidden')}})
}
global.ClubMatchV08Corrections={createCorrectionUi,deriveCorrectionRows,rowDescription,eventSecond,fmtSecond};
})(typeof window!=='undefined'?window:globalThis);
