import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const context={console,globalThis:null,window:null};context.globalThis=context;context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('./dashboard-controller.js',import.meta.url),'utf8'),context);let calls=[];
const dashboardData=team=>({team_season_id:team,players:[{player_id:'p1',name:'A',play:'80',bench:'10',goals:'2',assists:'1',rating:'82',ratingReliability:'middel',actionTotal:'12',possessionSeconds:'100',relationships:{passReceived:30,ballLoss:6,ballLossPerReceivedPct:20,duelWinPct:60}}],matches:[{id:'m1',opponent:'DEM',score_for:'3',score_against:'1',duration:'80',include_in_dashboard:true,can_delete:true}],kpis:{matches:'1',available_matches:'2',play_minutes:'880',bench_minutes:'110',goals:'3',assists:'2',absent:'1',actions:'12',possession_seconds:'100'},rating_model:{version:'cm-100-v1',min:1,max:100},analysis_model:{version:'cm-relations-v1'}});
const overview={team_season_id:'ts1',player:{player_id:'p1',name:'A',rating:82,relationships:{passReceived:30,ballLossPerReceivedPct:20}},training_summary:{trainingScore:88},matches:[{match_id:'m1'}],trainings:[{training_session_id:'tr1'}],recent_events:[{id:'e1'}]};
const client={async rpc(name,params={}){calls.push({name,params});if(name==='get_my_team_seasons')return {data:[{team_season_id:'ts1',team_name:'O16'},{team_season_id:'ts2',team_name:'O13'}],error:null};if(name==='get_cloud_dashboard_v2')return {data:dashboardData(params.p_team_season_id),error:null};if(name==='get_player_overview_v08')return {data:overview,error:null};if(name==='set_match_dashboard_inclusion_v08')return {data:{ok:true},error:null};if(name==='delete_match_v08')return {data:{ok:true},error:null};return {data:null,error:new Error(`unexpected ${name}`)}}};
const D=context.ClubMatchV08Dashboard.createDashboardController({client});await D.loadTeams();assert.equal(D.state.teamSeasons.length,2);await D.load('ts1');assert.equal(D.state.dashboard.teamSeasonId,'ts1');assert.equal(D.state.dashboard.players[0].rating,82);assert.equal(D.state.dashboard.players[0].relationships.ballLossPerReceivedPct,20);assert.equal(D.state.dashboard.analysisModel.version,'cm-relations-v1');assert.ok(calls.some(c=>c.name==='get_cloud_dashboard_v2'));
await D.loadPlayer('p1');assert.equal(D.state.playerOverview.training_summary.trainingScore,88);assert.ok(calls.some(c=>c.name==='get_player_overview_v08'&&c.params.p_player_id==='p1'&&c.params.p_team_season_id==='ts1'));D.closePlayer();assert.equal(D.state.playerOverview,null);
await D.setMatchIncluded('m1',false);assert.ok(calls.some(c=>c.name==='set_match_dashboard_inclusion_v08'&&c.params.p_include===false));await D.deleteMatch('m1','DELETE');assert.ok(calls.some(c=>c.name==='delete_match_v08'&&c.params.p_confirmation==='DELETE'));await assert.rejects(()=>D.deleteMatch('m1','JA'),/DELETE/);await D.load(null);assert.equal(calls.at(-1).params.p_team_season_id,null);assert.equal(Object.isFrozen(D.state.dashboard),true);
console.log('PASS dashboard-controller: Dashboard v2 relationships + Player 360 + match selection/delete');
