/* ClubMatch Cloud v0.8 - dashboard PDF owner: print the actual dashboard */
(function(global){
'use strict';
const doc=global.document;if(!doc)return;let latestState=null,busy=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function styleSource(){let out='';doc.querySelectorAll('style,link[rel="stylesheet"]').forEach(n=>{if(n.tagName==='STYLE')out+=`<style>${n.textContent}</style>`;else if(n.href)out+=`<link rel="stylesheet" href="${esc(n.href)}">`});return out}
function cloneDashboard(){const primary=doc.getElementById('v08PerformanceAnalysis');if(!primary)throw new Error('Dashboard is nog niet geladen');const wrap=doc.createElement('div'),copy=primary.cloneNode(true);copy.querySelectorAll('button,.cmInfoBtn,.cmiInfo,[data-cm-info]').forEach(x=>x.remove());wrap.appendChild(copy);const synergy=doc.getElementById('v08TeamSynergy');if(synergy&&!copy.querySelector('#v08TeamSynergy')){const s=synergy.cloneNode(true);s.querySelectorAll('button,.cmInfoBtn,.cmiInfo,[data-cm-info]').forEach(x=>x.remove());wrap.appendChild(s)}return wrap.innerHTML}
function printHtml(){const state=latestState||{},p=state.teamPerformance||{},title=p.scope?.type==='match'?`${p.team_name||'Team'} – ${p.scope?.opponent||'wedstrijd'}`:`${p.team_name||'Team'} – ClubMatch dashboard`,content=cloneDashboard();return `<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title>${styleSource()}<style>body{margin:0!important;background:#fff!important;color:#163048!important;font-family:Arial,Helvetica,sans-serif!important}.cmPdfPage{max-width:1180px;margin:auto;padding:18px}.cmPdfHeader{display:flex;justify-content:space-between;gap:12px;align-items:flex-end;border-bottom:3px solid #0d527e;padding-bottom:10px;margin-bottom:14px}.cmPdfHeader b{font-size:22px;color:#071d33}.cmPdfHeader span{font-size:11px;color:#607b8f}.cmPdfSource{font-size:10px;color:#607b8f;margin:12px 0;padding:8px;background:#f7fafc;border-radius:8px}@page{size:A4 portrait;margin:10mm}@media print{html,body{width:auto!important;overflow:visible!important}.cmPdfPage{max-width:none;padding:0}.cmPdfHeader{break-after:avoid}.cmiTop,#v11MatchIntelligence,.cmiPlayers,#v08TeamSynergy,.mi11Panel,.mi11Card,.mi11Impact>div,.cmiMetric,.cmiKpi,.cmiPlayer{break-inside:avoid}.mi11Timeline,.mi11Box{overflow:visible!important}.mi11Timeline svg{min-width:0!important}.mi11Box table{min-width:0!important;font-size:7px!important}.mi11Box th,.mi11Box td{padding:3px!important}.cmiActions,button{display:none!important}}</style></head><body><div class="cmPdfPage"><div class="cmPdfHeader"><b>${esc(title)}</b><span>ClubMatch Cloud · dashboard PDF</span></div>${content}<div class="cmPdfSource"><b>Rekenbasis:</b> dezelfde dashboarddata en dezelfde analyseblokken als op de website. Team Performance en Samenspel zijn verschillende modellen; de formule-uitleg in het dashboard wordt mee afgedrukt. Afstand uit actiecoördinaten is alleen een actie-afstandsindicator en geen GPS-loopafstand.</div></div><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),350));<\/script></body></html>`}
function printDashboard(){if(busy)return false;busy=true;try{const w=global.open?.('','_blank');if(!w)throw new Error('Pop-up geblokkeerd. Sta pop-ups toe voor Dashboard PDF.');w.document.open();w.document.write(printHtml());w.document.close();return true}finally{busy=false}}
function attach(state=latestState){if(state)latestState=state;const top=doc.querySelector('#v08PerformanceAnalysis .cmiTop');if(!top)return;let b=doc.getElementById('v09DashboardPdfBtn');if(!b){b=doc.createElement('button');b.id='v09DashboardPdfBtn';b.type='button';b.style.cssText='border:0;border-radius:10px;padding:9px 12px;background:#fff;color:#0d3552;font-weight:900;cursor:pointer;justify-self:end';top.appendChild(b)}b.textContent='🖨 Dashboard PDF · zoals website';b.title='Opent dezelfde dashboardweergave; kies daarna Opslaan als PDF';b.onclick=()=>{try{printDashboard()}catch(e){global.alert?.(`Dashboard PDF kon niet worden geopend: ${e.message||e}`)}}}
global.addEventListener?.('clubmatch:v08-dashboard-state',e=>{latestState=e.detail;setTimeout(()=>attach(e.detail),100)});
const api=Object.freeze({attach,print:printDashboard,download:printDashboard,cloneDashboard,printHtml,get latest(){return latestState}});global.ClubMatchV10DashboardPdf=api;global.ClubMatchV09DashboardPdf=api;
})(typeof window!=='undefined'?window:globalThis);
