/* ClubMatch Cloud v0.8 - dashboard en historie */
(function(global){
'use strict';
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function createDashboardUi(options={}){
  const doc=options.document||global.document,controller=options.controller;if(!doc||!controller)throw new Error('Document en dashboardcontroller zijn verplicht');let panel=null,sortKey='play';
  function ensureMounted(){if(panel)return panel;const app=doc.getElementById('appPanel');if(!app)throw new Error('ClubMatch-appscherm ontbreekt');panel=doc.createElement('section');panel.id='v08Dashboard';panel.className='card hidden';const prep=doc.getElementById('v08Preparation');if(prep)prep.after(panel);else app.firstElementChild?.after(panel);return panel}
  function teamOptions(state){return '<option value="">Alle teams</option>'+state.teamSeasons.map(t=>`<option value="${esc(t.team_season_id)}"${t.team_season_id===state.dashboard.teamSeasonId?' selected':''}>${esc(t.club_name)} · ${esc(t.team_name)} · ${esc(t.season_name)}</option>`).join('')}
  function sortedPlayers(players){const list=[...players];if(sortKey==='name')return list.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'nl'));return list.sort((a,b)=>Number(b[sortKey]||0)-Number(a[sortKey]||0)||String(a.name||'').localeCompare(String(b.name||''),'nl'))}
  function render(state){
    const root=ensureMounted(),d=state.dashboard,k=d.kpis,players=sortedPlayers(d.players);
    root.innerHTML=`<div class="sectionTitle"><div><h2 style="margin-bottom:3px">Dashboard & historie</h2><div class="muted">Afgeronde wedstrijden uit dezelfde bevestigde Cloud-bron.</div></div><div class="controls"><button id="dashRefresh" class="secondary" data-v08-action>↻ Dashboard</button><button id="dashClose" class="secondary" data-v08-action>Sluiten</button></div></div>
      <div class="grid2" style="margin-top:10px"><label>Teamfilter<select id="dashTeam">${teamOptions(state)}</select></label><label>Sorteer spelers<select id="dashSort"><option value="play">Speeltijd</option><option value="avg">Gemiddelde speeltijd</option><option value="playPct">% speeltijd</option><option value="goals">Doelpunten</option><option value="assists">Assists</option><option value="present">Aanwezig</option><option value="name">Naam</option></select></label></div>
      <div style="display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:7px;margin:10px 0"><div class="status"><b>${k.matches}</b><div class="muted">Wedstrijden</div></div><div class="status"><b>${k.play_minutes}</b><div class="muted">Speelminuten</div></div><div class="status"><b>${k.bench_minutes}</b><div class="muted">Bankminuten</div></div><div class="status"><b>${k.goals}</b><div class="muted">Doelpunten</div></div><div class="status"><b>${k.assists}</b><div class="muted">Assists</div></div><div class="status"><b>${k.absent}</b><div class="muted">Afwezig</div></div></div>
      <h3>Spelers</h3><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;min-width:820px"><thead><tr><th style="text-align:left">Speler</th><th>Aanwezig</th><th>Basis</th><th>Speeltijd</th><th>Banktijd</th><th>Gem.</th><th>%</th><th>Doelpunten</th><th>Assists</th></tr></thead><tbody>${players.map(p=>`<tr style="border-top:1px solid #eee"><td style="padding:6px"><b>#${esc(p.number??'—')} ${esc(p.display_name||p.name)}</b><div class="muted">${esc(p.team||'')}</div></td><td style="text-align:center">${p.present}</td><td style="text-align:center">${p.starts}</td><td style="text-align:center">${p.play}</td><td style="text-align:center">${p.bench}</td><td style="text-align:center">${p.avg}</td><td style="text-align:center">${p.playPct}%</td><td style="text-align:center">${p.goals}</td><td style="text-align:center">${p.assists}</td></tr>`).join('')||'<tr><td colspan="9" class="muted" style="padding:8px">Nog geen afgeronde spelersgegevens.</td></tr>'}</tbody></table></div>
      <h3 style="margin-top:14px">Wedstrijden</h3><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;min-width:720px"><thead><tr><th style="text-align:left">Datum</th><th style="text-align:left">Team</th><th style="text-align:left">Tegenstander</th><th>Score</th><th>Duur</th><th>Formatie</th></tr></thead><tbody>${d.matches.map(m=>`<tr style="border-top:1px solid #eee"><td style="padding:6px">${esc(m.match_date||'')}</td><td>${esc(m.team||'')}</td><td>${esc(m.opponent||'')}</td><td style="text-align:center"><b>${m.score_for}–${m.score_against}</b></td><td style="text-align:center">${m.duration??'—'} min</td><td style="text-align:center">${esc(m.formation||'—')}</td></tr>`).join('')||'<tr><td colspan="6" class="muted" style="padding:8px">Nog geen afgeronde wedstrijden.</td></tr>'}</tbody></table></div>`;
    const sort=root.querySelector('#dashSort');sort.value=sortKey;sort.onchange=()=>{sortKey=sort.value;render(controller.state)};
    root.querySelector('#dashTeam').onchange=e=>options.run?.('Dashboard laden',()=>controller.load(e.target.value||null));root.querySelector('#dashRefresh').onclick=()=>options.run?.('Dashboard verversen',()=>controller.load(controller.state.dashboard.teamSeasonId));root.querySelector('#dashClose').onclick=hide;root.classList.remove('hidden');return root;
  }
  function show(){ensureMounted().classList.remove('hidden');render(controller.state)}function hide(){ensureMounted().classList.add('hidden')}
  return Object.freeze({render,show,hide,get visible(){return panel&&!panel.classList.contains('hidden')}});
}
global.ClubMatchV08DashboardUi={createDashboardUi};
})(typeof window!=='undefined'?window:globalThis);
