/* ClubMatch Cloud v0.8 - dashboard, match selection, actions, 1-100 rating and history */
(function(global){
'use strict';
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtSeconds(value){const s=Math.max(0,Math.round(Number(value)||0));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
const ACTION_LABELS={possession_control:'Balcontrole',ball_recovery:'Veroverd',interception:'Onderschept',block:'Blok',ball_loss:'Balverlies',bad_pass:'Foute pass',chance_created:'Kans',duel_won:'Duel +',duel_lost:'Duel −',shot:'Schot',shot_on_target:'Op doel',foul_committed:'Overtreding',foul_won:'Overtreding mee',save:'Redding',injury:'Blessure'};
function createDashboardUi(options={}){
  const doc=options.document||global.document,controller=options.controller;if(!doc||!controller)throw new Error('Document en dashboardcontroller zijn verplicht');let panel=null,sortKey='rating';
  function ensureStyles(){if(doc.getElementById('v08DashStyles'))return;const s=doc.createElement('style');s.id='v08DashStyles';s.textContent='.dashKpis{display:grid;grid-template-columns:repeat(8,minmax(0,1fr));gap:7px;margin:10px 0}.dashRating{display:inline-flex;min-width:42px;justify-content:center;padding:5px 7px;border-radius:10px;background:#4b2672;color:#fff;font-size:17px;font-weight:900}.dashReliability{font-size:9px;color:#6b5877;margin-top:2px}.dashActions{display:flex;flex-wrap:wrap;gap:3px}.dashAction{font-size:9px;padding:2px 5px;border-radius:999px;background:#f3edf9;color:#4b2672;white-space:nowrap}.dashModel{padding:8px 10px;border-radius:10px;background:#fff8e9;border:1px solid #ead09a;font-size:10px;color:#6c5325;margin:8px 0}.dashMatchOff{opacity:.48;background:#fafafa}.dashDelete{border:1px solid #b23a48!important;background:#fff!important;color:#983263!important}.dashInclude{display:inline-flex;gap:5px;align-items:center;white-space:nowrap}@media(max-width:800px){.dashKpis{grid-template-columns:repeat(2,1fr)}}';doc.head.appendChild(s)}
  function ensureMounted(){if(panel)return panel;ensureStyles();const app=doc.getElementById('appPanel');if(!app)throw new Error('ClubMatch-appscherm ontbreekt');panel=doc.createElement('section');panel.id='v08Dashboard';panel.className='card hidden';const prep=doc.getElementById('v08Preparation');if(prep)prep.after(panel);else app.firstElementChild?.after(panel);return panel}
  function teamOptions(state){return '<option value="">Alle teams</option>'+state.teamSeasons.map(t=>`<option value="${esc(t.team_season_id)}"${t.team_season_id===state.dashboard.teamSeasonId?' selected':''}>${esc(t.club_name)} · ${esc(t.team_name)} · ${esc(t.season_name)}</option>`).join('')}
  function sortedPlayers(players){const list=[...players];if(sortKey==='name')return list.sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'nl'));return list.sort((a,b)=>Number(b[sortKey]||0)-Number(a[sortKey]||0)||String(a.name||'').localeCompare(String(b.name||''),'nl'))}
  function actionHtml(p){const items=Object.entries(p.actions||{}).filter(([,n])=>Number(n)>0).sort((a,b)=>Number(b[1])-Number(a[1]));return items.length?`<div class="dashActions">${items.map(([k,n])=>`<span class="dashAction">${esc(ACTION_LABELS[k]||k)} ${Number(n)}</span>`).join('')}</div>`:'<span class="muted">nog niet gelogd</span>'}
  function weightsText(model){const w=model?.weights||{};return Object.entries(w).map(([k,v])=>`${ACTION_LABELS[k]||k}: ${Number(v)>0?'+':''}${v}`).join(' · ')}
  function render(state){const root=ensureMounted(),d=state.dashboard,k=d.kpis,players=sortedPlayers(d.players);root.innerHTML=`<div class="sectionTitle"><div><h2 style="margin-bottom:3px">Dashboard & historie</h2><div class="muted">Alleen aangevinkte wedstrijden tellen mee in KPI's, acties en rating.</div></div><div class="controls"><button id="dashRefresh" class="secondary" data-v08-action>↻ Dashboard</button><button id="dashClose" class="secondary" data-v08-action>Sluiten</button></div></div>
    <div class="grid2" style="margin-top:10px"><label>Teamfilter<select id="dashTeam">${teamOptions(state)}</select></label><label>Sorteer spelers<select id="dashSort"><option value="rating">ClubMatch Rating</option><option value="actionTotal">Acties</option><option value="possessionSeconds">Balbezit-tijd</option><option value="play">Speeltijd</option><option value="avg">Gemiddelde speeltijd</option><option value="playPct">% speeltijd</option><option value="goals">Doelpunten</option><option value="assists">Assists</option><option value="present">Aanwezig</option><option value="name">Naam</option></select></label></div>
    <div class="dashKpis"><div class="status"><b>${k.matches}/${k.available_matches}</b><div class="muted">Mee / beschikbaar</div></div><div class="status"><b>${k.play_minutes}</b><div class="muted">Speelminuten</div></div><div class="status"><b>${k.bench_minutes}</b><div class="muted">Bankminuten</div></div><div class="status"><b>${k.goals}</b><div class="muted">Doelpunten</div></div><div class="status"><b>${k.assists}</b><div class="muted">Assists</div></div><div class="status"><b>${k.actions}</b><div class="muted">Acties gelogd</div></div><div class="status"><b>${fmtSeconds(k.possession_seconds)}</b><div class="muted">Eigen bezit gemeten</div></div><div class="status"><b>${k.absent}</b><div class="muted">Afwezig</div></div></div>
    ${d.ratingModel?`<div class="dashModel"><b>ClubMatch Performance Rating 1–100 · ${esc(d.ratingModel.version||'')}</b><br>${esc(d.ratingModel.description||'')}<br><b>Formule:</b> basis ${esc(d.ratingModel.base??50)} + gewogen prestatiepunten × ${esc(d.ratingModel.normalizationMinutes??80)} / max(speelminuten, ${esc(d.ratingModel.minimumNormalizerMinutes??20)}), begrensd op 1–100.<br><span class="muted">${esc(weightsText(d.ratingModel))}</span></div>`:''}
    <h3>Spelers</h3><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;min-width:1180px"><thead><tr><th style="text-align:left">Speler</th><th>Rating</th><th>Aanwezig</th><th>Basis</th><th>Speeltijd</th><th>Banktijd</th><th>%</th><th>Goals</th><th>Assists</th><th>Acties</th><th>Bezit</th><th style="text-align:left">Actieverdeling</th></tr></thead><tbody>${players.map(p=>`<tr style="border-top:1px solid #eee"><td style="padding:6px"><b>#${esc(p.number??'—')} ${esc(p.display_name||p.name)}</b><div class="muted">${esc(p.team||'')}</div></td><td style="text-align:center"><span class="dashRating">${p.rating}</span><div class="dashReliability">betrouwbaarheid ${esc(p.ratingReliability)}</div></td><td style="text-align:center">${p.present}</td><td style="text-align:center">${p.starts}</td><td style="text-align:center">${p.play}</td><td style="text-align:center">${p.bench}</td><td style="text-align:center">${p.playPct}%</td><td style="text-align:center">${p.goals}</td><td style="text-align:center">${p.assists}</td><td style="text-align:center">${p.actionTotal}</td><td style="text-align:center">${fmtSeconds(p.possessionSeconds)}<div class="muted">${p.possessionShare}% van gemeten eigen bezit</div></td><td>${actionHtml(p)}</td></tr>`).join('')||'<tr><td colspan="12" class="muted" style="padding:8px">Nog geen meegenomen wedstrijdgegevens.</td></tr>'}</tbody></table></div>
    <h3 style="margin-top:14px">Wedstrijden selecteren</h3><div class="muted" style="margin-bottom:6px">Vink uit wat niet in dashboard, rating en totalen mag meetellen. De wedstrijd blijft wel opgeslagen.</div><div style="overflow:auto"><table style="width:100%;border-collapse:collapse;min-width:1080px"><thead><tr><th>Mee</th><th style="text-align:left">Datum</th><th style="text-align:left">Team</th><th style="text-align:left">Tegenstander</th><th>Score</th><th>Duur</th><th>Formatie</th><th>Acties</th><th>Eigen bezit</th><th>Beheer</th></tr></thead><tbody>${d.matches.map(m=>`<tr class="${m.include_in_dashboard?'':'dashMatchOff'}" data-dash-match="${esc(m.id)}" style="border-top:1px solid #eee"><td style="text-align:center"><label class="dashInclude"><input type="checkbox" data-dash-include ${m.include_in_dashboard?'checked':''}> mee</label></td><td style="padding:6px">${esc(m.match_date||'')}</td><td>${esc(m.team||'')}</td><td>${esc(m.opponent||'')}</td><td style="text-align:center"><b>${m.score_for}–${m.score_against}</b></td><td style="text-align:center">${m.duration??'—'} min</td><td style="text-align:center">${esc(m.formation||'—')}</td><td style="text-align:center">${m.action_count}</td><td style="text-align:center">${fmtSeconds(m.possession_seconds)} · ${m.possession_pct}%</td><td>${m.can_delete?'<button type="button" class="dashDelete" data-dash-delete data-v08-action>🗑 Verwijderen</button>':'<span class="muted">alleen clubbeheer</span>'}</td></tr>`).join('')||'<tr><td colspan="10" class="muted" style="padding:8px">Nog geen afgeronde wedstrijden.</td></tr>'}</tbody></table></div>`;
    const sort=root.querySelector('#dashSort');sort.value=sortKey;sort.onchange=()=>{sortKey=sort.value;render(controller.state)};
    root.querySelector('#dashTeam').onchange=e=>options.run?.('Dashboard laden',()=>controller.load(e.target.value||null));root.querySelector('#dashRefresh').onclick=()=>options.run?.('Dashboard verversen',()=>controller.load(controller.state.dashboard.teamSeasonId));root.querySelector('#dashClose').onclick=hide;
    root.querySelectorAll('[data-dash-match]').forEach(row=>{const id=row.dataset.dashMatch;row.querySelector('[data-dash-include]')?.addEventListener('change',e=>options.run?.('Dashboardselectie opslaan',()=>controller.setMatchIncluded(id,e.target.checked)));row.querySelector('[data-dash-delete]')?.addEventListener('click',()=>{if(!global.confirm?.('Deze opgeslagen wedstrijd definitief verwijderen? Alle gekoppelde gebeurtenissen en spelerdata worden verwijderd.'))return;const typed=global.prompt?.('Typ DELETE om definitief te verwijderen:','');if(typed!=='DELETE')return;options.run?.('Wedstrijd verwijderen',()=>controller.deleteMatch(id,typed))})});root.classList.remove('hidden');return root}
  function show(){ensureMounted().classList.remove('hidden');render(controller.state)}function hide(){ensureMounted().classList.add('hidden')}
  return Object.freeze({render,show,hide,get visible(){return panel&&!panel.classList.contains('hidden')}})
}
global.ClubMatchV08DashboardUi={createDashboardUi};
})(typeof window!=='undefined'?window:globalThis);
