/* ClubMatch Cloud v0.8 - real designed dashboard PDF v10 (no print dialog) */
(function(global){
'use strict';
const doc=global.document;if(!doc)return;let latest=null,busy=false;
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0},nil=v=>v===null||v===undefined||v===''?null:Number(v),pct=v=>nil(v)===null?'—':`${Math.round(num(v)*10)/10}%`;
function clean(v){return String(v??'').replace(/[–—]/g,'-').replace(/→/g,'->').replace(/←/g,'<-').replace(/[✓✔]/g,'OK').replace(/[⚽🥅🎯🧤✕↺✂]/g,'').replace(/[^\x20-\x7E\xA0-\xFF]/g,' ').replace(/\s+/g,' ').trim()}
function pdfStr(v){return clean(v).replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)')}
function hexRgb(hex){const h=hex.replace('#','');return [parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255]}
const C={navy:'#071d33',blue:'#0d527e',purple:'#6f42c1',green:'#237a43',red:'#983263',amber:'#d39118',light:'#eef5fa',text:'#163048',muted:'#607b8f',white:'#ffffff',line:'#d9e4ec'};
class PdfDoc{
 constructor(){this.pages=[];this.W=595.28;this.H=841.89;this.page=null;this.y=0}
 addPage(){this.page={ops:[]};this.pages.push(this.page);this.y=this.H-42;return this.page}
 color(hex,stroke=false){const [r,g,b]=hexRgb(hex);this.page.ops.push(`${r.toFixed(3)} ${g.toFixed(3)} ${b.toFixed(3)} ${stroke?'RG':'rg'}`)}
 rect(x,y,w,h,fill=C.white,stroke=null,r=0){this.color(fill);this.page.ops.push(`${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re f`);if(stroke){this.color(stroke,true);this.page.ops.push(`0.7 w ${x.toFixed(2)} ${y.toFixed(2)} ${w.toFixed(2)} ${h.toFixed(2)} re S`)}}
 line(x1,y1,x2,y2,color=C.line,width=1){this.color(color,true);this.page.ops.push(`${width} w ${x1.toFixed(2)} ${y1.toFixed(2)} m ${x2.toFixed(2)} ${y2.toFixed(2)} l S`)}
 text(v,x,y,size=10,color=C.text,bold=false,max=0){let s=clean(v);if(max&&s.length>max)s=s.slice(0,Math.max(1,max-1))+'…';this.color(color);this.page.ops.push(`BT /${bold?'F2':'F1'} ${size.toFixed(1)} Tf 1 0 0 1 ${x.toFixed(2)} ${y.toFixed(2)} Tm (${pdfStr(s)}) Tj ET`)}
 wrap(v,x,y,w,size=9,color=C.text,bold=false,lineH=12,maxLines=20){const words=clean(v).split(' '),approx=Math.max(8,Math.floor(w/(size*.52))),lines=[];let line='';for(const word of words){const candidate=line?line+' '+word:word;if(candidate.length>approx&&line){lines.push(line);line=word}else line=candidate;if(lines.length>=maxLines)break}if(line&&lines.length<maxLines)lines.push(line);lines.forEach((l,i)=>this.text(l,x,y-i*lineH,size,color,bold));return y-lines.length*lineH}
 ensure(height){if(!this.page)this.addPage();if(this.y-height<36)this.addPage();return this.y}
 bytes(){const objects=[];const add=s=>{objects.push(s);return objects.length};const font1=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'),font2=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'),contentIds=[],pageIds=[];for(const p of this.pages){const stream=p.ops.join('\n'),cid=add(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);contentIds.push(cid);pageIds.push(add('PENDING'))}const pagesId=add('PAGES_PENDING'),catalogId=add(`<< /Type /Catalog /Pages ${pagesId} 0 R >>`);pageIds.forEach((pid,i)=>objects[pid-1]=`<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 ${this.W.toFixed(2)} ${this.H.toFixed(2)}] /Resources << /Font << /F1 ${font1} 0 R /F2 ${font2} 0 R >> >> /Contents ${contentIds[i]} 0 R >>`);objects[pagesId-1]=`<< /Type /Pages /Count ${pageIds.length} /Kids [${pageIds.map(id=>`${id} 0 R`).join(' ')}] >>`;let out='%PDF-1.4\n%ClubMatch\n',offset=[0];objects.forEach((o,i)=>{offset.push(out.length);out+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=out.length;out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;for(let i=1;i<=objects.length;i++)out+=String(offset[i]).padStart(10,'0')+' 00000 n \n';out+=`trailer\n<< /Size ${objects.length+1} /Root ${catalogId} 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(out)}
}
function confidence(p){const q=p?.pass_quality||{},r=p?.passes?.reliability||q.reliability||'low';if(Number.isFinite(Number(q.confidence_weight)))return Number(q.confidence_weight);return r==='high'?1:r==='medium'?.5:0}
function weighted(p,type){const c=p?.components||{},pc=confidence(p),parts=type==='Samenspel'?[['Passing',c.passing,40*pc],['Team-balbezit',c.possession,20],['Duels',c.duels,15],['Balcontrole',c.ball_control,25]]:[['Passing',c.passing,18*pc],['Team-balbezit',c.possession,12],['Duels',c.duels,10],['Balcontrole',c.ball_control,12],['Aanval',c.attack,18],['Verdediging',c.defense,15],['Discipline',c.discipline,5],['Resultaat',c.result,10]];let n=0,d=0,rows=[];parts.forEach(([name,v,w])=>{if(nil(v)===null||w<=0)return;const prod=num(v)*w;n+=prod;d+=w;rows.push({name,value:num(v),weight:w,product:prod})});return {rows,n,d,result:d?n/d:null}}
function header(pdf,title,sub){pdf.rect(0,pdf.H-105,pdf.W,105,C.navy);pdf.text('CLUBMATCH CLOUD',36,pdf.H-42,11,C.white,true);pdf.text(title,36,pdf.H-65,20,C.white,true,48);pdf.text(sub,36,pdf.H-84,9,'#bcd2e3',false,90);pdf.y=pdf.H-128}
function scoreCards(pdf,p){pdf.ensure(90);const y=pdf.y-70,w=162,g=12,vals=[['Team Performance',p.team_performance_pct,C.purple],['Samenspel',p.teamplay_pct,C.blue],['Datadekking',p.data_coverage_pct,C.green]];vals.forEach((x,i)=>{const X=36+i*(w+g);pdf.rect(X,y,w,66,C.light,C.line);pdf.text(x[0],X+10,y+46,9,C.muted,true);pdf.text(nil(x[1])===null?'—':`${Math.round(num(x[1]))}${i===2?'%':'/100'}`,X+10,y+18,23,x[2],true)});pdf.y=y-18}
function formulaBlock(pdf,p,type){const x=weighted(p,type);pdf.ensure(32+x.rows.length*18+32);const top=pdf.y;pdf.text(`${type} - echte berekening`,36,top,12,C.navy,true);pdf.y-=16;x.rows.forEach(r=>{pdf.rect(36,pdf.y-12,523,17,'#f7fbff',C.line);pdf.text(r.name,43,pdf.y-1,8,C.text,true);pdf.text(`${r.value.toFixed(1)} x ${r.weight.toFixed(1)} = ${r.product.toFixed(1)}`,325,pdf.y-1,8,C.text,false);pdf.y-=18});pdf.rect(36,pdf.y-14,523,20,C.navy);pdf.text('Totaal',43,pdf.y-2,9,C.white,true);pdf.text(`${x.n.toFixed(1)} / ${x.d.toFixed(1)} = ${x.result==null?'—':x.result.toFixed(1)}/100`,325,pdf.y-2,9,C.white,true);pdf.y-=31}
function halfBlock(pdf,state){const po=state?.teamPossession||{},first=po.first_half||{},second=po.second_half||{};pdf.ensure(92);pdf.text('Eerste helft versus tweede helft',36,pdf.y,12,C.navy,true);pdf.y-=16;const vals=[['Eerste helft',first.for_pct,first.against_pct],['Tweede helft',second.for_pct,second.against_pct],['Verschil',nil(first.for_pct)!==null&&nil(second.for_pct)!==null?num(second.for_pct)-num(first.for_pct):null,null]];vals.forEach((v,i)=>{const X=36+i*174;pdf.rect(X,pdf.y-55,162,56,C.white,C.line);pdf.text(v[0],X+8,pdf.y-14,9,C.muted,true);pdf.text(v[1]==null?'—':`${v[1]>=0&&i===2?'+':''}${num(v[1]).toFixed(1)}${i===2?' pp':'%'}`,X+8,pdf.y-38,18,i===2?(num(v[1])>=0?C.green:C.red):C.blue,true);if(i<2)pdf.text(`tegen ${pct(v[2])}`,X+84,pdf.y-37,8,C.muted)});pdf.y-=72}
function componentTable(pdf,p){const c=p.components||{},rows=[['Passing',c.passing],['Team-balbezit',c.possession],['Duels',c.duels],['Balcontrole',c.ball_control],['Aanval',c.attack],['Verdediging',c.defense],['Discipline',c.discipline],['Resultaat',c.result]];pdf.ensure(130);pdf.text('Kerncomponenten',36,pdf.y,12,C.navy,true);pdf.y-=15;for(let i=0;i<rows.length;i+=2){for(let j=0;j<2;j++){const r=rows[i+j];if(!r)continue;const X=36+j*262;pdf.rect(X,pdf.y-27,250,30,C.light,C.line);pdf.text(r[0],X+8,pdf.y-9,9,C.text,true);pdf.text(nil(r[1])===null?'—':`${num(r[1]).toFixed(1)}/100`,X+155,pdf.y-9,10,C.blue,true)}pdf.y-=34}}
function parseChart(){const svg=doc.querySelector('#v11MatchIntelligence .mi11Timeline svg');if(!svg)return null;const vb=(svg.getAttribute('viewBox')||'0 0 900 270').split(/\s+/).map(Number),lines=[...svg.querySelectorAll('polyline')].slice(0,2).map(x=>(x.getAttribute('points')||'').trim().split(/\s+/).map(p=>p.split(',').map(Number)).filter(p=>p.length===2&&p.every(Number.isFinite)));return {vb,lines}}
function chart(pdf){const data=parseChart();if(!data)return;pdf.ensure(185);pdf.text('Balbezit over de wedstrijdminuten',36,pdf.y,12,C.navy,true);const X=48,Y=pdf.y-155,W=500,H=135;pdf.rect(X,Y,W,H,C.white,C.line);[0,25,50,75,100].forEach(v=>{const yy=Y+12+(H-24)*(v/100);pdf.line(X+26,yy,X+W-12,yy,C.line,.5);pdf.text(`${v}%`,X+2,yy-2,7,C.muted)});const [vx,vy,vw,vh]=data.vb;data.lines.forEach((pts,i)=>{if(pts.length<2)return;const col=i===0?C.green:C.red;for(let k=1;k<pts.length;k++){const a=pts[k-1],b=pts[k],x1=X+26+(a[0]-vx)/vw*(W-38),y1=Y+12+(1-(a[1]-vy)/vh)*(H-24),x2=X+26+(b[0]-vx)/vw*(W-38),y2=Y+12+(1-(b[1]-vy)/vh)*(H-24);pdf.line(x1,y1,x2,y2,col,1.8)}});pdf.text('Groen: ons team    Rood: tegenstander',X+30,Y+4,7,C.muted);pdf.y=Y-16}
function playersPage(pdf,p){pdf.addPage();header(pdf,'Spelersanalyse & box score',`${p.team_name||'Team'} - POTM, sterke punten en speelstatistieken`);const rows=[...(p.players||[])].sort((a,b)=>num(b.rating)-num(a.rating));const potm=rows[0];if(potm){pdf.rect(36,pdf.y-64,523,64,C.navy);pdf.text('PLAYER OF THE MATCH (POTM)',48,pdf.y-17,9,'#9fc9e3',true);pdf.text(`#${potm.number??'-'} ${potm.display_name||potm.name}`,48,pdf.y-39,17,C.white,true);pdf.text(`${potm.rating}/100 - betrouwbaarheid ${potm.ratingReliability||'laag'}`,355,pdf.y-39,9,C.white,true);pdf.y-=82}pdf.text('Spelersranking',36,pdf.y,12,C.navy,true);pdf.y-=16;rows.slice(0,10).forEach((r,i)=>{pdf.rect(36,pdf.y-20,523,23,i%2?'#f7fbff':C.white,C.line);pdf.text(`${i+1}. #${r.number??'-'} ${r.display_name||r.name}`,43,pdf.y-8,9,C.text,true);pdf.text(`${r.rating}/100`,300,pdf.y-8,9,C.purple,true);const rel=r.relationships||{},a=r.actions||{};pdf.text(`min ${num(r.play)} | balverlies ${num(a.ball_loss)} | balwinst ${num(a.ball_recovery)+num(a.interception)} | pass ${rel.passReliability==='low'?'—':pct(rel.passCompletionPct)} | duel ${pct(rel.duelWinPct)}`,357,pdf.y-8,7,C.muted,false,58);pdf.y-=24});pdf.y-=6;boxScore(pdf,rows)}
function boxScore(pdf,rows){pdf.ensure(80);pdf.text('Box score / speelstatistieken',36,pdf.y,12,C.navy,true);pdf.y-=17;const cols=[['Speler',130],['Min',30],['Rat',30],['G',22],['A',22],['P+',28],['P-',28],['BV',28],['BW',28],['DW',28],['DV',28],['S',25],['OD',25]],x0=36;let x=x0;cols.forEach(([h,w])=>{pdf.rect(x,pdf.y-17,w,18,C.navy);pdf.text(h,x+3,pdf.y-7,7,C.white,true);x+=w});pdf.y-=18;rows.forEach((r,i)=>{if(pdf.y<52){pdf.addPage();header(pdf,'Box score - vervolg','ClubMatch Cloud');pdf.y-=4}const a=r.actions||{},rel=r.relationships||{},vals=[`#${r.number??'-'} ${r.display_name||r.name}`,num(r.play),num(r.rating),num(r.goals),num(r.assists),num(rel.passCompleted),num(rel.badPass),num(a.ball_loss),num(a.ball_recovery)+num(a.interception),num(a.duel_won),num(a.duel_lost),num(a.shot),num(a.shot_on_target)];x=x0;cols.forEach(([h,w],j)=>{pdf.rect(x,pdf.y-15,w,16,i%2?'#f7fbff':C.white,C.line);pdf.text(vals[j],x+3,pdf.y-6,j===0?7:6.5,C.text,j===0,w<40?5:22);x+=w});pdf.y-=16});pdf.y-=10}
function intelligencePage(pdf){const mi=doc.getElementById('v11MatchIntelligence');if(!mi)return;pdf.addPage();header(pdf,'Wedstrijdintelligentie','Wissel-/formatie-impact, coaching en volgende opstelling');chart(pdf);const impacts=[...mi.querySelectorAll('.mi11Impact>div')].slice(0,8);if(impacts.length){pdf.text('Impact van wissels en formatie',36,pdf.y,12,C.navy,true);pdf.y-=16;impacts.forEach(el=>{pdf.ensure(46);const tone=el.classList.contains('positief')?C.green:el.classList.contains('negatief')?C.red:C.muted;pdf.rect(36,pdf.y-38,523,40,C.white,C.line);pdf.rect(36,pdf.y-38,5,40,tone);pdf.wrap(el.textContent,48,pdf.y-10,500,7.5,C.text,false,10,3);pdf.y-=43})}const advice=mi.querySelector('.mi11Panel:nth-of-type(2)')||[...mi.querySelectorAll('.mi11Panel')].find(x=>x.textContent.includes('Voorstel volgende opstelling'));if(advice){pdf.ensure(120);pdf.text('Voorstel volgende opstelling',36,pdf.y,12,C.navy,true);pdf.y-=15;pdf.wrap(advice.textContent,36,pdf.y,523,8,C.text,false,11,9);pdf.y-=105}}
function terminology(pdf){pdf.ensure(58);pdf.rect(36,pdf.y-46,523,48,'#fff7df','#ead09a');pdf.text('Terminologie',44,pdf.y-13,9,C.amber,true);pdf.wrap('Team-balbezit = tijdspercentage van het team. Persoonlijke bezitmomenten = aantal possession_start-events van een speler. Balbehoud = 100 - turnover van die speler. Dit zijn verschillende KPI’s.',44,pdf.y-25,505,7.5,C.text,false,10,3);pdf.y-=58}
function buildPdfBytes(state=latest){if(!state)throw new Error('Dashboarddata ontbreekt');const p=state.teamPerformance||{},pdf=new PdfDoc();pdf.addPage();const scope=p.scope||{},title=scope.type==='match'?`${p.team_name||'Team'} - ${scope.opponent||'wedstrijd'}`:`${p.team_name||'Team'} - dashboard`;header(pdf,title,`${scope.match_date||''} ${scope.type==='match'?`- ${scope.score_for??0}-${scope.score_against??0}`:`- ${p.matches||0} wedstrijden`}`);scoreCards(pdf,p);terminology(pdf);halfBlock(pdf,state);componentTable(pdf,p);formulaBlock(pdf,p,'Samenspel');formulaBlock(pdf,p,'Team Performance');playersPage(pdf,p);intelligencePage(pdf);return pdf.bytes()}
function filename(){const p=latest?.teamPerformance||{},scope=p.scope||{},base=`ClubMatch_${p.team_name||'Team'}_${scope.type==='match'?(scope.match_date||'wedstrijd'):'dashboard'}`;return clean(base).replace(/[^A-Za-z0-9_-]+/g,'_')+'.pdf'}
function download(){if(busy)return null;busy=true;try{const bytes=buildPdfBytes(latest),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=doc.createElement('a');a.href=url;a.download=filename();doc.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);return {ok:true,bytes:bytes.length,filename:filename()}}finally{busy=false}}
function attach(state=latest){if(state)latest=state;const top=doc.querySelector('#v08PerformanceAnalysis .pi10Top')||doc.querySelector('#v08PerformanceAnalysis .cmiTop');if(!top)return false;let b=doc.getElementById('v10DashboardPdfBtn');if(!b){b=doc.createElement('button');b.id='v10DashboardPdfBtn';b.type='button';b.style.cssText='border:0;border-radius:10px;padding:9px 12px;background:#fff;color:#0d3552;font-weight:900;cursor:pointer;justify-self:end';top.appendChild(b)}b.textContent='⬇ Dashboard PDF';b.title='Download een ontworpen ClubMatch PDF';b.onclick=()=>{try{download()}catch(e){global.alert?.(`PDF kon niet worden gemaakt: ${e.message||e}`)}};return true}
global.addEventListener?.('clubmatch:v08-dashboard-state',e=>{latest=e.detail;setTimeout(()=>attach(e.detail),100)});global.addEventListener?.('clubmatch:v10-performance-rendered',e=>{latest=e.detail;setTimeout(()=>attach(e.detail),20)});
global.ClubMatchV10DashboardPdf=Object.freeze({attach,download,buildPdfBytes,get latest(){return latest}});global.ClubMatchV09DashboardPdf=global.ClubMatchV10DashboardPdf;
})(typeof window!=='undefined'?window:globalThis);
