import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const context={console,globalThis:null,window:null};context.globalThis=context;context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(new URL('./dashboard-controller.js',import.meta.url),'utf8'),context);
let calls=[];
const dashboardData=team=>({team_season_id:team,players:[{player_id:'p1',name:'A',play:'80',bench:'10',goals:'2',assists:'1',rating:'82',ratingReliability:'middel',actionTotal:'12',possessionSeconds:'100'}],matches:[{id:'m1',opponent:'DEM',score_for:'3',score_against:'1',duration:'80',include_in_dashboard:true,can_delete:true}],kpis:{matches:'1',available_matches:'2',play_minutes:'880',bench_minutes:'110',goals:'3',assists:'2',absent:'1',actions:'12',possession_seconds:'100'},rating_model:{version:'cm-100-v1',min:1,max:100}});
const client={async rpc(name,params={}){calls.push({name,params});if(name==='get_my_team_seasons')return {data:[{team_season_id:'ts1',team_name:'O16'},{team_season_id:'ts2',team_name:'O13'}],error:null};if(name==='get_cloud_dashboard')return {data:dashboardData(params.p_team_season_id),error:null};if(name==='set_match_dashboard_inclusion_v08')return {data:{ok:true},error:null};if(name==='delete_match_v08')return {data:{ok:true},error:null};return {data:null,error:new Error(`unexpected ${name}`)}}};
const D=context.ClubMatchV08Dashboard.createDashboardController({client});await D.loadTeams();assert.equal(D.state.teamSeasons.length,2);await D.load('ts1');assert.equal(D.state.dashboard.teamSeasonId,'ts1');assert.equal(D.state.dashboard.kpis.available_matches,2);assert.equal(D.state.dashboard.players[0].rating,82);assert.equal(D.state.dashboard.players[0].ratingReliability,'middel');assert.equal(D.state.dashboard.matches[0].include_in_dashboard,true);
await D.setMatchIncluded('m1',false);assert.ok(calls.some(c=>c.name==='set_match_dashboard_inclusion_v08'&&c.params.p_match_id==='m1'&&c.params.p_include===false));
await D.deleteMatch('m1','DELETE');assert.ok(calls.some(c=>c.name==='delete_match_v08'&&c.params.p_confirmation==='DELETE'));
await assert.rejects(()=>D.deleteMatch('m1','JA'),/DELETE/);await D.load(null);assert.equal(calls.at(-1).params.p_team_season_id,null);assert.equal(Object.isFrozen(D.state.dashboard),true);
console.log('PASS dashboard-controller: match selection + delete + 1-100 rating normalization');
