/* ClubMatch Cloud v0.8 - scrollable event feed with match/analysis filters */
(function(global){
'use strict';
function createEventFeedUi(doc=global.document){
 if(!doc)return null;let mode='all',controls=null,observer=null,timeline=null,initialScrollDone=false,userReadingOlder=false;
 const analytical=/schot|op doel|bal|pass|duel|onderschep|verover|kans|redding|overtreding|vrije trap|corner|ingooi|buitenspel|penalty|voorzet/i;
 function classify(row){const type=row.dataset.eventType||'';if(type==='player_action'||type==='team_possession')return 'analysis';return analytical.test((row.textContent||'').toLowerCase())?'analysis':'match'}
 function rowsFor(all,type){return type==='all'?all:all.filter(row=>row.dataset.feedType===type)}
 function isNearBottom(){if(!timeline)return true;return timeline.scrollHeight-timeline.scrollTop-timeline.clientHeight<90}
 function scrollNewest(force=false){if(!timeline||(!force&&userReadingOlder))return;timeline.scrollTop=timeline.scrollHeight}
 function apply(){if(!timeline)return;const stick=!initialScrollDone||isNearBottom(),all=[...timeline.querySelectorAll('.v08TimelineRow')];all.forEach(row=>{row.dataset.feedType=classify(row)});const eligible=new Set(rowsFor(all,mode));all.forEach(row=>row.classList.toggle('hidden',!eligible.has(row)));controls?.querySelectorAll('[data-feed]').forEach(b=>{const key=b.dataset.feed,count=rowsFor(all,key).length;b.classList.toggle('active',key===mode);const label=key==='match'?'Wedstrijd':key==='analysis'?'Analyse':'Alles';b.textContent=`${label} (${count})`});if(stick){global.requestAnimationFrame?.(()=>scrollNewest(true))||scrollNewest(true)}initialScrollDone=true}
 function select(next){mode=['match','analysis','all'].includes(next)?next:'all';userReadingOlder=false;apply();return mode}
 function mount(){timeline=doc.getElementById('v08Timeline');const card=timeline?.closest('.card');if(!card)return false;timeline.classList.add('v08EventScroll');timeline.style.maxHeight='360px';timeline.style.overflowY='auto';timeline.style.overscrollBehavior='contain';timeline.style.scrollbarWidth='thin';if(!controls){controls=doc.createElement('div');controls.className='controls';controls.style.marginBottom='8px';controls.innerHTML='<button type="button" class="secondary" data-feed="all">Alles</button><button type="button" class="secondary" data-feed="analysis">Analyse</button><button type="button" class="secondary" data-feed="match">Wedstrijd</button>';const heading=card.querySelector('h2');heading?.after(controls);const hint=doc.createElement('div');hint.className='muted';hint.style.marginBottom='7px';hint.textContent='snelle analistacties direct zichtbaar. Scroll omhoog voor oudere gebeurtenissen. Filters veranderen alleen de weergave; niets wordt uit de historie verwijderd.';controls.after(hint);controls.querySelectorAll('[data-feed]').forEach(b=>b.onclick=()=>select(b.dataset.feed));timeline.addEventListener('scroll',()=>{userReadingOlder=!isNearBottom()},{passive:true})}card.querySelectorAll('button').forEach(button=>{if(/^Toon oudere gebeurtenissen/.test(button.textContent||''))button.remove()});if(!observer){observer=new MutationObserver(()=>{const stick=isNearBottom();if(stick)userReadingOlder=false;apply()});observer.observe(timeline,{childList:true,subtree:true})}apply();return true}
 setTimeout(mount,0);return Object.freeze({mount,apply,select,get mode(){return mode}})
}
global.ClubMatchV08EventFeed={createEventFeedUi};
function boot(){let tries=0;const timer=global.setInterval(()=>{tries++;const ui=createEventFeedUi(global.document);if(ui?.mount?.()||tries>100)global.clearInterval(timer)},50)}
if(global.document?.readyState==='loading')global.document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(typeof window!=='undefined'?window:globalThis);
