import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const listeners=new Map();const runtime={activeMatchId:null,starts:[],async start(id){this.activeMatchId=id;this.starts.push(id);return{id}}};
const appPanel={classList:{contains:name=>false}};const anchor={after(){}};const document={readyState:'complete',getElementById(id){if(id==='appPanel')return appPanel;if(id==='v08Integrity')return anchor;return null},createElement(){return{style:{},setAttribute(){},isConnected:true,textContent:''}}};
const client={auth:{async getSession(){return{data:{session:{access_token:'jwt'}}}}},async rpc(name,params){if(name==='get_match_snapshot')return{data:{match:{id:params.p_match_id,status:'live'},state:{}}};if(name==='get_late_arrival_candidates_v08')return{data:[]};throw new Error(name)}};
const context={console,globalThis:null,window:null,document,performance:{now:(()=>{let n=100;return()=>n+=25})()},MutationObserver:class{observe(){}},CustomEvent:class{constructor(type,init){this.type=type;this.detail=init?.detail}},ClubMatchV08CloudClient:{createClient(){return client}},ClubMatchV08MatchSelection:{createMatchSelection(){return{recalled(){return'm1'},clear(){}}}},addEventListener(type,fn){const a=listeners.get(type)||[];a.push(fn);listeners.set(type,a)},dispatchEvent(event){for(const fn of listeners.get(event.type)||[])fn(event)},Promise,setTimeout,clearTimeout};context.globalThis=context;context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('./fast-resume-v08.js',import.meta.url),'utf8'),context);
const api=context.ClubMatchV08FastResume;assert.equal(api.resumableStatus('live'),true);assert.equal(api.resumableStatus('halftime'),true);assert.equal(api.resumableStatus('draft'),false);assert.equal(api.resumableStatus('finished'),false);
context.dispatchEvent(new context.CustomEvent('clubmatch:v08-runtime-ready',{detail:{runtime}}));await Promise.resolve();await Promise.resolve();await new Promise(resolve=>setTimeout(resolve,0));assert.deepEqual(runtime.starts,['m1'],'Fast Resume moet remembered live match direct starten zodra beveiligde app zichtbaar is');assert.equal(api.state.done,true);assert.equal(api.state.lastMs>=0,true);
const source=fs.readFileSync(new URL('./fast-resume-v08.js',import.meta.url),'utf8');assert.match(source,/get_match_snapshot/);assert.match(source,/runtime\.start\(matchId\)/);assert.match(source,/appVisible\(\)/);assert.match(source,/Fast Resume · live wedstrijd hersteld/);assert.doesNotMatch(source,/\.rpc\s*=/,'Fast Resume mag Supabase rpc niet overschrijven');
console.log('PASS fast-resume: secured app visibility + remembered confirmed snapshot + runtime first + no rpc monkeypatch');
