import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=f=>fs.readFileSync(new URL(`./${f}`,import.meta.url),'utf8');
const html=read('index.html');
const roadmap=read('roadmap-ux-v08.js');
const fast=read('fast-resume-v08.js');
const playerUi=read('player-action-ui.js');
const device=read('device-security-ux-v08.js');
const analystUndo=read('analyst-correction-v08.js');
const mgmtVisibility=read('management-visibility.js');
const mgmtController=read('management-controller.js');
const smart=read('smart-registration-v08.js');
const liveField=read('analyst-live-input-v08.js');
const liveWorkspace=read('live-match-workspace-v08.js');
const analystPolish=read('live-analyst-polish-v08.js');
const eventFeed=read('event-feed-ui.js');
const dashboardTiles=read('dashboard-player-tiles-v08.js');
const prep=read('preparation-controller.js');
const stabilize=read('v08-stabilization.js');

assert.match(html,/build 20260829\.0245/);
for(const asset of ['cloud-client.js','realtime-native.js','roadmap-ux-v08.js','smart-registration-v08.js','live-match-workspace-v08.js','analyst-live-input-v08.js','live-analyst-polish-v08.js','event-feed-ui.js','analyst-correction-v08.js','dashboard-player-tiles-v08.js','device-security-ux-v08.js','app.js'])assert.match(html,new RegExp(`${asset.replaceAll('.','\\.')}\\?v=20260829\\.0245`));
assert.match(html,/id="authPanel" class="card hidden"/);
assert.ok([...html.matchAll(/<script\s+src="[^"]+"([^>]*)>/g)].every(m=>/\bdefer\b/.test(m[1])),'alle browsermodules moeten defer laden');
assert.ok(html.indexOf('cloud-client.js')<html.indexOf('realtime-native.js')&&html.indexOf('live-match-workspace-v08.js')<html.indexOf('analyst-live-input-v08.js')&&html.indexOf('analyst-live-input-v08.js')<html.indexOf('live-analyst-polish-v08.js')&&html.indexOf('dashboard-ui.js')<html.indexOf('dashboard-player-tiles-v08.js')&&html.indexOf('dashboard-player-tiles-v08.js')<html.indexOf('app.js'),'browsermodule volgorde onjuist');
assert.doesNotMatch(html,/action-field-controller\.js\?v=/);assert.doesNotMatch(html,/action-field-ui\.js\?v=/);

assert.match(roadmap,/__sharedBrowserClient/);assert.match(roadmap,/registry\.has/);assert.doesNotMatch(roadmap,/MutationObserver/,'uitgefaseerd Actieveld mag geen permanente observer houden');assert.doesNotMatch(roadmap,/get_my_team_seasons| get_my_open_matches/,'shared-client guard mag geen startup-RPC warmen');
assert.doesNotMatch(fast,/createClient\(/);assert.doesNotMatch(fast,/runtime\.start\(/);assert.match(fast,/clubmatch:v08-confirmed/);
assert.match(device,/probePromise/);assert.match(device,/clearSessionCheckStatus/);assert.match(device,/__ClubMatchShellBoot\?\.build/);assert.doesNotMatch(device,/MutationObserver/,'sessiediagnostiek mag de hele app-DOM niet observeren');
assert.match(playerUi,/lastStructureKey/);assert.match(playerUi,/structureKey===lastStructureKey/);assert.match(playerUi,/setInterval\(updatePossessionClocks,1000\)/);assert.doesNotMatch(playerUi,/setInterval\(renderPossessionBar/);assert.match(playerUi,/Categorieën/);assert.match(playerUi,/A–Z/);
assert.doesNotMatch(mgmtVisibility,/setInterval/);assert.doesNotMatch(mgmtVisibility,/loadAll\(/);assert.match(mgmtVisibility,/if\(inFlight\)return inFlight/);assert.match(mgmtController,/function singleFlight/);
assert.match(analystUndo,/undo_last_analyst_input_v08/);assert.match(smart,/record_analyst_goal_v08/);assert.match(smart,/assistCandidate/);
assert.match(liveField,/MAX_TRAIL=31/);assert.match(liveField,/goalModal/);assert.match(liveField,/v08LiveActionFieldHost/);assert.doesNotMatch(liveField,/MutationObserver/);assert.doesNotMatch(liveField,/setInterval/);
assert.match(liveWorkspace,/v08LiveMatchWorkspace/);assert.match(liveWorkspace,/v08FormationFlow/);assert.match(liveWorkspace,/rightCol\.appendChild\(eventsCard\)/);assert.match(liveWorkspace,/tileZone\.appendChild\(fieldCard\)/);assert.doesNotMatch(liveWorkspace,/setInterval/);
assert.match(analystPolish,/set_opponent_formation_v08/);assert.match(analystPolish,/Actiezone:/);assert.match(analystPolish,/data-primary-goal="against"/);assert.match(analystPolish,/p_action:'offside'/);
assert.match(eventFeed,/overflowY='auto'/);assert.doesNotMatch(eventFeed,/visibleLimit/);
assert.match(dashboardTiles,/dashPlayerTiles/);assert.match(dashboardTiles,/source\.click\(\)/);assert.match(prep,/save_lineup_favorite_v08/);assert.match(prep,/applyFavorite/);
assert.doesNotMatch(stabilize,/client\.rpc\s*=/);assert.doesNotMatch(stabilize,/Actieve wedstrijd veilig hervatten vanuit Cloud/);
console.log('PASS live-ux-fixes: build 0245 analyst usability + opponent formation + event scroll + prior stability');
