import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const context={console,globalThis:null,window:null,fetch:null};context.globalThis=context;context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('./management-controller.js',import.meta.url),'utf8'),context);
const calls=[];let created=0;const admin=(id='ts1',team='O16-1')=>({team_season_id:id,club_id:'c1',club_name:'Club',team_id:'t1',team_name:team,season_name:'2026/2027',can_manage:true,players:[]});const client={session:{access_token:'jwt-test'},async rpc(name,params={}){calls.push({name,params});if(name==='get_my_team_seasons')return {data:[{team_season_id:'ts1',club_id:'c1',club_name:'Club',team_name:'O16-1',season_name:'2026/2027'}],error:null};if(name==='get_management_context_v08')return {data:{can_create_club:true,clubs:[{club_id:'c1',club_name:'Club',can_manage:true}]},error:null};if(name==='get_user_admin_v08')return {data:{is_platform_admin:true,can_manage_users:true,clubs:[{club_id:'c1',club_name:'Club'}],memberships:[{user_id:'u1',club_id:'c1',email:'viewer@test.nl',role:'viewer',status:'active'}]},error:null};if(name==='set_club_membership_v08')return {data:{ok:true},error:null};if(name==='get_team_admin_v08')return {data:admin(params.p_team_season_id),error:null};if(name==='create_team_season_v08'){created++;return {data:admin(created===1?'ts2':'ts3',params.p_team_name),error:null}}if(name==='upsert_team_player_v08')return {data:{...admin('ts2','O16-2'),players:[{player_id:'p1',full_name:params.p_full_name,preferred_positions:params.p_preferred_positions}]},error:null};if(name==='update_team_season_v08')return {data:admin('ts2',params.p_team_name),error:null};return {data:null,error:new Error(`unexpected ${name}`)}}};
let inviteRequest=null;const fetchMock=async(url,options)=>{inviteRequest={url,options,body:JSON.parse(options.body)};return {ok:true,status:200,async json(){return {ok:true,invited:true,email:inviteRequest.body.email}}}};
const M=context.ClubMatchV08Management.createManagementController({client,fetch:fetchMock});await M.loadAll();assert.equal(M.state.context.can_create_club,true);assert.equal(M.state.userAdmin.is_platform_admin,true);assert.equal(M.state.userAdmin.can_manage_users,true);
await M.inviteUser({email:'gerson@example.nl',clubId:'c1',role:'viewer'});assert.match(inviteRequest.url,/clubmatch-user-invite$/);assert.equal(inviteRequest.body.role,'viewer');assert.equal(inviteRequest.options.headers.Authorization,'Bearer jwt-test');
await M.setMembership({userId:'u1',clubId:'c1',role:'trainer',status:'active'});assert.ok(calls.some(x=>x.name==='set_club_membership_v08'&&x.params.p_role==='trainer'));
await M.createTeamSeason({clubId:'c1',newClub:false,teamName:'O16-2',seasonName:'2026/2027'});let c=calls.find(x=>x.name==='create_team_season_v08');assert.equal(c.params.p_team_name,'O16-2');assert.equal(M.state.teamSeasonId,'ts2');await M.addPlayer({fullName:'Nieuwe Speler',shirtNumber:16,preferredPositions:'RW, ST'});const p=calls.find(x=>x.name==='upsert_team_player_v08');assert.deepEqual(Array.from(p.params.p_preferred_positions),['RW','ST']);await M.createTeamSeason({newClub:true,clubName:'Andere Club',teamName:'O16-1',seasonName:'2026/2027'});c=calls.filter(x=>x.name==='create_team_season_v08').at(-1);assert.equal(c.params.p_club_name,'Andere Club');
console.log('PASS management-controller: superuser + viewer invite/roles + O16-2 + players + new club');
