/* ClubMatch Cloud v0.8 - standalone masterdata management UI */
(function(global){
'use strict';
const SUPABASE_URL='https://fnbqyogbamufytcabfzm.supabase.co';
const SUPABASE_KEY='sb_publishable_skGPpngOQ_1OpEbreV2kXA__2OL_Mbp';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function createManagementUi(options={}){
  const doc=options.document||global.document,controller=options.controller,run=options.run||async(label,fn)=>{try{return await fn()}catch(error){global.alert?.(`${label} mislukt: ${error.message||error}`);throw error}};if(!doc||!controller)throw new Error('Document en beheercontroller zijn verplicht');let panel=null,installed=false;
  function ensureStyles(){if(doc.getElementById('v08ManagementStyles'))return;const s=doc.createElement('style');s.id='v08ManagementStyles';s.textContent='.mgmtGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mgmtPlayers{overflow:auto;margin-top:9px}.mgmtPlayers table{width:100%;border-collapse:collapse;min-width:1080px}.mgmtPlayers th{font-size:10px;text-align:left;background:#f8f4fc;position:sticky;top:0}.mgmtPlayers td,.mgmtPlayers th{padding:6px;border-top:1px solid #eee}.mgmtPlayers input{padding:6px}.mgmtReadOnly{padding:8px 10px;background:#fff8e9;border:1px solid #ead09a;border-radius:10px;color:#6c5325;font-size:11px;margin:8px 0}.mgmtNew{border:1px dashed #bca3d2;border-radius:12px;padding:9px;margin-top:12px;background:#fcfaff}.mgmtTag{display:inline-block;padding:2px 6px;border-radius:999px;background:#eee;font-size:9px}.mgmtTag.on{background:#eaf7ee;color:#237a43}@media(max-width:800px){.mgmtGrid{grid-template-columns:1fr}}';doc.head.appendChild(s)}
  function ensureMounted(){if(panel)return panel;ensureStyles();const app=doc.getElementById('appPanel');if(!app)throw new Error('Appscherm ontbreekt');panel=doc.createElement('section');panel.id='v08Management';panel.className='card hidden';app.firstElementChild?.after(panel);return panel}
  function teamOptions(state){return '<option value="">— kies team/seizoen —</option>'+state.teamSeasons.map(t=>`<option value="${esc(t.team_season_id)}"${state.teamSeasonId===t.team_season_id?' selected':''}>${esc(t.club_name)} · ${esc(t.team_name)} · ${esc(t.season_name)}</option>`).join('')}
  function playerRow(p,can){return `<tr data-mgmt-player="${esc(p.player_id)}"><td><input data-m="fullName" value="${esc(p.full_name)}" ${can?'':'disabled'}></td><td><input data-m="displayName" value="${esc(p.display_name||'')}" ${can?'':'disabled'}></td><td><input data-m="shirtNumber" type="number" min="0" max="99" value="${esc(p.shirt_number??'')}" ${can?'':'disabled'}></td><td><input data-m="preferredPositions" value="${esc((p.preferred_positions||[]).join(', '))}" placeholder="RW, ST" ${can?'':'disabled'}></td><td><input data-m="shirtSize" value="${esc(p.shirt_size||'')}" placeholder="S/M/L" ${can?'':'disabled'}></td><td><label><input data-m="teamActive" type="checkbox" ${p.team_active?'checked':''} ${can?'':'disabled'}> actief</label></td><td>${can?'<button type="button" class="secondary" data-save-player data-v08-action>Opslaan</button>':`<span class="mgmtTag ${p.team_active?'on':''}">${p.team_active?'actief':'inactief'}</span>`}</td></tr>`}
  function render(state){const root=ensureMounted(),a=state.admin,can=!!a?.can_manage;root.innerHTML=`<div class="sectionTitle"><div><h2 style="margin-bottom:3px">Beheer</h2><div class="muted">Centrale clubmasterdata: team, seizoen, spelers, rugnummers en voorkeursposities.</div></div><div class="controls"><button id="mgmtRefresh" class="secondary" data-v08-action>↻ Beheer</button><button id="mgmtClose" class="secondary" data-v08-action>Sluiten</button></div></div><label style="display:block;margin-top:9px">Team / seizoen<select id="mgmtTeam">${teamOptions(state)}</select></label>${!a?'<div class="muted" style="margin-top:8px">Kies een team/seizoen.</div>':`${can?'':'<div class="mgmtReadOnly"><b>Alleen-lezen.</b> Alleen platform-admin of club-admin kan team-, seizoen- en spelersmasterdata wijzigen.</div>'}<div class="mgmtGrid"><label>Teamnaam<input id="mgmtTeamName" value="${esc(a.team_name)}" ${can?'':'disabled'}></label><label>Seizoennaam<input id="mgmtSeasonName" value="${esc(a.season_name)}" ${can?'':'disabled'}></label><label>Weergavenaam team/seizoen<input id="mgmtDisplayName" value="${esc(a.team_season_display_name||'')}" ${can?'':'disabled'}></label></div>${can?'<div class="controls" style="margin-top:8px"><button id="mgmtSaveNames" data-v08-action>Team / seizoen opslaan</button></div>':''}<h3 style="margin-top:14px">Spelers</h3><div class="mgmtPlayers"><table><thead><tr><th>Naam</th><th>Roepnaam</th><th>Nr.</th><th>Voorkeursposities</th><th>Maat</th><th>Status</th><th></th></tr></thead><tbody>${(a.players||[]).map(p=>playerRow(p,can)).join('')}</tbody></table></div>${can?'<div class="mgmtNew"><b>+ Nieuwe speler</b><div class="mgmtGrid" style="margin-top:7px"><label>Naam<input id="mgmtNewName"></label><label>Roepnaam<input id="mgmtNewDisplay"></label><label>Rugnummer<input id="mgmtNewNumber" type="number" min="0" max="99"></label><label>Voorkeursposities<input id="mgmtNewPositions" placeholder="RW, ST"></label><label>Shirtmaat<input id="mgmtNewSize" placeholder="S/M/L"></label></div><div class="controls" style="margin-top:7px"><button id="mgmtAddPlayer" data-v08-action>Speler toevoegen</button></div></div>':''}`}`;bind(root,state);root.classList.remove('hidden');return root}
  function rowValue(row,key){const el=row.querySelector(`[data-m="${key}"]`);return el?.type==='checkbox'?!!el.checked:el?.value||''}
  function notifyMasterdataChanged(){doc.getElementById('refreshMatchesBtn')?.click()}
  function bind(root,state){root.querySelector('#mgmtTeam').onchange=e=>e.target.value&&run('Beheer laden',()=>controller.load(e.target.value));root.querySelector('#mgmtRefresh').onclick=()=>run('Beheer verversen',async()=>{await controller.loadTeamSeasons();if(controller.state.teamSeasonId)await controller.load(controller.state.teamSeasonId)});root.querySelector('#mgmtClose').onclick=hide;root.querySelector('#mgmtSaveNames')?.addEventListener('click',()=>run('Team/seizoen opslaan',async()=>{await controller.updateNames({teamName:root.querySelector('#mgmtTeamName').value,seasonName:root.querySelector('#mgmtSeasonName').value,displayName:root.querySelector('#mgmtDisplayName').value});notifyMasterdataChanged()}));root.querySelectorAll('[data-save-player]').forEach(btn=>btn.onclick=()=>{const row=btn.closest('[data-mgmt-player]');return run('Speler opslaan',async()=>{await controller.savePlayer({playerId:row.dataset.mgmtPlayer,fullName:rowValue(row,'fullName'),displayName:rowValue(row,'displayName'),shirtNumber:rowValue(row,'shirtNumber'),preferredPositions:rowValue(row,'preferredPositions'),shirtSize:rowValue(row,'shirtSize'),teamActive:rowValue(row,'teamActive')});notifyMasterdataChanged()})});root.querySelector('#mgmtAddPlayer')?.addEventListener('click',()=>run('Speler toevoegen',async()=>{await controller.addPlayer({fullName:root.querySelector('#mgmtNewName').value,displayName:root.querySelector('#mgmtNewDisplay').value,shirtNumber:root.querySelector('#mgmtNewNumber').value,preferredPositions:root.querySelector('#mgmtNewPositions').value,shirtSize:root.querySelector('#mgmtNewSize').value,teamActive:true});notifyMasterdataChanged()}))}
  async function show(){const root=ensureMounted();await controller.loadTeamSeasons();render(controller.state);root.classList.remove('hidden')}
  function hide(){ensureMounted().classList.add('hidden')}
  function installButton(){if(installed)return true;const refresh=doc.getElementById('refreshMatchesBtn'),parent=refresh?.parentElement;if(!parent)return false;installed=true;const button=doc.createElement('button');button.id='managementBtn';button.className='secondary';button.dataset.v08Action='';button.textContent='Beheer';button.onclick=()=>run('Beheer openen',show);parent.insertBefore(button,refresh);return true}
  return Object.freeze({show,hide,render,installButton,get visible(){return panel&&!panel.classList.contains('hidden')}})
}
function installStandalone(){if(!global.ClubMatchV08CloudClient?.createClient||!global.ClubMatchV08Management?.createManagementController)return;const client=global.ClubMatchV08CloudClient.createClient(SUPABASE_URL,SUPABASE_KEY),controller=global.ClubMatchV08Management.createManagementController({client}),ui=createManagementUi({document:global.document,controller});let tries=0;const timer=global.setInterval(()=>{tries++;if(ui.installButton()||tries>200)global.clearInterval(timer)},50);global.ClubMatchV08ManagementApp={client,controller,ui}}
global.ClubMatchV08ManagementUi={createManagementUi,installStandalone};
global.document?.addEventListener?.('DOMContentLoaded',installStandalone);
})(typeof window!=='undefined'?window:globalThis);
