import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');
const renderer=fs.readFileSync(new URL('./dom-renderer.js',import.meta.url),'utf8');
const ui=fs.readFileSync(new URL('./player-action-ui.js',import.meta.url),'utf8');
assert.ok(app.includes("createPlayerActionController({client,runtime})"),'speleracties moeten dezelfde Cloud-client en live-runtime gebruiken');
assert.ok(app.includes("playerActions?.setSnapshot?.(snapshot)"),'speleracties mogen alleen uit een bevestigde snapshot werken');
assert.ok(app.includes("createPlayerActionUi({document,controller:playerActions,runtime,run})"),'snelle actie-UI moet aan confirmed controller en goal-runtime gekoppeld zijn');
assert.ok(renderer.includes('data-player-action-open'),'tegels/veld moeten één compacte snelle actie-ingang bieden');
assert.ok(!renderer.includes('Balverlies</button><button'),'alle eventtypes mogen niet permanent over iedere spelerkaart worden uitgesmeerd');
assert.ok(ui.includes('data-team-possession="for"')&&ui.includes('data-team-possession="against"'),'team-balbezit moet onafhankelijk van speler snel te starten zijn');
assert.ok(ui.includes('Doelpunt gemaakt')&&ui.includes('paGoalAssist')&&ui.includes('paGoalType'),'snelle speleractie moet doelpunt + assist + type ondersteunen');
assert.ok(ui.includes('Overtreding / vrije trap tegen')&&ui.includes('Overtreding mee / vrije trap mee'),'vrije trap context moet in snelle acties herkenbaar zijn');
console.log('PASS player-action-integration: compact actions + team possession + quick goal/free-kick context');
