import fs from 'node:fs';
import assert from 'node:assert/strict';
const app=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');
const renderer=fs.readFileSync(new URL('./dom-renderer.js',import.meta.url),'utf8');
const ui=fs.readFileSync(new URL('./player-action-ui.js',import.meta.url),'utf8');
const controller=fs.readFileSync(new URL('./player-action-controller.js',import.meta.url),'utf8');
assert.ok(app.includes("createPlayerActionController({client,runtime})"),'speleracties moeten dezelfde Cloud-client en live-runtime gebruiken');
assert.ok(app.includes("playerActions?.setSnapshot?.(snapshot)"),'speleracties mogen alleen uit een bevestigde snapshot werken');
assert.ok(renderer.includes('data-player-action-open'),'tegels/veld moeten één compacte snelle actie-ingang bieden');
assert.ok(ui.includes('data-team-possession="for"')&&ui.includes('data-team-possession="against"'),'team-balbezit moet snel te starten zijn');
assert.ok(ui.includes('v08StopAllPossession')&&ui.includes('Alles bezit stoppen'),'één knop moet speler- en teambezit samen kunnen stoppen');
assert.ok(ui.includes('analystReceiveBall')&&ui.includes('analystLoseBall')&&ui.includes('analystRecord'),'analistmodus moet expliciet de inference-API gebruiken, zonder proxy-afhankelijkheid');
assert.ok(ui.includes("if(mode==='analyst'){const active=controller.currentPossession?.();if(active)await controller.stopPossession()"),'analistmodus uitzetten moet actief spelerbezit sluiten');
assert.ok(controller.includes("record_analyst_ball_flow_v08")&&controller.includes("stop_all_possession_v08"),'controller moet atomaire analistflow en alles-stop gebruiken');
assert.ok(ui.includes('Doelpunt gemaakt')&&ui.includes('paGoalAssist')&&ui.includes('paGoalType'),'snelle speleractie moet doelpunt + assist + type ondersteunen');
console.log('PASS player-action-integration: explicit analyst flow + unified possession stop + compact quick actions');
