/* ClubMatch Cloud v0.8 - visuele wedstrijdvoorbereiding */
(function(global){
'use strict';
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const EXTRA_POSITIONS=['GK','RB','RWB','RCB','CB','LCB','LB','LWB','RDM','LDM','DM','RM','RCM','CM','LCM','LM','AM','RW','LW','RST','ST','LST'];
function createPreparationUi(options={}){
  const doc=options.document||global.document,controller=options.controller;if(!doc||!controller)throw new Error('Document en wedstrijdvoorbereiding zijn verplicht');
  let panel=null,lastState=null;
  function ensureStyles(){if(doc.getElementById('v08PrepStyles'))return;const s=doc.createElement('style');s.id='v08PrepStyles';s.textContent=`
    .prepWorkspace{display:grid;grid-template-columns:minmax(340px,1.05fr) minmax(330px,.95fr);gap:12px;margin-top:10px}.prepPitch{background:repeating-linear-gradient(90deg,#438b57 0 10%,#4b985f 10% 20%);border:3px solid #fff;border-radius:16px;padding:12px;min-height:520px;display:flex;flex-direction:column;justify-content:space-around;box-shadow:inset 0 0 0 1px rgba(255,255,255,.45)}.prepPitchRow{display:flex;justify-content:space-around;gap:7px}.prepSlot{width:min(118px,30%);min-height:77px;background:rgba(255,255,255,.95);border-radius:11px;padding:7px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,.12)}.prepSlot.empty{opacity:.65}.prepSlotPos{font-size:10px;color:#4b2672;font-weight:900}.prepSlotName{font-size:12px;font-weight:900;margin-top:3px}.prepSlotMeta{font-size:9px;color:#6b5877;margin-top:3px}.prepBench{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.prepBenchCard{border:1px solid #dfd0ec;border-radius:10px;padding:7px;background:#faf7fd}.prepQuick{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.prepQuick button{font-size:11px}.prepRoster{overflow:auto;max-height:610px;border:1px solid #eadff5;border-radius:12px}.prepRoster table{width:100%;border-collapse:collapse;min-width:650px}.prepRoster th{position:sticky;top:0;background:#f8f4fc;z-index:1;padding:7px 5px;font-size:10px}.prepRoster td{padding:7px 5px}.prepRoster tr{border-top:1px solid #eee}.prepSummary{margin:10px 0;padding:9px;border-radius:10px;background:#f8f4fc}.prepSummary.ok{background:#eaf7ee;border:1px solid #9ed5ad}.prepSummary.bad{background:#fff4f4;border:1px solid #e5b0b0}.prepSectionLabel{font-size:11px;font-weight:900;color:#4b2672;text-transform:uppercase;letter-spacing:.04em;margin:9px 0 6px}@media(max-width:900px){.prepWorkspace{grid-template-columns:1fr}.prepPitch{min-height:480px}}@media(max-width:520px){.prepBench{grid-template-columns:1fr}.prepSlot{width:31%;padding:5px}.prepSlotName{font-size:10px}}
  `;doc.head.appendChild(s)}
  function ensureMounted(){if(panel)return panel;ensureStyles();const app=doc.getElementById('appPanel');if(!app)throw new Error('ClubMatch-appscherm ontbreekt');panel=doc.createElement('section');panel.id='v08Preparation';panel.className='card';const first=app.firstElementChild;first?.after(panel);if(!first)app.prepend(panel);return panel}
  function teamOptions(state){return '<option value="">— team/seizoen —</option>'+state.teamSeasons.map(t=>`<option value="${esc(t.team_season_id)}"${t.team_season_id===state.meta.teamSeasonId?' selected':''}>${esc(t.club_name)} · ${esc(t.team_name)} · ${esc(t.season_name)}</option>`).join('')}
  function formationOptions(state){const formations=global.ClubMatchV08Formation?.FORMATIONS||{'4-3-3':[]};return Object.keys(formations).map(code=>`<option value="${esc(code)}"${code===state.meta.formationCode?' selected':''}>${esc(code)}</option>`).join('')}
  function positionOptions(player){const formationSlots=global.ClubMatchV08Formation?.getFormation?.(lastState?.meta?.formationCode)?.slots||[];const values=[...new Set([...formationSlots,...EXTRA_POSITIONS,...(player.preferredPositions||[]).map(String),player.position].filter(Boolean))];return '<option value="">— positie —</option>'+values.map(p=>`<option value="${esc(p)}"${p===player.position?' selected':''}>${esc(p)}</option>`).join('')}
  function playerLabel(player){return `#${esc(player.shirtNumber??'—')} ${esc(player.name)}`}
  function pitchHtml(state){
    if(!state.setup)return '<div class="muted">Kies eerst een team/seizoen.</div>';
    const rows=global.ClubMatchV08Formation?.pitchRows?.(state.meta.formationCode)||[];const byPos=new Map(state.players.filter(p=>p.starter&&p.position).map(p=>[String(p.position),p]));
    const known=new Set(rows.flat()),unplaced=state.players.filter(p=>p.starter&&!known.has(String(p.position||'')));
    const html=rows.map(row=>`<div class="prepPitchRow">${row.map(slot=>{const p=byPos.get(slot);return p?`<div class="prepSlot" data-player-id="${esc(p.playerId)}"><div class="prepSlotPos">${esc(slot)}</div><div class="prepSlotName">${playerLabel(p)}</div><div class="prepSlotMeta">${esc((p.preferredPositions||[]).join(' · ')||'geen voorkeur')}</div></div>`:`<div class="prepSlot empty"><div class="prepSlotPos">${esc(slot)}</div><div class="prepSlotName">Vrij</div><div class="prepSlotMeta">Kies/plaats speler</div></div>`}).join('')}</div>`).join('');
    return `<div class="prepPitch">${html}</div>${unplaced.length?`<div class="muted" style="margin-top:6px">Niet in deze formatie geplaatst: ${unplaced.map(playerLabel).join(', ')}</div>`:''}`;
  }
  function benchHtml(state){const bench=state.players.filter(p=>p.selected&&!p.starter);if(!bench.length)return '<div class="muted">Nog geen geselecteerde reserves.</div>';return `<div class="prepBench">${bench.map(p=>`<div class="prepBenchCard"><b>${playerLabel(p)}</b><div class="muted">${esc((p.preferredPositions||[]).join(' · ')||'geen voorkeurspositie')}</div></div>`).join('')}</div>`}
  function rosterHtml(state){
    if(!state.setup)return '<div class="muted">Kies eerst een team/seizoen.</div>';
    const players=[...state.players].sort((a,b)=>(Number(a.shirtNumber)||999)-(Number(b.shirtNumber)||999)||String(a.name).localeCompare(String(b.name)));
    return `<div class="prepRoster"><table><thead><tr><th style="text-align:left">Speler</th><th>Aanwezig</th><th>Selectie</th><th>Basis</th><th style="text-align:left">Positie</th></tr></thead><tbody>${players.map(player=>`<tr data-prep-player="${esc(player.playerId)}"><td><b>${playerLabel(player)}</b><div class="muted">Voorkeur: ${esc((player.preferredPositions||[]).join(' · ')||'—')}</div></td><td style="text-align:center"><input type="checkbox" data-prep-field="attendance" ${player.attendance?'checked':''}></td><td style="text-align:center"><input type="checkbox" data-prep-field="selected" ${player.selected?'checked':''} ${!player.attendance?'disabled':''}></td><td style="text-align:center"><input type="checkbox" data-prep-field="starter" ${player.starter?'checked':''} ${!player.attendance?'disabled':''}></td><td><select data-prep-field="position" ${!player.starter?'disabled':''}>${positionOptions(player)}</select></td></tr>`).join('')}</tbody></table></div>`;
  }
  function render(state){
    lastState=state;const root=ensureMounted();const v=state.validation||{errors:[],selectedCount:0,starterCount:0,benchCount:0,attendanceCount:0,ok:false};const ready=v.ok&&!state.dirty&&!!state.meta.matchId;
    root.innerHTML=`<div class="sectionTitle"><div><h2 style="margin-bottom:3px">Wedstrijdvoorbereiding</h2><div class="muted">Selectie, basisopstelling, formatie en bank uit de Cloud. Refresh mag niets verliezen.</div></div><div class="controls"><button id="prepNewBtn" class="secondary" data-v08-action>Nieuwe voorbereiding</button><button id="prepCloseBtn" class="secondary" data-v08-action>Sluiten</button></div></div>
      <div class="grid3" style="margin-top:10px"><label>Team / seizoen<select id="prepTeam">${teamOptions(state)}</select></label><label>Tegenstander<input id="prepOpponent" value="${esc(state.meta.opponentName)}" placeholder="Tegenstander"></label><label>Formatie<select id="prepFormation">${formationOptions(state)}</select></label></div>
      <div class="grid3" style="margin-top:8px"><label>Datum<input id="prepDate" type="date" value="${esc(state.meta.matchDate)}"></label><label>Tijd<input id="prepTime" type="time" value="${esc(state.meta.scheduledTime)}"></label><label>Wedstrijdduur (min)<input id="prepDuration" type="number" min="1" max="180" value="${esc(state.meta.officialDurationMinutes)}"></label></div>
      <div class="prepQuick"><button id="prepSelectPresentBtn" class="secondary" data-v08-action>✓ Alle aanwezigen selecteren</button><button id="prepFirstElevenBtn" class="secondary" data-v08-action>11 eerste geselecteerden → basis</button><button id="prepApplyFormationBtn" class="secondary" data-v08-action>⚽ Formatie toepassen</button><button id="prepClearSelectionBtn" class="secondary" data-v08-action>Selectie leegmaken</button></div>
      <div class="prepSummary ${v.ok?'ok':'bad'}"><b>${v.attendanceCount} aanwezig · ${v.selectedCount} selectie · ${v.starterCount} basis · ${v.benchCount} bank</b> · ${state.dirty?'nog niet opgeslagen':'opgeslagen'}${state.meta.matchId?` · wedstrijd ${esc(state.meta.matchId).slice(0,8)}…`:''}<div class="muted" style="margin-top:4px">${v.errors.length?esc(v.errors.join(' · ')):'✓ Basisopstelling voldoet aan alle 11-spelers- en positiecontroles.'}</div></div>
      <div class="prepWorkspace"><div><div class="prepSectionLabel">Visuele basisopstelling · ${esc(state.meta.formationCode)}</div>${pitchHtml(state)}<div class="prepSectionLabel">Bank / reserves</div>${benchHtml(state)}</div><div><div class="prepSectionLabel">Spelers en selectie</div>${rosterHtml(state)}</div></div>
      <div class="controls" style="margin-top:12px"><button id="prepSaveBtn" data-v08-action ${!state.setup?'disabled':''}>Voorbereiding opslaan</button><button id="prepStartBtn" data-v08-action ${!ready?'disabled':''}>▶ Wedstrijd starten</button></div>`;
    bind(root);root.classList.remove('hidden');return root;
  }
  function syncMeta(){controller.setMeta({opponentName:doc.getElementById('prepOpponent')?.value||'',formationCode:doc.getElementById('prepFormation')?.value||'4-3-3',matchDate:doc.getElementById('prepDate')?.value||'',scheduledTime:doc.getElementById('prepTime')?.value||'',officialDurationMinutes:Number(doc.getElementById('prepDuration')?.value||80)})}
  function bind(root){
    const team=root.querySelector('#prepTeam');if(team)team.onchange=()=>options.run?.('Team laden',()=>controller.loadTeam(team.value));
    ['prepOpponent','prepDate','prepTime','prepDuration'].forEach(id=>{const el=root.querySelector(`#${id}`);if(el)el.onchange=syncMeta});
    const formation=root.querySelector('#prepFormation');if(formation)formation.onchange=()=>controller.setMeta({formationCode:formation.value});
    root.querySelectorAll('[data-prep-player]').forEach(row=>row.querySelectorAll('[data-prep-field]').forEach(input=>input.onchange=()=>{const field=input.dataset.prepField,value=field==='position'?input.value:!!input.checked;controller.patchPlayer(row.dataset.prepPlayer,{[field]:value})}));
    root.querySelector('#prepSelectPresentBtn')?.addEventListener('click',()=>controller.selectAllPresent());
    root.querySelector('#prepClearSelectionBtn')?.addEventListener('click',()=>controller.clearSelection());
    root.querySelector('#prepFirstElevenBtn')?.addEventListener('click',()=>options.run?.('Basisspelers kiezen',()=>controller.makeSelectedStarters()));
    root.querySelector('#prepApplyFormationBtn')?.addEventListener('click',()=>options.run?.('Formatie toepassen',()=>controller.applyFormation(root.querySelector('#prepFormation')?.value||'4-3-3')));
    root.querySelector('#prepSaveBtn')?.addEventListener('click',()=>options.run?.('Voorbereiding opslaan',async()=>{syncMeta();const snap=await controller.save();await options.onSaved?.(snap);return snap}));
    root.querySelector('#prepStartBtn')?.addEventListener('click',()=>options.run?.('Wedstrijd starten',async()=>{const id=controller.state.meta.matchId;const result=await controller.start();await options.onStarted?.(id,result);return result}));
    root.querySelector('#prepNewBtn')?.addEventListener('click',()=>{controller.clear();render(controller.state)});root.querySelector('#prepCloseBtn')?.addEventListener('click',hide);
  }
  function hide(){ensureMounted().classList.add('hidden')}
  function show(){ensureMounted().classList.remove('hidden');if(lastState)render(lastState)}
  async function openExisting(match){const state=await controller.openExisting(match);return render(state)}
  function renderCurrent(){return render(controller.state)}
  return Object.freeze({render,renderCurrent,openExisting,show,hide,get visible(){return panel&&!panel.classList.contains('hidden')}});
}
global.ClubMatchV08PreparationUi={createPreparationUi};
})(typeof window!=='undefined'?window:globalThis);
