import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const sent=[],sockets=[];let authCallback=null;
class FakeWebSocket{constructor(url){this.url=url;this.readyState=0;sockets.push(this)}send(value){sent.push(JSON.parse(value))}close(){this.readyState=3}open(){this.readyState=1;this.onopen?.()}message(value){this.onmessage?.({data:JSON.stringify(value)})}}
const base=Object.freeze({rpc(){},session:{access_token:'jwt-1'},auth:{onAuthStateChange(cb){authCallback=cb;return{data:{subscription:{unsubscribe(){}}}}}}});
const context={console,globalThis:null,window:null,WebSocket:FakeWebSocket,setInterval:()=>1,clearInterval(){},setTimeout:()=>1,clearTimeout(){},ClubMatchV08CloudClient:{createClient(){return base}}};context.globalThis=context;context.window=context;context.supabase={createClient:context.ClubMatchV08CloudClient.createClient};vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('./realtime-bridge.js',import.meta.url),'utf8'),context);
const client=context.ClubMatchV08CloudClient.createClient('https://fnbqyogbamufytcabfzm.supabase.co','sb_publishable_test');assert.equal(typeof client.channel,'function');assert.equal(typeof client.removeChannel,'function');
let status='',payload=null;const channel=client.channel('clubmatch-v08-m1').on('postgres_changes',{event:'UPDATE',schema:'public',table:'match_state',filter:'match_id=eq.m1'},p=>payload=p).on('postgres_changes',{event:'INSERT',schema:'public',table:'match_events',filter:'match_id=eq.m1'},p=>payload=p).subscribe(s=>{status=s});
assert.match(sockets[0].url,/\/realtime\/v1\/websocket\?/);assert.match(sockets[0].url,/vsn=1\.0\.0/);sockets[0].open();const join=sent.find(m=>m.event==='phx_join');assert.ok(join);assert.equal(join.payload.access_token,'jwt-1');assert.equal(join.payload.config.postgres_changes.length,2);assert.equal(join.payload.config.postgres_changes[0].filter,'match_id=eq.m1');
sockets[0].message({topic:'realtime:clubmatch-v08-m1',event:'phx_reply',ref:join.ref,join_ref:join.ref,payload:{status:'ok',response:{}}});assert.equal(status,'SUBSCRIBED');
sockets[0].message({topic:'realtime:clubmatch-v08-m1',event:'postgres_changes',payload:{data:{schema:'public',table:'match_events',type:'INSERT',record:{match_id:'m1',id:'e1'},old_record:{}}}});assert.equal(payload.table,'match_events');assert.equal(payload.eventType,'INSERT');
authCallback?.('TOKEN_REFRESHED',{access_token:'jwt-2'});assert.equal(sent.some(m=>m.event==='access_token'&&m.payload.access_token==='jwt-2'),true);await channel.unsubscribe();
console.log('PASS realtime-bridge: authenticated Phoenix join + match-scoped postgres changes + token refresh');
