/* ClubMatch Cloud v0.8 - downloadable color infographic PDF/PNG + Excel export */
(function(global){
'use strict';
const doc=global.document;
const W=1240,H=1754,PDF_W=595.28,PDF_H=841.89;
const C={purple:'#4b2672',purple2:'#6f42c1',lav:'#eadff5',lav2:'#f7f2fb',green:'#237a43',greenBg:'#e9f7ee',red:'#983263',redBg:'#fff0f3',blue:'#1976d2',blueBg:'#eef7ff',amber:'#d39118',amberBg:'#fff6df',ink:'#241633',muted:'#6b5877',line:'#e4d4f2',white:'#ffffff'};
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function pct(v){return v===null||v===undefined||Number.isNaN(Number(v))?'—':`${Math.round(Number(v)*10)/10}%`}
function fmtSeconds(v){const s=Math.max(0,Math.round(num(v)));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function safe(v){return String(v??'').replace(/[\r\n]+/g,' ').trim()}
function teamName(state){const id=state?.dashboard?.teamSeasonId,t=(state?.teamSeasons||[]).find(x=>x.team_season_id===id)||state?.teamSeasons?.[0]||{};return `${t.club_name||'ClubMatch'} · ${t.team_name||'Team'}${t.season_name?` · ${t.season_name}`:''}`}
function rounded(ctx,x,y,w,h,r,fill,stroke=null,lw=1){ctx.beginPath();ctx.roundRect(x,y,w,h,r);if(fill){ctx.fillStyle=fill;ctx.fill()}if(stroke){ctx.lineWidth=lw;ctx.strokeStyle=stroke;ctx.stroke()}}
function text(ctx,value,x,y,size=24,weight=400,color=C.ink,align='left',maxWidth){ctx.save();ctx.font=`${weight} ${size}px Arial, Helvetica, sans-serif`;ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='alphabetic';ctx.fillText(safe(value),x,y,maxWidth);ctx.restore()}
function wrap(ctx,value,x,y,maxWidth,lineHeight,size=23,weight=400,color=C.ink,maxLines=4){const words=safe(value).split(/\s+/),lines=[];let line='';ctx.save();ctx.font=`${weight} ${size}px Arial, Helvetica, sans-serif`;for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=word;if(lines.length>=maxLines-1)break}else line=next}if(line&&lines.length<maxLines)lines.push(line);lines.forEach((l,i)=>text(ctx,l,x,y+i*lineHeight,size,weight,color));ctx.restore();return y+lines.length*lineHeight}
function metric(ctx,x,y,w,h,label,value,sub='',tone='purple'){const map={purple:[C.lav2,C.purple],green:[C.greenBg,C.green],red:[C.redBg,C.red],blue:[C.blueBg,C.blue],amber:[C.amberBg,C.amber]},[bg,fg]=map[tone]||map.purple;rounded(ctx,x,y,w,h,22,bg,C.line,2);text(ctx,value,x+w/2,y+55,34,900,fg,'center',w-20);text(ctx,label,x+w/2,y+88,17,800,C.ink,'center',w-20);if(sub)text(ctx,sub,x+w/2,y+112,14,400,C.muted,'center',w-18)}
function bar(ctx,x,y,w,p,label,value){const q=Math.max(0,Math.min(100,num(p)));rounded(ctx,x,y,w,18,9,'#ece7f0');rounded(ctx,x,y,w*q/100,18,9,C.purple2);text(ctx,label,x,y-10,15,700,C.muted);text(ctx,value,x+w,y-10,15,900,C.purple,'right')}
function createCanvas(){const c=doc.createElement('canvas');c.width=W;c.height=H;return c}
function header(ctx,title,subtitle,pageLabel=''){ctx.fillStyle=C.white;ctx.fillRect(0,0,W,H);ctx.fillStyle=C.purple;ctx.fillRect(0,0,W,188);text(ctx,'CLUBMATCH CLOUD',64,62,20,900,'#d9c7ec');text(ctx,title,64,119,45,900,C.white);text(ctx,subtitle,64,158,19,400,'#eee4f8', 'left',900);if(pageLabel)text(ctx,pageLabel,W-64,62,18,900,C.white,'right')}
function footer(ctx,state){ctx.strokeStyle=C.line;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(64,H-72);ctx.lineTo(W-64,H-72);ctx.stroke();text(ctx,`${teamName(state)} · gegenereerd ${new Date().toLocaleString('nl-NL')}`,64,H-38,14,400,C.muted);text(ctx,'KPI-percentages zijn gebaseerd op geregistreerde wedstrijdacties.',W-64,H-38,14,400,C.muted,'right')}
function teamCanvas(state){const c=createCanvas(),ctx=c.getContext('2d'),p=state?.teamPerformance||{},d=state?.dashboard||{},k=d.kpis||{},pass=p.passes||{},duel=p.duels||{},shot=p.shooting||{},def=p.defending||{},disc=p.discipline||{};header(ctx,'Team KPI Infographic',teamName(state),'TEAM OVERZICHT');
 rounded(ctx,64,222,1112,262,28,C.purple);text(ctx,'TEAM PERFORMANCE',94,270,18,900,'#d9c7ec');text(ctx,p.team_performance_pct==null?'—':`${Math.round(p.team_performance_pct)}%`,94,375,88,900,C.white);text(ctx,'Totale prestatie',94,416,23,800,C.white);wrap(ctx,'Passnauwkeurigheid + balbezit + duels + balcontrole + doelgerichtheid + resultaat.',94,447,480,25,17,400,'#eee4f8',3);ctx.strokeStyle='rgba(255,255,255,.25)';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(610,252);ctx.lineTo(610,454);ctx.stroke();text(ctx,'SAMENSPEL',650,270,18,900,'#d9c7ec');text(ctx,p.teamplay_pct==null?'—':`${Math.round(p.teamplay_pct)}%`,650,375,88,900,C.white);text(ctx,'Hoe goed speelde het team samen?',650,416,23,800,C.white);text(ctx,`Datadekking ${pct(p.data_coverage_pct)}`,650,454,17,700,'#eee4f8');
 const y1=520,mw=260,mh=126,g=24;metric(ctx,64,y1,mw,mh,'Passes aangekomen',pass.completed??0,`${pct(pass.accuracy_pct)} nauwkeurig`,'green');metric(ctx,64+(mw+g),y1,mw,mh,'Foute passes',pass.failed??0,`${pass.attempted??0} pogingen`,'red');metric(ctx,64+2*(mw+g),y1,mw,mh,'Balbezit',pct(p.possession?.pct),`${fmtSeconds(p.possession?.for_seconds)} gemeten`,'blue');metric(ctx,64+3*(mw+g),y1,mw,mh,'Winst-Gelijk-Verlies',`${p.wins??0}-${p.draws??0}-${p.losses??0}`,`${p.matches??0} wedstrijden`,'purple');
 text(ctx,'SAMENSPEL & BALCIRCULATIE',64,705,21,900,C.purple);bar(ctx,64,755,520,pass.accuracy_pct||0,'Passnauwkeurigheid',pct(pass.accuracy_pct));bar(ctx,650,755,526,p.possession?.pct||0,'Balbezit',pct(p.possession?.pct));
 const y2=824;metric(ctx,64,y2,mw,mh,'Duels gewonnen',`${duel.won??0}/${(duel.won??0)+(duel.lost??0)}`,pct(duel.win_pct),'purple');metric(ctx,64+(mw+g),y2,mw,mh,'Schoten op doel',`${shot.on_target??0}/${shot.shots??0}`,pct(shot.on_target_pct),'amber');metric(ctx,64+2*(mw+g),y2,mw,mh,'Balwinst / verlies',`${def.recoveries??0}/${def.losses??0}`,pct(def.recovery_control_pct),'green');metric(ctx,64+3*(mw+g),y2,mw,mh,'Kansen gecreëerd',shot.chances_created??0,'geregistreerd','blue');
 text(ctx,'VERDEDIGING & CONTROLE',64,1008,21,900,C.purple);metric(ctx,64,1036,mw,108,'Onderscheppingen',def.interceptions??0,'','blue');metric(ctx,64+(mw+g),1036,mw,108,'Blokken',def.blocks??0,'','purple');metric(ctx,64+2*(mw+g),1036,mw,108,'Reddingen',def.saves??0,'','green');metric(ctx,64+3*(mw+g),1036,mw,108,'Overtredingen mee/tegen',`${disc.fouls_won??0}/${disc.fouls_committed??0}`,'','amber');
 text(ctx,'TEAMRESULTAAT & OMVANG',64,1202,21,900,C.purple);metric(ctx,64,1230,mw,108,'Goals / Assists',`${k.goals??0}/${k.assists??0}`,'','green');metric(ctx,64+(mw+g),1230,mw,108,'Acties',k.actions??0,'','purple');metric(ctx,64+2*(mw+g),1230,mw,108,'Speelminuten',k.play_minutes??0,'','blue');metric(ctx,64+3*(mw+g),1230,mw,108,'Spelers',d.players?.length??0,'','purple');
 rounded(ctx,64,1380,1112,188,22,C.lav2,C.line,2);text(ctx,'Hoe wordt het cijfer berekend?',88,1422,20,900,C.purple);wrap(ctx,p.formula?.performance||'Team Performance gebruikt pass, bezit, duels, balcontrole, schotkwaliteit en resultaat en herweegt alleen de KPI’s waarvoor data beschikbaar is.',88,1460,1040,26,16,400,C.ink,3);wrap(ctx,p.formula?.teamplay||'Samenspel gebruikt passnauwkeurigheid, balbezit, duelwinst en verhouding balwinst/balverlies.',88,1531,1040,24,15,400,C.muted,2);footer(ctx,state);return c}
function playerCardsCanvas(state,players,pageIndex,totalPages){const c=createCanvas(),ctx=c.getContext('2d');header(ctx,'Spelers KPI Overzicht',teamName(state),`SPELERS ${pageIndex}/${totalPages}`);const startY=225,cols=2,cardW=536,cardH=425,gapX=40,gapY=34;players.forEach((p,i)=>{const col=i%cols,row=Math.floor(i/cols),x=64+col*(cardW+gapX),y=startY+row*(cardH+gapY),r=p.relationships||{},a=p.actions||{};rounded(ctx,x,y,cardW,cardH,25,C.white,C.line,3);ctx.fillStyle=C.purple;ctx.fillRect(x,y,cardW,88);text(ctx,`#${p.number??'—'} ${p.display_name||p.name}`,x+24,y+53,25,900,C.white,'left',380);rounded(ctx,x+420,y+18,90,54,14,C.white);text(ctx,p.rating??'—',x+465,y+56,30,900,C.purple,'center');text(ctx,`Betrouwbaarheid ${p.ratingReliability||'laag'}`,x+24,y+111,14,600,C.muted);metric(ctx,x+24,y+133,150,96,'Speeltijd',`${p.play??0}m`,`${p.playPct??0}%`,'purple');metric(ctx,x+193,y+133,150,96,'Goals / assists',`${p.goals??0}/${p.assists??0}`,'','green');metric(ctx,x+362,y+133,150,96,'Acties',p.actionTotal??0,'','blue');metric(ctx,x+24,y+248,150,96,'Pass',pct(r.passCompletionPct),`${r.passCompleted??0}/${(r.passCompleted??0)+(r.badPass??0)}`,'green');metric(ctx,x+193,y+248,150,96,'Duelwinst',pct(r.duelWinPct),`${r.duelWon??0}/${(r.duelWon??0)+(r.duelLost??0)}`,'purple');metric(ctx,x+362,y+248,150,96,'Op doel',pct(r.shotOnTargetPct),`${r.shotsOnTarget??0}/${r.shots??0}`,'amber');text(ctx,`Balwinst ${a.ball_recovery||0} · onderscheppingen ${a.interception||0} · balverlies ${a.ball_loss||0} · reddingen ${a.save||0}`,x+24,y+388,14,600,C.muted,'left',488)});footer(ctx,state);return c}
function detailedPlayerCanvas(state,p,index,total){const c=createCanvas(),ctx=c.getContext('2d'),r=p.relationships||{},a=p.actions||{},model=state.dashboard?.ratingModel||{},b=global.ClubMatchV08DashboardUi?.ratingBreakdown?.(p,model);header(ctx,`#${p.number??'—'} ${p.display_name||p.name}`,teamName(state),`SPELER ${index}/${total}`);rounded(ctx,64,225,1112,176,26,C.purple);text(ctx,'CLUBMATCH PERFORMANCE RATING',92,267,18,900,'#d9c7ec');text(ctx,p.rating??'—',92,360,78,900,C.white);text(ctx,`Betrouwbaarheid: ${p.ratingReliability||'laag'} · ${p.play??0} speelminuten · ${p.playPct??0}% speeltijd`,260,335,21,700,C.white);if(b)text(ctx,`Basis ${b.base} + ${b.raw.toFixed(2)} punten × ${b.factor.toFixed(2)} = ${b.calculated}/100`,260,370,17,400,'#eee4f8');const metrics=[['Speelminuten',p.play,'purple'],['Goals',p.goals,'green'],['Assists',p.assists,'green'],['Acties',p.actionTotal,'blue'],['Pass goed',r.passCompleted??0,'green'],['Pass fout',r.badPass??0,'red'],['Pass %',pct(r.passCompletionPct),'green'],['Balverlies %',pct(r.ballLossPerReceivedPct),'red'],['Duel %',pct(r.duelWinPct),'purple'],['Op doel %',pct(r.shotOnTargetPct),'amber'],['Balwinst',a.ball_recovery||0,'green'],['Intercepties',a.interception||0,'blue'],['Reddingen',a.save||0,'green'],['Kansen',a.chance_created||0,'amber'],['Bezit',fmtSeconds(p.possessionSeconds),'blue'],['Bezit aandeel',pct(p.possessionShare),'purple']];metrics.forEach((m,i)=>{const col=i%4,row=Math.floor(i/4);metric(ctx,64+col*284,440+row*139,260,116,m[0],m[1],'',m[2])});text(ctx,'ACTIEVERDELING',64,1040,21,900,C.purple);const actionRows=Object.entries(a).filter(([,v])=>num(v)>0).sort((x,y)=>num(y[1])-num(x[1])).slice(0,18);actionRows.forEach(([key,val],i)=>{const col=i%3,row=Math.floor(i/3),x=64+col*380,y=1070+row*62;rounded(ctx,x,y,356,48,12,C.lav2);text(ctx,(global.ClubMatchV08DashboardUi?.ACTION_LABELS?.[key]||key).replaceAll('_',' '),x+15,y+31,14,700,C.ink);text(ctx,val,x+336,y+31,17,900,C.purple,'right')});footer(ctx,state);return c}
async function canvasJpeg(canvas,quality=.92){const blob=await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Canvas kon niet naar JPEG worden omgezet')),'image/jpeg',quality));return new Uint8Array(await blob.arrayBuffer())}
function ascii(str){return new TextEncoder().encode(str)}
function concat(parts){const len=parts.reduce((a,p)=>a+p.length,0),out=new Uint8Array(len);let off=0;parts.forEach(p=>{out.set(p,off);off+=p.length});return out}
function pdfFromJpegs(images){const count=images.length,objects=new Array(3+count*3),kids=[];objects[1]=ascii('<< /Type /Catalog /Pages 2 0 R >>');for(let i=0;i<count;i++){const page=3+i*3,content=4+i*3,image=5+i*3;kids.push(`${page} 0 R`);const stream=`q ${PDF_W} 0 0 ${PDF_H} 0 0 cm /Im1 Do Q`;objects[page]=ascii(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PDF_W} ${PDF_H}] /Resources << /XObject << /Im1 ${image} 0 R >> >> /Contents ${content} 0 R >>`);objects[content]=ascii(`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`);const jpg=images[i];objects[image]=concat([ascii(`<< /Type /XObject /Subtype /Image /Width ${W} /Height ${H} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpg.length} >>\nstream\n`),jpg,ascii('\nendstream')])}objects[2]=ascii(`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${count} >>`);const chunks=[ascii('%PDF-1.4\n%ClubMatch\n')],offsets=[0],max=objects.length-1;let offset=chunks[0].length;for(let i=1;i<=max;i++){offsets[i]=offset;const head=ascii(`${i} 0 obj\n`),tail=ascii('\nendobj\n');chunks.push(head,objects[i],tail);offset+=head.length+objects[i].length+tail.length}const xrefOffset=offset;let xref=`xref\n0 ${max+1}\n0000000000 65535 f \n`;for(let i=1;i<=max;i++)xref+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;const trailer=`trailer\n<< /Size ${max+1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;chunks.push(ascii(xref+trailer));return concat(chunks)}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=doc.createElement('a');a.href=url;a.download=filename;doc.body.appendChild(a);a.click();a.remove();global.setTimeout(()=>URL.revokeObjectURL(url),2000)}
async function downloadTeamInfographicPdf(state){const canvases=[teamCanvas(state)],players=[...(state?.dashboard?.players||[])].sort((a,b)=>num(b.rating)-num(a.rating)),perPage=6,total=Math.max(1,Math.ceil(players.length/perPage));for(let i=0;i<players.length;i+=perPage)canvases.push(playerCardsCanvas(state,players.slice(i,i+perPage),Math.floor(i/perPage)+1,total));const jpgs=[];for(const c of canvases)jpgs.push(await canvasJpeg(c));const pdf=pdfFromJpegs(jpgs);downloadBlob(new Blob([pdf],{type:'application/pdf'}),`ClubMatch_Team_Infographic_${new Date().toISOString().slice(0,10)}.pdf`);return {ok:true,pages:canvases.length,bytes:pdf.length}}
async function downloadTeamInfographicPng(state){const c=teamCanvas(state),blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('PNG kon niet worden gemaakt')),'image/png'));downloadBlob(blob,`ClubMatch_Team_Infographic_${new Date().toISOString().slice(0,10)}.png`);return {ok:true,bytes:blob.size}}
async function downloadPlayerInfographicPdf(state){const players=[...(state?.dashboard?.players||[])].sort((a,b)=>num(b.rating)-num(a.rating));if(!players.length)throw new Error('Geen spelers in dashboard');const jpgs=[];for(let i=0;i<players.length;i++)jpgs.push(await canvasJpeg(detailedPlayerCanvas(state,players[i],i+1,players.length),.9));const pdf=pdfFromJpegs(jpgs);downloadBlob(new Blob([pdf],{type:'application/pdf'}),`ClubMatch_Spelers_Infographic_${new Date().toISOString().slice(0,10)}.pdf`);return {ok:true,pages:players.length,bytes:pdf.length}}
function xml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function cell(value,type='String'){return `<Cell><Data ss:Type="${type}">${xml(value)}</Data></Cell>`}
function row(values){return `<Row>${values.map(v=>cell(v,typeof v==='number'?'Number':'String')).join('')}</Row>`}
function worksheet(name,rows){return `<Worksheet ss:Name="${xml(name)}"><Table>${rows.map(row).join('')}</Table></Worksheet>`}
function buildExcel(state){const p=state?.teamPerformance||{},d=state?.dashboard||{},players=d.players||[],matches=d.matches||[],teamRows=[['KPI','Waarde'],['Team Performance %',num(p.team_performance_pct)],['Samenspel %',num(p.teamplay_pct)],['Datadekking %',num(p.data_coverage_pct)],['Wedstrijden',num(p.matches)],['Winst',num(p.wins)],['Gelijk',num(p.draws)],['Verlies',num(p.losses)],['Passes goed',num(p.passes?.completed)],['Passes fout',num(p.passes?.failed)],['Passes totaal',num(p.passes?.attempted)],['Passnauwkeurigheid %',num(p.passes?.accuracy_pct)],['Balbezit %',num(p.possession?.pct)],['Duels gewonnen',num(p.duels?.won)],['Duels verloren',num(p.duels?.lost)],['Duelwinst %',num(p.duels?.win_pct)],['Schoten',num(p.shooting?.shots)],['Schoten op doel',num(p.shooting?.on_target)],['Op doel %',num(p.shooting?.on_target_pct)],['Kansen',num(p.shooting?.chances_created)],['Balwinst',num(p.defending?.recoveries)],['Balverlies',num(p.defending?.losses)],['Onderscheppingen',num(p.defending?.interceptions)],['Blokken',num(p.defending?.blocks)],['Reddingen',num(p.defending?.saves)]];const playerRows=[['Nummer','Speler','Rating','Betrouwbaarheid','Speelminuten','Speel%','Goals','Assists','Acties','Bezit sec','Bezit %','Pass goed','Pass fout','Pass %','Balverlies/ontvangen %','Duelwinst %','Schot op doel %','Reddingen','Veroveringen','Onderscheppingen'],...players.map(x=>[x.number??'',x.display_name||x.name,x.rating,x.ratingReliability||'',num(x.play),num(x.playPct),num(x.goals),num(x.assists),num(x.actionTotal),num(x.possessionSeconds),num(x.possessionShare),num(x.relationships?.passCompleted),num(x.relationships?.badPass),num(x.relationships?.passCompletionPct),num(x.relationships?.ballLossPerReceivedPct),num(x.relationships?.duelWinPct),num(x.relationships?.shotOnTargetPct),num(x.actions?.save),num(x.actions?.ball_recovery),num(x.actions?.interception)])];const matchRows=[['Datum','Team','Tegenstander','Score voor','Score tegen','Duur','Formatie','Acties','Bezit sec','Bezit %','Mee'],...matches.map(m=>[m.match_date||'',m.team||'',m.opponent||'',num(m.score_for),num(m.score_against),num(m.duration),m.formation||'',num(m.action_count),num(m.possession_seconds),num(m.possession_pct),m.include_in_dashboard!==false?'Ja':'Nee'])];return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${worksheet('Team KPI',teamRows)}${worksheet('Spelers',playerRows)}${worksheet('Wedstrijden',matchRows)}</Workbook>`}
function exportExcel(state){const xml=buildExcel(state);downloadBlob(new Blob([xml],{type:'application/vnd.ms-excel'}),`ClubMatch_KPI_${new Date().toISOString().slice(0,10)}.xls`);return {ok:true,bytes:xml.length}}
function printTeam(state){return downloadTeamInfographicPdf(state)}
function printPlayers(state){return downloadPlayerInfographicPdf(state)}
global.ClubMatchV08Reports=Object.freeze({downloadTeamInfographicPdf,downloadTeamInfographicPng,downloadPlayerInfographicPdf,printTeam,printPlayers,buildExcel,exportExcel,teamCanvas,playerCardsCanvas,detailedPlayerCanvas,pdfFromJpegs});
})(typeof window!=='undefined'?window:globalThis);
