/* ClubMatch Cloud v0.8 - A4 infographic + Excel report export service */
(function(global){
'use strict';
const doc=global.document;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function xml(v){return esc(v)}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
function pct(v){return v===null||v===undefined||Number.isNaN(Number(v))?'—':`${Math.round(Number(v)*10)/10}%`}
function fmtSeconds(v){const s=Math.max(0,Math.round(num(v)));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
const LABELS={save:'Reddingen',shot:'Schoten',shot_on_target:'Op doel',block:'Blokken',ball_recovery:'Bal veroverd',interception:'Onderscheppingen',ball_loss:'Balverlies',bad_pass:'Foute passes',duel_won:'Duels +',duel_lost:'Duels −',foul_won:'Overtredingen mee',foul_committed:'Overtredingen tegen',chance_created:'Kansen',possession_control:'Balcontrole'};
function teamStats(state={}){const d=state.dashboard||{},players=d.players||[],matches=(d.matches||[]).filter(m=>m.include_in_dashboard!==false),actions={};players.forEach(p=>Object.entries(p.actions||{}).forEach(([k,v])=>{actions[k]=(actions[k]||0)+num(v)}));const wins=matches.filter(m=>num(m.score_for)>num(m.score_against)).length,draws=matches.filter(m=>num(m.score_for)===num(m.score_against)).length,losses=matches.filter(m=>num(m.score_for)<num(m.score_against)).length,goalsFor=matches.reduce((a,m)=>a+num(m.score_for),0),goalsAgainst=matches.reduce((a,m)=>a+num(m.score_against),0),avgRating=players.length?Math.round(players.reduce((a,p)=>a+num(p.rating),0)/players.length):0;return {matches:matches.length,wins,draws,losses,goalsFor,goalsAgainst,goalDiff:goalsFor-goalsAgainst,avgRating,actions,players,teamPossession:state.teamPossession?.total||{},kpis:d.kpis||{},ratingModel:d.ratingModel||{}}}
function playerKpis(p={}){const r=p.relationships||{},a=p.actions||{};return [{label:'Rating',value:p.rating??'—'},{label:'Speelminuten',value:num(p.play)},{label:'Speel%',value:pct(p.playPct)},{label:'Goals',value:num(p.goals)},{label:'Assists',value:num(p.assists)},{label:'Acties',value:num(p.actionTotal)},{label:'Spelerbezit',value:fmtSeconds(p.possessionSeconds)},{label:'Bezit-aandeel',value:pct(p.possessionShare)},{label:'Pass voltooid',value:pct(r.passCompletionPct)},{label:'Balverlies / ontvangen',value:pct(r.ballLossPerReceivedPct)},{label:'Duelwinst',value:pct(r.duelWinPct)},{label:'Schot op doel',value:pct(r.shotOnTargetPct)},{label:'Veroveringen',value:num(a.ball_recovery)},{label:'Onderscheppingen',value:num(a.interception)},{label:'Reddingen',value:num(a.save)},{label:'Overtredingen mee',value:num(a.foul_won)}]}
function baseCss(){return `@page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;margin:0;color:#241633;background:#fff}.page{page-break-after:always;min-height:277mm;padding:3mm}.page:last-child{page-break-after:auto}.brand{font-size:10px;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:#6f42c1}.title{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:4px solid #6f42c1;padding-bottom:6px;margin-bottom:8px}h1{font-size:24px;margin:3px 0;color:#4b2672}h2{font-size:16px;color:#4b2672;margin:10px 0 5px}.muted{font-size:10px;color:#6b5877}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.kpi{border:1px solid #e4d4f2;border-radius:10px;padding:8px;background:#faf7fd;text-align:center}.kpi b{display:block;font-size:20px;color:#4b2672}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.box{border:1px solid #e4d4f2;border-radius:10px;padding:8px}.bar{height:14px;border-radius:99px;background:linear-gradient(90deg,#237a43 var(--own),#983263 var(--own));margin:6px 0}.actionGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.action{display:flex;justify-content:space-between;gap:5px;padding:5px 7px;border-radius:7px;background:#f3edf9;font-size:10px}.playerHeader{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.rating{font-size:38px;font-weight:900;color:#fff;background:#4b2672;border-radius:14px;padding:8px 14px;text-align:center}.rating small{display:block;font-size:8px}.playerKpis{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.playerKpi{border:1px solid #e4d4f2;border-radius:8px;padding:6px;text-align:center;font-size:9px}.playerKpi b{display:block;font-size:15px;color:#4b2672}.ratingParts{display:grid;grid-template-columns:1fr 1fr;gap:4px}.ratingPart{display:flex;justify-content:space-between;border-bottom:1px solid #eee;padding:3px;font-size:9px}.footer{margin-top:8px;border-top:1px solid #eee;padding-top:5px;font-size:8px;color:#6b5877}@media print{button{display:none!important}}`}
function ratingBreakdown(p,model){if(global.ClubMatchV08DashboardUi?.ratingBreakdown)return global.ClubMatchV08DashboardUi.ratingBreakdown(p,model);const weights=model?.weights||{},base=num(model.base||50),norm=num(model.normalizationMinutes||80)||80,minNorm=num(model.minimumNormalizerMinutes||20)||20,parts=[];let raw=0;const add=(k,c)=>{c=num(c);const w=num(weights[k]);if(!c||!w)return;const contribution=c*w;raw+=contribution;parts.push({key:k,label:LABELS[k]||k,count:c,weight:w,contribution})};add('goal',p.goals);add('assist',p.assists);Object.keys(p.actions||{}).forEach(k=>add(k,p.actions[k]));const factor=norm/Math.max(num(p.play),minNorm);return {base,raw,factor,calculated:Math.max(1,Math.min(100,Math.round(base+raw*factor))),parts}}
function teamPage(state){const s=teamStats(state),own=s.teamPossession?.for_pct,opp=s.teamPossession?.against_pct,actions=Object.entries(s.actions).filter(([,v])=>num(v)>0).sort((a,b)=>num(b[1])-num(a[1]));return `<section class="page"><div class="title"><div><div class="brand">ClubMatch Cloud · Teamrapport</div><h1>Team infographic</h1><div class="muted">${s.matches} meegenomen wedstrijd${s.matches===1?'':'en'} · gegenereerd ${new Date().toLocaleString('nl-NL')}</div></div><div class="rating">${s.avgRating}<small>gem. rating</small></div></div><div class="kpis"><div class="kpi"><b>${s.matches}</b>Wedstrijden</div><div class="kpi"><b>${s.wins}-${s.draws}-${s.losses}</b>W-G-V</div><div class="kpi"><b>${s.goalsFor}-${s.goalsAgainst}</b>Goals</div><div class="kpi"><b>${s.goalDiff>0?'+':''}${s.goalDiff}</b>Doelsaldo</div><div class="kpi"><b>${num(s.kpis.actions)}</b>Acties</div><div class="kpi"><b>${num(s.kpis.play_minutes)}</b>Speelminuten</div><div class="kpi"><b>${num(s.kpis.bench_minutes)}</b>Bankminuten</div><div class="kpi"><b>${s.players.length}</b>Spelers</div></div><div class="grid2"><div class="box"><h2>Balbezit</h2>${own!==null&&own!==undefined?`<div class="bar" style="--own:${num(own)}%"></div><b>Ons ${pct(own)}</b> · Tegen ${pct(opp)}<div class="muted">Ons ${fmtSeconds(s.teamPossession.for_seconds)} · Tegen ${fmtSeconds(s.teamPossession.against_seconds)}</div>`:'<div class="muted">Geen team-balbezit gemeten.</div>'}</div><div class="box"><h2>Ratingmodel</h2><b>${esc(s.ratingModel.version||'cm-100-v1')}</b><div class="muted">Basis ${s.ratingModel.base??50} · normalisatie ${s.ratingModel.normalizationMinutes??80} minuten · minimum ${s.ratingModel.minimumNormalizerMinutes??20}. Rating is gebaseerd op daadwerkelijk gelogde acties.</div></div></div><h2>Actieverdeling team · absolute aantallen</h2><div class="actionGrid">${actions.map(([k,v])=>`<div class="action"><span>${esc(LABELS[k]||k)}</span><b>${num(v)}</b></div>`).join('')||'<div class="muted">Geen acties.</div>'}</div><h2>Spelers kernoverzicht</h2><div class="actionGrid">${[...s.players].sort((a,b)=>num(b.rating)-num(a.rating)).map(p=>`<div class="action"><span>#${esc(p.number??'—')} ${esc(p.display_name||p.name)}</span><b>${p.rating} · ${p.play}m · ${p.playPct}%</b></div>`).join('')}</div><div class="footer">Absolute waarden en percentages zijn gebaseerd op geselecteerde dashboardwedstrijden. Percentages zijn alleen betrouwbaar voor acties die daadwerkelijk consequent zijn geregistreerd.</div></section>`}
function playerPage(p,model,index,total){const r=ratingBreakdown(p,model),kpis=playerKpis(p),actions=Object.entries(p.actions||{}).filter(([,v])=>num(v)>0).sort((a,b)=>num(b[1])-num(a[1]));return `<section class="page"><div class="title"><div><div class="brand">ClubMatch Cloud · Speler A4 ${index}/${total}</div><h1>#${esc(p.number??'—')} ${esc(p.display_name||p.name)}</h1><div class="muted">${esc(p.team||'')} · betrouwbaarheid rating: ${esc(p.ratingReliability||'laag')}</div></div><div class="rating">${p.rating}<small>ClubMatch rating</small></div></div><div class="playerKpis">${kpis.map(k=>`<div class="playerKpi"><b>${esc(k.value)}</b>${esc(k.label)}</div>`).join('')}</div><h2>Opbouw rating</h2><div class="box"><b>Basis ${r.base} + ${r.raw.toFixed(2)} punten × factor ${r.factor.toFixed(2)} = ${r.calculated}/100</b><div class="ratingParts">${r.parts.map(x=>`<div class="ratingPart"><span>${esc(x.label)} ${x.count} × ${x.weight>0?'+':''}${x.weight}</span><b>${x.contribution>0?'+':''}${x.contribution.toFixed(2)}</b></div>`).join('')||'<div class="muted">Geen gewogen acties.</div>'}</div></div><h2>Acties · absolute aantallen</h2><div class="actionGrid">${actions.map(([k,v])=>`<div class="action"><span>${esc(LABELS[k]||k)}</span><b>${num(v)}</b></div>`).join('')||'<div class="muted">Geen acties.</div>'}</div><div class="footer">Speel%, pass%, balverlies%, duel% en schot-op-doel% zijn relatieve KPI's. De overige waarden zijn absolute aantallen/tijden. Alleen geregistreerde acties kunnen in analyse en rating worden meegenomen.</div></section>`}
function printDocument(title,body){const w=global.open?.('','_blank');if(!w)throw new Error('Pop-up geblokkeerd. Sta pop-ups toe voor de PDF/printweergave.');w.document.open();w.document.write(`<!doctype html><html lang="nl"><head><meta charset="utf-8"><title>${esc(title)}</title><style>${baseCss()}</style></head><body>${body}<script>window.addEventListener('load',()=>setTimeout(()=>window.print(),150));<\/script></body></html>`);w.document.close();return w}
function printTeam(state){return printDocument('ClubMatch Teamrapport',teamPage(state))}
function printPlayers(state){const players=state?.dashboard?.players||[],model=state?.dashboard?.ratingModel||{};if(!players.length)throw new Error('Geen spelers in dashboard');return printDocument('ClubMatch Spelerrapport',players.map((p,i)=>playerPage(p,model,i+1,players.length)).join(''))}
function cell(value,type='String'){return `<Cell><Data ss:Type="${type}">${xml(value)}</Data></Cell>`}
function row(values){return `<Row>${values.map(v=>cell(v,typeof v==='number'?'Number':'String')).join('')}</Row>`}
function worksheet(name,rows){return `<Worksheet ss:Name="${xml(name)}"><Table>${rows.map(row).join('')}</Table></Worksheet>`}
function buildExcel(state){const s=teamStats(state),players=state?.dashboard?.players||[],matches=state?.dashboard?.matches||[];const teamRows=[['KPI','Waarde'],['Wedstrijden',s.matches],['Winst',s.wins],['Gelijk',s.draws],['Verlies',s.losses],['Goals voor',s.goalsFor],['Goals tegen',s.goalsAgainst],['Gem. rating',s.avgRating],['Balbezit ons %',num(s.teamPossession?.for_pct)],['Balbezit tegen %',num(s.teamPossession?.against_pct)],...Object.entries(s.actions).map(([k,v])=>[LABELS[k]||k,num(v)])];const playerRows=[['Nummer','Speler','Rating','Betrouwbaarheid','Speelminuten','Speel%','Goals','Assists','Acties','Bezit sec','Bezit %','Pass %','Balverlies/ontvangen %','Duelwinst %','Schot op doel %','Reddingen','Veroveringen','Onderscheppingen'],...players.map(p=>[p.number??'',p.display_name||p.name,p.rating,p.ratingReliability||'',num(p.play),num(p.playPct),num(p.goals),num(p.assists),num(p.actionTotal),num(p.possessionSeconds),num(p.possessionShare),num(p.relationships?.passCompletionPct),num(p.relationships?.ballLossPerReceivedPct),num(p.relationships?.duelWinPct),num(p.relationships?.shotOnTargetPct),num(p.actions?.save),num(p.actions?.ball_recovery),num(p.actions?.interception)])];const matchRows=[['Datum','Team','Tegenstander','Score voor','Score tegen','Duur','Formatie','Acties','Bezit sec','Bezit %','Mee'],...matches.map(m=>[m.match_date||'',m.team||'',m.opponent||'',num(m.score_for),num(m.score_against),num(m.duration),m.formation||'',num(m.action_count),num(m.possession_seconds),num(m.possession_pct),m.include_in_dashboard!==false?'Ja':'Nee'])];return `<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">${worksheet('Team',teamRows)}${worksheet('Spelers',playerRows)}${worksheet('Wedstrijden',matchRows)}</Workbook>`}
function downloadText(content,filename,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=doc.createElement('a');a.href=url;a.download=filename;doc.body.appendChild(a);a.click();a.remove();global.setTimeout(()=>URL.revokeObjectURL(url),1500)}
function exportExcel(state){const content=buildExcel(state);if(content.length<500)throw new Error('Excel-rapport bevat onverwacht geen data');downloadText(content,`ClubMatch_dashboard_${new Date().toISOString().slice(0,10)}.xls`,'application/vnd.ms-excel;charset=utf-8');return {ok:true,bytes:content.length}}
global.ClubMatchV08Reports=Object.freeze({teamStats,playerKpis,ratingBreakdown,teamPage,playerPage,printTeam,printPlayers,buildExcel,exportExcel});
})(typeof window!=='undefined'?window:globalThis);
