/* ClubMatch Cloud v0.8 - roadmap UX: analyst inference routing + spatial-only action field */
(function(global){
'use strict';
const doc=global.document;
function patchPlayerActionUi(){const api=global.ClubMatchV08PlayerActionUi;if(!api?.createPlayerActionUi||api.__roadmapUx)return;const original=api.createPlayerActionUi.bind(api);global.ClubMatchV08PlayerActionUi={...api,__roadmapUx:true,createPlayerActionUi(options={}){const base=options.controller;if(!base)return original(options);const controller=new Proxy(base,{get(target,prop){if(prop==='receiveBall'&&typeof target.analystReceiveBall==='function')return target.analystReceiveBall.bind(target);if(prop==='loseBall'&&typeof target.analystLoseBall==='function')return target.analystLoseBall.bind(target);const value=target[prop];return typeof value==='function'?value.bind(target):value}});return original({...options,controller})}}}
const SPATIAL=new Set(['pass','progression','switch_play','cross','shot','shot_on_target','chance_created','free_kick','corner','throw_in']);
function simplifyActionField(){const panel=doc?.getElementById('v08ActionField');if(!panel)return;panel.querySelectorAll('[data-af-action]').forEach(btn=>btn.classList.toggle('hidden',!SPATIAL.has(btn.dataset.afAction)));const headings=[...panel.querySelectorAll('h3')];const quickHeading=headings.find(h=>/snelle actie/i.test(h.textContent||''));if(quickHeading)quickHeading.textContent='Actie met locatie';const safe=panel.querySelector('.afSafe');if(safe)safe.innerHTML='<b>Actieveld = locatie en balroute.</b> Algemene acties zoals balverlies, onderschepping, duels en overtredingen registreer je in Snelle registratie. Zo voorkom je dubbele knoppen en dubbele invoer.';const hint=panel.querySelector('.afHint');if(hint)hint.textContent='Sleep/veeg de bal voor de route of tik een speler. Gebruik Snelle registratie voor acties zonder relevante veldlocatie.'}
function boot(){patchPlayerActionUi();simplifyActionField();new MutationObserver(simplifyActionField).observe(doc.body,{childList:true,subtree:true})}
if(doc?.readyState==='loading')doc.addEventListener('DOMContentLoaded',boot);else boot();
})(typeof window!=='undefined'?window:globalThis);
