/* ClubMatch Cloud v0.8 - roadmap UX: safe refresh prefetch, analyst inference + spatial-only action field */
(function(global){
'use strict';
const doc=global.document;
const URL='https://fnbqyogbamufytcabfzm.supabase.co',KEY='sb_publishable_skGPpngOQ_1OpEbreV2kXA__2OL_Mbp';
let warmStartup=()=>Promise.resolve();
function installFastResume(){const api=global.ClubMatchV08CloudClient;if(!api?.createClient)return;const client=api.createClient(URL,KEY);if(client.__v08FastResume){warmStartup=client.__v08FastResumeWarm||warmStartup;return}const originalRpc=client.rpc.bind(client),prefetch=new Map();const key=(name,params)=>`${name}:${JSON.stringify(params||{})}`;function start(name,params={}){const k=key(name,params);if(!prefetch.has(k)){const p=Promise.resolve().then(()=>originalRpc(name,params)).finally(()=>setTimeout(()=>prefetch.delete(k),1500));prefetch.set(k,p)}return prefetch.get(k)}client.rpc=function(name,params){const k=key(name,params);return prefetch.has(k)?prefetch.get(k):originalRpc(name,params)};warmStartup=async()=>{try{const session=(await client.auth.getSession()).data?.session;if(!session)return;await Promise.allSettled([start('get_my_team_seasons'),start('get_my_open_matches')])}catch(error){console.debug('ClubMatch fast-resume prefetch overgeslagen',error)}};Object.defineProperty(client,'__v08FastResume',{value:true});Object.defineProperty(client,'__v08FastResumeWarm',{value:warmStartup})}
function patchPlayerActionUi(){const api=global.ClubMatchV08PlayerActionUi;if(!api?.createPlayerActionUi||api.__roadmapUx)return;const original=api.createPlayerActionUi.bind(api);global.ClubMatchV08PlayerActionUi={...api,__roadmapUx:true,createPlayerActionUi(options={}){const base=options.controller;if(!base)return original(options);const controller=new Proxy(base,{get(target,prop){if(prop==='receiveBall'&&typeof target.analystReceiveBall==='function')return target.analystReceiveBall.bind(target);if(prop==='loseBall'&&typeof target.analystLoseBall==='function')return target.analystLoseBall.bind(target);const value=target[prop];return typeof value==='function'?value.bind(target):value}});return original({...options,controller})}}}
const SPATIAL=new Set(['pass','progression','switch_play','cross','shot','shot_on_target','chance_created','free_kick','corner','throw_in']);
function simplifyActionField(){const panel=doc?.getElementById('v08ActionField');if(!panel)return;panel.querySelectorAll('[data-af-action]').forEach(btn=>btn.classList.toggle('hidden',!SPATIAL.has(btn.dataset.afAction)));const headings=[...panel.querySelectorAll('h3')];const quickHeading=headings.find(h=>/snelle actie/i.test(h.textContent||''));if(quickHeading)quickHeading.textContent='Actie met locatie';const safe=panel.querySelector('.afSafe');if(safe)safe.innerHTML='<b>Actieveld = locatie en balroute.</b> Algemene acties zoals balverlies, onderschepping, duels en overtredingen registreer je in Snelle registratie. Zo voorkom je dubbele knoppen en dubbele invoer.';const hint=panel.querySelector('.afHint');if(hint)hint.textContent='Sleep/veeg de bal voor de route of tik een speler. Gebruik Snelle registratie voor acties zonder relevante veldlocatie.'}
function boot(){installFastResume();warmStartup();patchPlayerActionUi();simplifyActionField();new MutationObserver(simplifyActionField).observe(doc.body,{childList:true,subtree:true})}
installFastResume();
if(doc?.readyState==='loading')doc.addEventListener('DOMContentLoaded',boot);else boot();
})(typeof window!=='undefined'?window:globalThis);
