import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const storage={getItem(){return null},setItem(){},removeItem(){}};const document={readyState:'loading',addEventListener(){},getElementById(){return null},body:null};
const context={console,globalThis:null,window:null,document,localStorage:storage,fetch:async()=>{throw new Error('not called')},MutationObserver:class{observe(){}},WebSocket:class{}};context.globalThis=context;context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(new URL('./cloud-client.js',import.meta.url),'utf8'),context);vm.runInContext(fs.readFileSync(new URL('./realtime-native.js',import.meta.url),'utf8'),context);const realtimeCreate=context.ClubMatchV08CloudClient.createClient;vm.runInContext(fs.readFileSync(new URL('./roadmap-ux-v08.js',import.meta.url),'utf8'),context);vm.runInContext(fs.readFileSync(new URL('./action-field-standalone.js',import.meta.url),'utf8'),context);
const api=context.ClubMatchV08CloudClient;assert.equal(api.__sharedBrowserClient,true);const a=api.createClient('https://example.supabase.co','sb_publishable_test');const b=api.createClient('https://example.supabase.co','sb_publishable_test');assert.equal(a,b,'Browsermodules moeten exact dezelfde Realtime+Cloud-client delen');assert.equal(typeof a.channel,'function','Gedeelde client moet native Realtime behouden');
const customFetch=async()=>({ok:true,text:async()=>''});const c=api.createClient('https://example.supabase.co','sb_publishable_test',{fetch:customFetch,storage});const d=api.createClient('https://example.supabase.co','sb_publishable_test',{fetch:customFetch,storage});assert.notEqual(c,d,'Expliciete test/custom clients moeten geïsoleerd blijven');assert.notEqual(api.createClient,realtimeCreate,'Registry moet ná de Realtime-wrapper worden geïnstalleerd');
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');assert.ok(html.indexOf('cloud-client.js')<html.indexOf('realtime-native.js')&&html.indexOf('realtime-native.js')<html.indexOf('roadmap-ux-v08.js')&&html.indexOf('roadmap-ux-v08.js')<html.indexOf('action-field-standalone.js'),'Browservolgorde moet Cloud → Realtime → shared registry → legacy bootstrap zijn');
const source=fs.readFileSync(new URL('./roadmap-ux-v08.js',import.meta.url),'utf8');assert.match(source,/__sharedBrowserClient/);assert.match(source,/registry\.has/);assert.doesNotMatch(source,/get_my_team_seasons/,'Startup guard mag geen extra Cloud-RPC warmup meer starten');assert.doesNotMatch(source,/get_my_open_matches/,'Startup guard mag geen extra Cloud-RPC warmup meer starten');
console.log('PASS shared-cloud-client: exact one Realtime+auth browser client in real script order, custom clients isolated');
