/* ClubMatch Cloud v0.8 - training attendance, effort, quality and attitude UI */
(function(global){
'use strict';
const SUPABASE_URL='https://fnbqyogbamufytcabfzm.supabase.co';const SUPABASE_KEY='sb_publishable_skGPpngOQ_1OpEbreV2kXA__2OL_Mbp';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function scoreOptions(value){return '<option value="">—</option>'+[1,2,3,4,5].map(n=>`<option value="${n}"${Number(value)===n?' selected':''}>${n}</option>`).join('')}
function createTrainingUi(options={}){
 const doc=options.document||global.document,controller=options.controller,run=options.run||(async(label,fn)=>{try{return await fn()}catch(error){global.alert?.(`${label} mislukt: ${error.message||error}`);throw error}});if(!doc||!controller)throw new Error('Document en trainingcontroller zijn verplicht');let panel=null,selectedSessionId='';
 function ensureStyles(){if(doc.getElementById('v08TrainingStyles'))return;const s=doc.createElement('style');s.id='v08TrainingStyles';s.textContent='.trKpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin:9px 0}.trSessions{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.trSession{border:1px solid #d9c5eb;background:#faf7fd;color:#4b2672;border-radius:10px;padding:7px 9px;cursor:pointer}.trSession.active{background:#6f42c1;color:#fff}.trReviews{overflow:auto}.trReviews table{width:100%;border-collapse:collapse;min-width:1050px}.trReviews th,.trReviews td{padding:6px;border-top:1px solid #eee}.trReviews select,.trReviews input{padding:6px}.trScore{font-weight:900;color:#4b2672}.trModel{padding:8px 10px;background:#eef7ff;border:1px solid #b8d8f5;border-radius:10px;font-size:10px;margin:8px 0}@media(max-width:760px){.trKpis{grid-template-columns:repeat(2,1fr)}}';doc.head.appendChild(s)}
 function ensureMounted(){if(panel)return panel;ensureStyles();const app=doc.getElementById('appPanel');if(!app)throw new Error('Appscherm ontbreekt');panel=doc.createElement('section');panel.id='v08Training';panel.className='card hidden';app.firstElementChild?.after(panel);return panel}
 function teamOptions(state){return '<option value="">— kies team/seizoen —</option>'+state.teamSeasons.map(t=>`<option value="${esc(t.team_season_id)}"${state.teamSeasonId===t.team_season_id?' selected':''}>${esc(t.club_name)} · ${esc(t.team_name)} · ${esc(t.season_name)}</option>`).join('')}
 function playerMeta(state,id){return state.dashboard.players.find(p=>p.player_id===id)||{} }
 function render(state){const root=ensureMounted(),d=state.dashboard||{sessions:[],players:[]};if(selectedSessionId&&!d.sessions.some(s=>s.id===selectedSessionId))selectedSessionId='';if(!selectedSessionId&&d.sessions[0])selectedSessionId=d.sessions[0].id;const active=d.sessions.find(s=>s.id===selectedSessionId)||null;root.innerHTML=`<div class="sectionTitle"><div><h2 style="margin-bottom:3px">Trainingen</h2><div class="muted">Aanwezigheid en coachbeoordeling. Wedstrijdperformance en trainingsscore blijven bewust apart.</div></div><div class="controls"><button id="trRefresh" class="secondary" data-v08-action>↻ Training</button><button id="trClose" class="secondary" data-v08-action>Sluiten</button></div></div><label style="display:block;margin-top:8px">Team / seizoen<select id="trTeam">${teamOptions(state)}</select></label>${state.teamSeasonId?`<div class="grid3" style="margin-top:8px"><label>Datum<input id="trDate" type="date"></label><label>Tijd<input id="trTime" type="time"></label><label>Titel<input id="trTitle" value="Training"></label></div><label>Notitie<input id="trNotes" placeholder="Bijv. positiespel + partijvorm"></label><div class="controls" style="margin-top:7px"><button id="trCreate" data-v08-action>+ Training toevoegen</button></div>`:'<div class="muted" style="margin-top:8px">Kies eerst een team/seizoen.</div>'}${d.model?`<div class="trModel"><b>Trainingsscore 1–100</b> = inzet 40% + trainingskwaliteit 35% + houding/samenwerking 25%. Aanwezigheid staat apart en verlaagt deze kwaliteitsscore niet automatisch.</div>`:''}${d.players?.length?`<h3 style="margin-top:14px">Trainingsoverzicht spelers</h3><div style="overflow:auto"><table style="width:100%;min-width:800px;border-collapse:collapse"><thead><tr><th style="text-align:left">Speler</th><th>Aanwezig</th><th>Aanwezig %</th><th>Inzet</th><th>Kwaliteit</th><th>Houding</th><th>Trainingsscore</th></tr></thead><tbody>${d.players.map(p=>`<tr style="border-top:1px solid #eee"><td style="padding:6px"><b>#${esc(p.number??'—')} ${esc(p.display_name||p.name)}</b></td><td style="text-align:center">${p.present}/${p.sessions}</td><td style="text-align:center">${p.attendancePct}%</td><td style="text-align:center">${p.effort??'—'}</td><td style="text-align:center">${p.quality??'—'}</td><td style="text-align:center">${p.attitude??'—'}</td><td style="text-align:center"><span class="trScore">${p.trainingScore??'—'}</span></td></tr>`).join('')}</tbody></table></div>`:''}<h3 style="margin-top:14px">Trainingsmomenten</h3><div class="trSessions">${(d.sessions||[]).map(s=>`<button type="button" class="trSession ${s.id===selectedSessionId?'active':''}" data-tr-session="${esc(s.id)}">${esc(s.training_date)} · ${esc(s.title||'Training')}</button>`).join('')||'<span class="muted">Nog geen trainingen.</span>'}</div>${active?reviewHtml(state,active):''}`;bind(root,state,active);root.classList.remove('hidden');return root}
 function reviewHtml(state,session){return `<div class="sectionTitle"><div><h3 style="margin:0">${esc(session.training_date)} · ${esc(session.title)}</h3><div class="muted">${esc(session.notes||'')}</div></div><button type="button" id="trDelete" class="danger" data-v08-action>🗑 Training verwijderen</button></div><div class="trReviews"><table><thead><tr><th style="text-align:left">Speler</th><th>Status</th><th>Inzet 1–5</th><th>Kwaliteit 1–5</th><th>Houding 1–5</th><th>Coachnotitie</th><th></th></tr></thead><tbody>${(session.reviews||[]).map(r=>{const p=playerMeta(state,r.player_id);return `<tr data-tr-player="${esc(r.player_id)}"><td><b>#${esc(p.number??'—')} ${esc(p.display_name||p.name||r.player_id)}</b></td><td><select data-tr="attendanceStatus"><option value="unknown"${r.attendance_status==='unknown'?' selected':''}>Onbekend</option><option value="present"${r.attendance_status==='present'?' selected':''}>Aanwezig</option><option value="absent"${r.attendance_status==='absent'?' selected':''}>Afwezig</option><option value="injured"${r.attendance_status==='injured'?' selected':''}>Geblesseerd</option><option value="excused"${r.attendance_status==='excused'?' selected':''}>Afwezig met reden</option></select></td><td><select data-tr="effort">${scoreOptions(r.effort)}</select></td><td><select data-tr="quality">${scoreOptions(r.quality)}</select></td><td><select data-tr="attitude">${scoreOptions(r.attitude)}</select></td><td><input data-tr="coachNote" value="${esc(r.coach_note||'')}" placeholder="Optioneel"></td><td><button type="button" class="secondary" data-tr-save data-v08-action>Opslaan</button></td></tr>`}).join('')}</tbody></table></div>`}
 function val(row,key){return row.querySelector(`[data-tr="${key}"]`)?.value||''}
 function bind(root,state,active){root.querySelector('#trTeam').onchange=e=>e.target.value&&run('Trainingen laden',()=>controller.load(e.target.value));root.querySelector('#trRefresh').onclick=()=>run('Trainingen verversen',async()=>{await controller.loadTeams();if(controller.state.teamSeasonId)await controller.load(controller.state.teamSeasonId)});root.querySelector('#trClose').onclick=hide;root.querySelector('#trCreate')?.addEventListener('click',()=>run('Training toevoegen',()=>controller.createSession({trainingDate:root.querySelector('#trDate').value,scheduledTime:root.querySelector('#trTime').value,title:root.querySelector('#trTitle').value,notes:root.querySelector('#trNotes').value})));root.querySelectorAll('[data-tr-session]').forEach(btn=>btn.onclick=()=>{selectedSessionId=btn.dataset.trSession;render(controller.state)});root.querySelectorAll('[data-tr-save]').forEach(btn=>btn.onclick=()=>{const row=btn.closest('[data-tr-player]');return run('Training speler opslaan',()=>controller.saveReview(active.id,row.dataset.trPlayer,{attendanceStatus:val(row,'attendanceStatus'),effort:val(row,'effort'),quality:val(row,'quality'),attitude:val(row,'attitude'),coachNote:val(row,'coachNote')}))});root.querySelector('#trDelete')?.addEventListener('click',()=>{if(!global.confirm?.('Deze training en alle beoordelingen verwijderen?'))return;run('Training verwijderen',()=>controller.deleteSession(active.id))})}
 async function show(){await controller.loadTeams();const root=ensureMounted();render(controller.state);root.classList.remove('hidden')}
 function hide(){ensureMounted().classList.add('hidden')}
 function installButton(){const refresh=doc.getElementById('refreshMatchesBtn'),parent=refresh?.parentElement;if(!parent||doc.getElementById('trainingBtn'))return !!parent;const b=doc.createElement('button');b.id='trainingBtn';b.className='secondary';b.dataset.v08Action='';b.textContent='Trainingen';b.onclick=()=>run('Trainingen openen',show);parent.insertBefore(b,refresh);return true}
 return Object.freeze({show,hide,render,installButton,get visible(){return panel&&!panel.classList.contains('hidden')}})
}
function installStandalone(){if(!global.ClubMatchV08CloudClient?.createClient||!global.ClubMatchV08Training?.createTrainingController)return;const client=global.ClubMatchV08CloudClient.createClient(SUPABASE_URL,SUPABASE_KEY),controller=global.ClubMatchV08Training.createTrainingController({client,onChange:state=>ui.visible&&ui.render(state)}),ui=createTrainingUi({document:global.document,controller});let tries=0;const timer=global.setInterval(()=>{tries++;if(ui.installButton()||tries>200)global.clearInterval(timer)},50);global.ClubMatchV08TrainingApp={client,controller,ui}}
global.ClubMatchV08TrainingUi={createTrainingUi,installStandalone};global.document?.addEventListener?.('DOMContentLoaded',installStandalone);
})(typeof window!=='undefined'?window:globalThis);
