import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const context={console,globalThis:null,window:null};context.globalThis=context;context.window=context;vm.createContext(context);vm.runInContext(fs.readFileSync(new URL('./training-controller.js',import.meta.url),'utf8'),context);
const calls=[];const client={async rpc(name,params={}){calls.push({name,params});if(name==='get_my_team_seasons')return {data:[{team_season_id:'ts1',team_name:'O16-2'}],error:null};if(name==='get_training_dashboard_v08')return {data:{team_season_id:'ts1',sessions:[{id:'tr1',training_date:'2026-08-28'}],players:[{player_id:'p1',trainingScore:84}],model:{trainingScoreMax:100}},error:null};if(name==='create_training_session_v08')return {data:{ok:true,training_session_id:'tr1'},error:null};if(['save_training_review_v08','save_training_reviews_v08','delete_training_session_v08'].includes(name))return {data:{ok:true},error:null};return {data:null,error:new Error(`unexpected ${name}`)}}};
const T=context.ClubMatchV08Training.createTrainingController({client});await T.loadTeams();assert.equal(T.state.teamSeasons[0].team_name,'O16-2');await T.load('ts1');assert.equal(T.state.dashboard.players[0].trainingScore,84);
const created=await T.createSession({trainingDate:'2026-08-28',scheduledTime:'19:00',title:'Positiespel',notes:'Partijvorm'});assert.equal(created.created.training_session_id,'tr1');assert.ok(calls.some(c=>c.name==='create_training_session_v08'&&c.params.p_training_date==='2026-08-28'));
await T.saveReview('tr1','p1',{attendanceStatus:'present',effort:5,quality:4,attitude:5,coachNote:'sterk'});const save=calls.find(c=>c.name==='save_training_review_v08');assert.equal(save.params.p_effort,5);assert.equal(save.params.p_quality,4);assert.equal(save.params.p_attitude,5);
await T.saveAllReviews('tr1',[{playerId:'p1',attendanceStatus:'present',effort:'5',quality:'4',attitude:'5',coachNote:'sterk'}]);const batch=calls.find(c=>c.name==='save_training_reviews_v08');assert.ok(batch);assert.equal(batch.params.p_training_session_id,'tr1');assert.equal(batch.params.p_reviews.length,1);assert.equal(batch.params.p_reviews[0].player_id,'p1');
await T.deleteSession('tr1');assert.ok(calls.some(c=>c.name==='delete_training_session_v08'));
console.log('PASS training-controller: create + one-click batch save + attendance/assessment + deletion');
