/* ClubMatch Cloud v0.8 - training attendance, effort, quality and attitude UI */
(function(global){
'use strict';
const SUPABASE_URL='https://fnbqyogbamufytcabfzm.supabase.co';const SUPABASE_KEY='sb_publishable_skGPpngOQ_1OpEbreV2kXA__2OL_Mbp';
const LAST_TEAM_KEY='clubmatch.v08.training.team';const LAST_SESSION_KEY='clubmatch.v08.training.session';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function scoreOptions(value){return '<option value="">—</option>'+[1,2,3,4,5].map(n=>`<option value="${n}"${Number(value)===n?' selected':''}>${n}</option>`).join('')}
function todayLocal(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function storageGet(key){try{return global.localStorage?.getItem(key)||''}catch{return ''}}
function storageSet(key,value){try{if(value)global.localStorage?.setItem(key,String(value));else global.localStorage?.removeItem(key)}catch{}}
function createTrainingUi(options={}){
 const doc=options.document||global.document,controller=options.controller,run=options.run||(async(label,fn)=>{try{return await fn()}catch(error){global.alert?.(`${label} mislukt: ${error.message||error}`);throw error}});if(!doc||!controller)throw new Error('Document en trainingcontroller zijn verplicht');let panel=null,selectedSessionId='',dirty=false;
 function ensureStyles(){if(doc.getElementById('v08TrainingStyles'))return;const s=doc.createElement('style');s.id='v08TrainingStyles';s.textContent='.trKpis{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:7px;margin:9px 0}.trSessions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:8px 0}.trSessionCard{border:1px solid #d9c5eb;background:#faf7fd;color:#4b2672;border-radius:12px;padding:10px}.trSessionCard.active{border:3px solid #6f42c1;background:#f3ebfa}.trSessionHead{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.trSessionBtn{background:#fff!important;color:#4b2672!important;border:2px solid #8d6dac!important;white-space:nowrap}.trSessionCard.active .trSessionBtn{background:#6f42c1!important;color:#fff!important;border-color:#6f42c1!important}.trReviews{overflow:auto}.trReviews table{width:100%;border-collapse:collapse;min-width:930px}.trReviews th,.trReviews td{padding:6px;border-top:1px solid #eee}.trReviews select,.trReviews input{padding:6px}.trScore{font-weight:900;color:#4b2672}.trModel{padding:8px 10px;background:#eef7ff;border:1px solid #b8d8f5;border-radius:10px;font-size:10px;margin:8px 0}.trSaveBar{position:sticky;bottom:8px;display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:10px;padding:9px 10px;border:1px solid #d5c5e6;border-radius:12px;background:rgba(255,255,255,.96);box-shadow:0 4px 16px rgba(75,38,114,.12)}.trSaveBtn{background:#5b3591!important;color:#fff!important;border:2px solid #5b3591!important;padding:10px 17px!important}.trDirty{color:#9b6200;font-weight:800}.trSaved{color:#237a43;font-weight:800}.trCreateBox{border:1px dashed #bca3d2;background:#fcfaff;border-radius:12px;padding:10px;margin-top:10px}.trDeleteBtn{background:#fff!important;color:#983263!important;border:2px solid #b95078!important}.trResume{padding:9px 10px;border-radius:10px;background:#eef7ff;border:1px solid #b8d8f5;margin:8px 0;font-size:11px}@media(max-width:760px){.trKpis,.trSessions{grid-template-columns:1fr}.trSaveBar{align-items:stretch;flex-direction:column}.trSaveBtn{width:100%}.trSessionHead{flex-direction:column}.trSessionBtn{width:100%}}';doc.head.appendChild(s)}
 function ensureMounted(){if(panel)return panel;ensureStyles();const app=doc.getElementById('appPanel');if(!app)throw new Error('Appscherm ontbreekt');panel=doc.createElement('section');panel.id='v08Training';panel.className='card hidden';app.firstElementChild?.after(panel);return panel}
 function teamOptions(state){return '<option value="">— kies team/seizoen —</option>'+state.teamSeasons.map(t=>`<option value="${esc(t.team_season_id)}"${state.teamSeasonId===t.team_season_id?' selected':''}>${esc(t.club_name)} · ${esc(t.team_name)} · ${esc(t.season_name)}</option>`).join('')}
 function playerMeta(state,id){return state.dashboard.players.find(p=>p.player_id===id)||{} }
 function chooseSession(d){if(selectedSessionId&&d.sessions.some(s=>s.id===selectedSessionId))return selectedSessionId;const remembered=storageGet(LAST_SESSION_KEY);if(remembered&&d.sessions.some(s=>s.id===remembered))return remembered;return d.sessions[0]?.id||''}
 function sessionCard(s,active){const time=String(s.scheduled_time||'').slice(0,5);return `<div class="trSessionCard ${active?'active':''}" data-tr-session-card="${esc(s.id)}"><div class="trSessionHead"><div><b>${esc(s.training_date)}${time?' · '+esc(time):''} · ${esc(s.title||'Training')}</b><div class="muted">${esc(s.notes||'Opgeslagen training · je kunt deze later opnieuw openen en aanpassen.')}</div></div><button type="button" class="trSessionBtn" data-tr-open="${esc(s.id)}" data-v08-action>${active?'Geopend':'Openen / bewerken'}</button></div></div>`}
 function render(state){const root=ensureMounted(),d=state.dashboard||{sessions:[],players:[]};selectedSessionId=chooseSession(d);if(selectedSessionId)storageSet(LAST_SESSION_KEY,selectedSessionId);const active=d.sessions.find(s=>s.id===selectedSessionId)||null;root.innerHTML=`<div class="sectionTitle"><div><h2 style="margin-bottom:3px">Trainingen</h2><div class="muted">Opgeslagen trainingen kun je steeds opnieuw openen, aanpassen en weer opslaan.</div></div><div class="controls"><button id="trRefresh" class="secondary" data-v08-action>↻ Verversen</button><button id="trClose" class="secondary" data-v08-action>Sluiten</button></div></div><label style="display:block;margin-top:8px">Team / seizoen<select id="trTeam">${teamOptions(state)}</select></label>${state.teamSeasonId?`<div class="trCreateBox"><h3 style="margin-bottom:7px">+ Nieuw trainingsmoment</h3><div class="grid3"><label>Datum<input id="trDate" type="date" value="${todayLocal()}"></label><label>Tijd<input id="trTime" type="time"></label><label>Titel<input id="trTitle" value="Training"></label></div><label>Notitie<input id="trNotes" placeholder="Bijv. positiespel + partijvorm"></label><div class="controls" style="margin-top:7px"><button id="trCreate" class="trSaveBtn" data-v08-action>+ Nieuwe training aanmaken</button></div></div>`:'<div class="muted" style="margin-top:8px">Kies eerst een team/seizoen.</div>'}${d.model?`<div class="trModel"><b>Trainingsscore 1–100</b> = inzet 40% + trainingskwaliteit 35% + houding/samenwerking 25%. Aanwezigheid staat apart.</div>`:''}<h3 style="margin-top:14px">Opgeslagen trainingen</h3><div class="trResume">Klik <b>Openen / bewerken</b> om een eerder opgeslagen training te hervatten. Alle eerder opgeslagen spelerwaarden worden teruggeladen.</div><div class="trSessions">${(d.sessions||[]).map(s=>sessionCard(s,s.id===selectedSessionId)).join('')||'<span class="muted">Nog geen opgeslagen trainingen voor dit team.</span>'}</div>${active?reviewHtml(state,active):''}${d.players?.length?`<h3 style="margin-top:14px">Trainingsoverzicht spelers</h3><div style="overflow:auto"><table style="width:100%;min-width:800px;border-collapse:collapse"><thead><tr><th style="text-align:left">Speler</th><th>Aanwezig</th><th>Aanwezig %</th><th>Inzet</th><th>Kwaliteit</th><th>Houding</th><th>Trainingsscore</th></tr></thead><tbody>${d.players.map(p=>`<tr style="border-top:1px solid #eee"><td style="padding:6px"><b>#${esc(p.number??'—')} ${esc(p.display_name||p.name)}</b></td><td style="text-align:center">${p.present}/${p.sessions}</td><td style="text-align:center">${p.attendancePct}%</td><td style="text-align:center">${p.effort??'—'}</td><td style="text-align:center">${p.quality??'—'}</td><td style="text-align:center">${p.attitude??'—'}</td><td style="text-align:center"><span class="trScore">${p.trainingScore??'—'}</span></td></tr>`).join('')}</tbody></table></div>`:''}`;bind(root,state,active);root.classList.remove('hidden');return root}
 function reviewHtml(state,session){return `<div class="sectionTitle" style="margin-top:14px"><div><h3 style="margin:0">Training bewerken · ${esc(session.training_date)} · ${esc(String(session.scheduled_time||'').slice(0,5))}</h3><div class="muted">${esc(session.title||'Training')}${session.notes?' · '+esc(session.notes):''}</div></div><button type="button" id="trDelete" class="trDeleteBtn" data-v08-action>🗑 Training verwijderen</button></div><div class="muted" style="margin:5px 0">Je werkt in de opgeslagen training. Wijzig zoveel spelers als nodig en sla daarna alles in één keer op.</div><div class="trReviews"><table><thead><tr><th style="text-align:left">Speler</th><th>Status</th><th>Inzet 1–5</th><th>Kwaliteit 1–5</th><th>Houding 1–5</th><th>Coachnotitie</th></tr></thead><tbody>${(session.reviews||[]).map(r=>{const p=playerMeta(state,r.player_id);return `<tr data-tr-player="${esc(r.player_id)}"><td><b>#${esc(p.number??'—')} ${esc(p.display_name||p.name||r.player_id)}</b></td><td><select data-tr="attendanceStatus"><option value="unknown"${r.attendance_status==='unknown'?' selected':''}>Onbekend</option><option value="present"${r.attendance_status==='present'?' selected':''}>Aanwezig</option><option value="absent"${r.attendance_status==='absent'?' selected':''}>Afwezig</option><option value="injured"${r.attendance_status==='injured'?' selected':''}>Geblesseerd</option><option value="excused"${r.attendance_status==='excused'?' selected':''}>Afwezig met reden</option></select></td><td><select data-tr="effort">${scoreOptions(r.effort)}</select></td><td><select data-tr="quality">${scoreOptions(r.quality)}</select></td><td><select data-tr="attitude">${scoreOptions(r.attitude)}</select></td><td><input data-tr="coachNote" value="${esc(r.coach_note||'')}" placeholder="Optioneel"></td></tr>`}).join('')}</tbody></table></div><div class="trSaveBar"><div id="trSaveState" class="${dirty?'trDirty':'trSaved'}">${dirty?'Wijzigingen nog niet opgeslagen':'Opgeslagen training geladen · alles opgeslagen'}</div><button type="button" id="trSaveAll" class="trSaveBtn" data-v08-action>✓ Wijzigingen opslaan</button></div>`}
 function val(row,key){return row.querySelector(`[data-tr="${key}"]`)?.value||''}
 function collectReviews(root){return [...root.querySelectorAll('[data-tr-player]')].map(row=>({playerId:row.dataset.trPlayer,attendanceStatus:val(row,'attendanceStatus'),effort:val(row,'effort'),quality:val(row,'quality'),attitude:val(row,'attitude'),coachNote:val(row,'coachNote')}))}
 function markDirty(root){dirty=true;const state=root.querySelector('#trSaveState');if(state){state.textContent='Wijzigingen nog niet opgeslagen';state.className='trDirty'}}
 function openSession(id){if(dirty&&!global.confirm?.('Er zijn niet-opgeslagen wijzigingen. Andere training openen zonder opslaan?'))return;dirty=false;selectedSessionId=id;storageSet(LAST_SESSION_KEY,id);render(controller.state)}
 function bind(root,state,active){root.querySelector('#trTeam').onchange=e=>e.target.value&&run('Trainingen laden',async()=>{dirty=false;selectedSessionId='';storageSet(LAST_TEAM_KEY,e.target.value);storageSet(LAST_SESSION_KEY,'');return controller.load(e.target.value)});root.querySelector('#trRefresh').onclick=()=>run('Trainingen verversen',async()=>{dirty=false;await controller.loadTeams();if(controller.state.teamSeasonId)await controller.load(controller.state.teamSeasonId)});root.querySelector('#trClose').onclick=hide;root.querySelector('#trCreate')?.addEventListener('click',()=>run('Training aanmaken',async()=>{const trainingDate=root.querySelector('#trDate').value,scheduledTime=root.querySelector('#trTime').value,title=root.querySelector('#trTitle').value,existing=(controller.state.dashboard.sessions||[]).find(s=>s.training_date===trainingDate&&String(s.scheduled_time||'').slice(0,5)===scheduledTime);if(existing){selectedSessionId=existing.id;storageSet(LAST_SESSION_KEY,existing.id);dirty=false;render(controller.state);global.alert?.('Er bestaat al een training voor dit team op deze datum en tijd. De bestaande training is geopend zodat je die kunt aanpassen.');return {existing:true,training_session_id:existing.id}}dirty=false;const result=await controller.createSession({trainingDate,scheduledTime,title,notes:root.querySelector('#trNotes').value});selectedSessionId=result?.created?.training_session_id||controller.state.dashboard.sessions?.[0]?.id||'';storageSet(LAST_SESSION_KEY,selectedSessionId);render(controller.state);return result}));root.querySelectorAll('[data-tr-open]').forEach(btn=>btn.onclick=()=>openSession(btn.dataset.trOpen));root.querySelectorAll('[data-tr-player] select,[data-tr-player] input').forEach(el=>el.addEventListener('change',()=>markDirty(root)));root.querySelector('#trSaveAll')?.addEventListener('click',()=>run('Training opslaan',async()=>{const result=await controller.saveAllReviews(active.id,collectReviews(root));dirty=false;selectedSessionId=active.id;storageSet(LAST_SESSION_KEY,active.id);render(controller.state);return result}));root.querySelector('#trDelete')?.addEventListener('click',()=>{if(!global.confirm?.('Deze training en alle beoordelingen verwijderen?'))return;run('Training verwijderen',async()=>{dirty=false;selectedSessionId='';storageSet(LAST_SESSION_KEY,'');return controller.deleteSession(active.id)})})}
 async function show(){await controller.loadTeams();let teamId=controller.state.teamSeasonId||storageGet(LAST_TEAM_KEY);if(!teamId&&controller.state.teamSeasons.length===1)teamId=controller.state.teamSeasons[0].team_season_id;if(teamId&&!controller.state.teamSeasons.some(t=>t.team_season_id===teamId))teamId='';if(teamId){storageSet(LAST_TEAM_KEY,teamId);await controller.load(teamId)}const root=ensureMounted();render(controller.state);root.classList.remove('hidden')}
 function hide(){ensureMounted().classList.add('hidden')}
 function installButton(){const refresh=doc.getElementById('refreshMatchesBtn'),parent=refresh?.parentElement;if(!parent||doc.getElementById('trainingBtn'))return !!parent;const b=doc.createElement('button');b.id='trainingBtn';b.className='secondary';b.dataset.v08Action='';b.textContent='Trainingen';b.onclick=()=>run('Trainingen openen',show);parent.insertBefore(b,refresh);return true}
 return Object.freeze({show,hide,render,installButton,get visible(){return panel&&!panel.classList.contains('hidden')}})
}
function installStandalone(){if(!global.ClubMatchV08CloudClient?.createClient||!global.ClubMatchV08Training?.createTrainingController)return;const client=global.ClubMatchV08CloudClient.createClient(SUPABASE_URL,SUPABASE_KEY),controller=global.ClubMatchV08Training.createTrainingController({client,onChange:state=>ui.visible&&ui.render(state)}),ui=createTrainingUi({document:global.document,controller});let tries=0;const timer=global.setInterval(()=>{tries++;if(ui.installButton()||tries>200)global.clearInterval(timer)},50);global.ClubMatchV08TrainingApp={client,controller,ui}}
global.ClubMatchV08TrainingUi={createTrainingUi,installStandalone};global.document?.addEventListener?.('DOMContentLoaded',installStandalone);
})(typeof window!=='undefined'?window:globalThis);
