/* ClubMatch Cloud v0.8 - restart-safe speech + typed fallback + explicit confirmation */
(function(global){
'use strict';
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function createVoiceUi(options={}){
  const doc=options.document||global.document,controller=options.controller;if(!doc||!controller)throw new Error('Document en spraakcontroller zijn verplicht');
  const Recognition=options.SpeechRecognition||global.SpeechRecognition||global.webkitSpeechRecognition||null;
  let panel=null,recognition=null,listening=false,localMessage='',watchdog=null,sessionNo=0;
  function ensureStyles(){if(doc.getElementById('v08VoiceStyles'))return;const s=doc.createElement('style');s.id='v08VoiceStyles';s.textContent=`.voiceRow{display:grid;grid-template-columns:1fr auto auto;gap:7px;align-items:end}.voicePending{margin-top:8px;padding:9px;border:1px solid #cdb6e6;background:#f8f3fd;border-radius:10px}.voiceListening{animation:v08pulse 1s infinite}.voiceBtn{border:1px solid #6c63a8!important;background:#f1f0ff!important;color:#39306b!important}.voiceCheckBtn{border:1px solid #5d48a1!important;background:#5d48a1!important;color:#fff!important}.voiceConfirmBtn{background:#314e9b!important;color:#fff!important;border:0!important}.voiceCancelBtn{background:#f2f0f5!important;color:#594d66!important;border:1px solid #cfc5d7!important}@keyframes v08pulse{50%{opacity:.55}}@media(max-width:650px){.voiceRow{grid-template-columns:1fr}.voiceRow button{width:100%}}`;doc.head.appendChild(s)}
  function ensureMounted(){if(panel)return panel;ensureStyles();const app=doc.getElementById('appPanel');if(!app)throw new Error('ClubMatch-appscherm ontbreekt');panel=doc.createElement('section');panel.id='v08Voice';panel.className='card';const correction=doc.getElementById('v08Corrections'),live=app.querySelector('.liveLayout');if(correction)app.insertBefore(panel,correction);else if(live)app.insertBefore(panel,live);else app.appendChild(panel);return panel}
  function messageFor(state){if(localMessage)return localMessage;if(state.lastError)return state.lastError;if(!state.hasMatch)return 'Open eerst een actieve wedstrijd. Typen blijft beschikbaar zodra een wedstrijd actief is.';if(!Recognition)return 'Microfoonherkenning is in deze browser niet beschikbaar. Typ de opdracht hieronder.';return 'Je kunt een naam of rugnummer zeggen. Iedere luisteractie start een verse herkenningssessie.'}
  function render(state=controller.state){const root=ensureMounted(),pending=state.pending;root.innerHTML=`<div class="sectionTitle"><div><h2 style="margin-bottom:3px">Spraak & snelle invoer</h2><div class="muted">Nederlands · spelernaam of rugnummer · altijd eerst controleren en bevestigen</div></div><span class="badge">${Recognition?'MIC + TEKST':'TEKST'}</span></div><div class="voiceRow" style="margin-top:9px"><label>Opdracht<input id="voiceText" value="${esc(state.lastText||'')}" placeholder="Bijv. wissel Wai Sam voor Shane"></label><button id="voiceListen" class="voiceBtn ${listening?'voiceListening':''}" data-v08-action ${!Recognition||!state.hasMatch?'disabled':''}>${listening?'● Luistert…':'🎙 Luisteren'}</button><button id="voiceCheck" class="voiceCheckBtn" data-v08-action ${!state.hasMatch?'disabled':''}>Opdracht controleren</button></div><div id="voiceMessage" class="muted" style="margin-top:6px">${esc(messageFor(state))}</div><div class="muted" style="margin-top:5px">Voorbeelden: “wissel Wai Sam voor Shane” · “doelpunt nummer 13 assist 9” · “positie Wai Sam rechtsbuiten” · “balverlies Wai Sam” · “onderschepping 13” · “pauze”</div>${pending?`<div class="voicePending"><b>ClubMatch begrijpt:</b> ${esc(pending.summary)}<div class="controls" style="margin-top:7px"><button id="voiceConfirm" class="voiceConfirmBtn" data-v08-action>✓ Bevestigen</button><button id="voiceCancel" class="voiceCancelBtn" data-v08-action>Annuleren</button></div></div>`:''}`;bind(root);return root}
  function prepare(text){localMessage='';const result=controller.prepare(text);render(controller.state);return result}
  function bind(root){const input=root.querySelector('#voiceText');input?.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();prepare(input.value)}});root.querySelector('#voiceCheck')?.addEventListener('click',()=>prepare(input?.value||''));root.querySelector('#voiceCancel')?.addEventListener('click',()=>{controller.cancel();localMessage='Opdracht geannuleerd; er is niets opgeslagen.';render(controller.state)});root.querySelector('#voiceConfirm')?.addEventListener('click',()=>options.run?.('Spraakopdracht bevestigen',async()=>{const summary=controller.state.pending?.summary||'Opdracht';const result=await controller.confirm();localMessage=`Opgeslagen: ${summary}`;render(controller.state);return result}));root.querySelector('#voiceListen')?.addEventListener('click',startListening)}
  function clearWatchdog(){if(watchdog){global.clearTimeout?.(watchdog);watchdog=null}}
  function disposeRecognition(abort=false){clearWatchdog();const r=recognition;recognition=null;if(abort&&r){try{r.abort?.()}catch{}}}
  function createRecognition(){if(!Recognition)return null;disposeRecognition(true);const current=++sessionNo,r=new Recognition();recognition=r;r.lang='nl-NL';r.continuous=false;r.interimResults=false;r.maxAlternatives=3;r.onstart=()=>{if(current!==sessionNo)return;listening=true;localMessage='Luisteren… spreek één korte opdracht uit.';render(controller.state);clearWatchdog();watchdog=global.setTimeout?.(()=>{if(current!==sessionNo)return;localMessage='Geen spraak ontvangen. Probeer opnieuw of typ de opdracht.';listening=false;disposeRecognition(true);render(controller.state)},12000)};r.onresult=event=>{if(current!==sessionNo)return;const candidates=[],first=event?.results?.[0];if(first){for(let i=0;i<first.length;i++)if(first[i]?.transcript)candidates.push(first[i].transcript)}const spoken=candidates[0]||'';listening=false;disposeRecognition(false);localMessage='';prepare(spoken)};r.onerror=event=>{if(current!==sessionNo)return;const code=event?.error||'onbekend';listening=false;disposeRecognition(false);if(code==='not-allowed'||code==='service-not-allowed')localMessage='Microfoontoegang is geweigerd. Je kunt dezelfde opdracht typen.';else if(code==='no-speech')localMessage='Geen spraak herkend. Klik opnieuw op Luisteren of typ de opdracht.';else if(code==='network')localMessage='Spraakdienst tijdelijk niet bereikbaar. Klik opnieuw op Luisteren; er wordt een nieuwe sessie gestart.';else localMessage=`Spraakherkenning lukte niet (${code}). Klik opnieuw of typ de opdracht.`;render(controller.state)};r.onend=()=>{if(current!==sessionNo)return;clearWatchdog();if(listening){listening=false;localMessage='Luistersessie beëindigd. Klik opnieuw op Luisteren voor een nieuwe sessie.'}recognition=null;render(controller.state)};return r}
  function startListening(){if(!controller.state.hasMatch){localMessage='Open eerst een actieve wedstrijd.';return render(controller.state)}if(listening){stopListening();localMessage='Luisteren gestopt.';return render(controller.state)}const r=createRecognition();if(!r){localMessage='Microfoonherkenning is niet beschikbaar; typ de opdracht.';return render(controller.state)}try{r.start()}catch(error){listening=false;disposeRecognition(true);localMessage=`Microfoon kon niet starten: ${error.message||error}. Klik opnieuw; ClubMatch maakt dan een nieuwe sessie.`;render(controller.state)}}
  function stopListening(){sessionNo++;listening=false;disposeRecognition(true)}
  function setSnapshot(snapshot){controller.setSnapshot(snapshot);return render(controller.state)}
  function clear(){stopListening();controller.clear();localMessage='';if(panel)render(controller.state)}
  return Object.freeze({render,setSnapshot,prepare,startListening,stopListening,clear,get supported(){return !!Recognition},get listening(){return listening}})
}
global.ClubMatchV08VoiceUi={createVoiceUi};
})(typeof window!=='undefined'?window:globalThis);
