import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const context={console,globalThis:null,window:null};context.globalThis=context;context.window=context;context.ClubMatchV08EventDescriber={PLAYER_ACTION_LABELS:{ball_loss:'Balverlies'}};vm.createContext(context);
for(const file of ['voice-command.js','voice-controller.js'])vm.runInContext(fs.readFileSync(new URL(`./${file}`,import.meta.url),'utf8'),context);
const calls=[];
const runtime={async substitute(payload){calls.push(['substitute',payload]);return {ok:true}},async swapPositions(payload){calls.push(['swap',payload]);return {ok:true}},async changePosition(payload){calls.push(['position',payload]);return {ok:true}},async recordGoal(payload){calls.push(['goal',payload]);return {ok:true}},async advanceClock(payload){calls.push(['clock',payload]);return {ok:true}}};
const playerActions={async record(playerId,action,note){calls.push(['playerAction',{playerId,action,note}]);return {ok:true}}};
const snapshot={match:{id:'m1'},players:[{player_id:'p13',display_name:'Wai Sam',shirt_number:13,selected:true},{player_id:'p9',display_name:'Shane',shirt_number:9,selected:true},{player_id:'p10',display_name:'Siem',shirt_number:10,selected:true}]};
const C=context.ClubMatchV08VoiceController.createVoiceController({runtime,playerActions});
let parsed=C.prepare('wissel 13 voor 9');assert.equal(parsed.ok,false);assert.match(C.state.lastError,/Open eerst/);assert.equal(calls.length,0);C.setSnapshot(snapshot);
parsed=C.prepare('wissel Wai Sam voor Shane');assert.equal(parsed.ok,true);assert.equal(C.state.pending.action,'SUBSTITUTION');assert.equal(calls.length,0,'voorstel mag nooit meteen schrijven');C.cancel();assert.equal(calls.length,0);
C.prepare('wissel 13 voor 9');await C.confirm();assert.equal(calls[0][0],'substitute');
C.prepare('doelpunt Wai Sam assist Shane');await C.confirm();assert.equal(calls[1][0],'goal');
C.prepare('positie 13 naar rechtsbuiten');await C.confirm();assert.equal(calls[2][0],'position');
C.prepare('ruil 13 met 10');await C.confirm();assert.equal(calls[3][0],'swap');
C.prepare('pauze');await C.confirm();assert.equal(calls[4][0],'clock');
C.prepare('balverlies Wai Sam');assert.equal(calls.length,5,'speleractie moet eveneens eerst voorstel blijven');await C.confirm();assert.equal(calls[5][0],'playerAction');assert.deepEqual(calls[5][1],{playerId:'p13',action:'ball_loss',note:''});
parsed=C.prepare('verwijder wedstrijd');assert.equal(parsed.ok,false);assert.equal(calls.length,6);C.clear();assert.equal(C.state.hasMatch,false);
console.log('PASS voice-controller: voorstellen + expliciet bevestigen + speleracties');
